### ISSUE TITLE
Subtitle Effect Issue

### ISSUE THREAD

**Issue by jazmac** [shinchiro/mpv-winbuild-cmake#10]
## Expected Behavior
A transparent outline of the text should overlay itself on top of the already displayed words.

## Current Behavior
The transparency effect doesn't display correctly and instead the shadow alpha within the text outline is bleeding inwards.

## Possible Solution
A pseudo workaround is to remove the \4a shadow alpha effect using a subtitle editing program by also setting it to transparent.

The subtitles display correctly in the video player MPC-HC.

## Steps to Reproduce
The specific issue is found at timestamps 0:17:57.43 > 0:18:03.06 within the subtitles linked below. Playing the subtitles through the MPV video player and at the timestamps mentioned previously will reproduce the issue.

## Detailed Description

Inspecting the subtitles using the subtitle editing program Aegisub, the effect in question found at timestamps 0:17:57.43 > 0:18:03.06, it appears to be the effect called "1a&HFF&" which is responsible for setting the alpha (transparency) of the text.

According to Aegisub's own documentation (http://docs.aegisub.org/3.2/ASS_Tags/), when used, it effectively leaves only the border and shadow. However for some unknown reason when displaying them in MPV, the \4a or "shadow alpha" is bleeding inwards into the text.

Comparison;

Working as intended;
https://jazmac.prodibi.com/a/q4mjl2xzj07vvm/i/06de2yy1edqy6g?s=FOpTYi6jm3BiocR3V8rWbczAv%2FIV6pbVDjvEvWMwlaQ%3D

Bugged;
https://jazmac.prodibi.com/a/q4mjl2xzj07vvm/i/z9lgz4jyd0ze5l?s=kiY5CbeoTURsEzZ3Zw2k5xsj09axjaOXrpmVe%2F4xZ3c%3D

The text displayed in Aegisub;
https://jazmac.prodibi.com/a/q4mjl2xzj07vvm/i/78rw64dy0v2xvy?s=UymCkapN1L1tV6S40EG668ePbNABQ17iI7TC9OByzZE%3D

download link to the subtitles;
https://mega.nz/#!nbID3IRS!qQJ2y02Bu1E319NkPpeZcG3Q5iFv7c_OZDPl7vb2Ct8

**Comment by shinchiro** [comment]
Please report it on mpv repo instead: https://github.com/mpv-player/mpv/issues
