### ISSUE TITLE
MPV quit unexpectedly when I move its window

### ISSUE THREAD

**Issue by RnYi** [shinchiro/mpv-winbuild-cmake#105]
I print a log file and find some info may give a help:

[   1.269][d][vo/gpu/win32] move window: 501:307
[   1.271][d][cplayer] Run command: quit, flags=73, args=[code="4"]
[   1.271][i][cplayer] Exiting... (Quit)
[   1.271][d][cplayer] Run command: change-list, flags=64, args=[name="shared-script-properties", operation="remove", value="osc-margins"]
[   1.271][v][cplayer] Set property: shared-script-properties -> 1
[   1.271][d][autoload] Exiting...
[   1.271][d][ytdl_hook] Exiting...
[   1.271][d][console] Exiting...
[   1.271][d][stats] Exiting...
[   1.271][d][osc] Exiting...
[   1.273][d][vo/gpu] flushing shader cache
[   1.278][v][vo/gpu/win32] uninit

I can send you the full log if you need.

**Comment by myfreeer** [comment]
Maybe posting this to [upstream](https://github.com/mpv-player/mpv) would help.

**Comment by shinchiro** [comment]
yeah, right
