### ISSUE TITLE
Performing configure step for 'ffmpeg' error

### ISSUE THREAD

**Issue by bladem2003** [shinchiro/mpv-winbuild-cmake#106]
i have always the same error

![ninja_ffmpeg](https://user-images.githubusercontent.com/47271861/104964976-4b8fd680-59e6-11eb-883d-5d8a39fb58ec.png)

Debian 10.6 
Thanks!

edit:
i have disable in ffmpeg.cmake the --enable-libssh and now its compile fine

**Comment by tasty0tomato** [comment]
maybe pull a request?
