### ISSUE TITLE
build v0.32.0 stable

### ISSUE THREAD

**Issue by bladem2003** [shinchiro/mpv-winbuild-cmake#107]
how can i build this version ?

**Comment by garoto** [comment]
Add `GIT_TAG "v0.32.0"` just below `GIT_REPOSITORY` in mpv.cmake, and then `ninja removebuild && ninja mpv`.

I just built 3 different tags using this method. Seems to work.

**Comment by bladem2003** [comment]
Thank you.

**Comment by shinchiro** [comment]
Correct
