### ISSUE TITLE
May be ignorance not an issue - 

### ISSUE THREAD

**Issue by AVRider** [shinchiro/mpv-winbuild-cmake#110]
shinchiro: I need to include both ASIO and WASAPI "extended" audio output options to play DSF files, natively. Presently, I can do this with both FB2K (with additional components added) and TEAC HR Player which has its own ASIO USB driver (with various plugins included). These additional components and plugins are key to accomplishing the above objective. 
Now, the results of --audio-device=help produces only the default devices which are inadequate. For example, FB2K produces a comprehensive list of devices to choose from (ASIO USB DRIVER and WASAPI devices 
![FB2K Device Options](https://user-images.githubusercontent.com/19938478/107881519-c0a1df00-6eb2-11eb-9a36-75ac44a52871.jpg)
). 
I choose one of the many options beyond the defaults in order to play these DSF files natively. 

To be clear, I can play these files now on MPV but not native DSD. The output is PCM at 192kHz, not 2.8 or 5.6MHz.

Do I need to incorporate libmpv.dll into the MPV folder to accomplish this? Also, how would I then execute the --audio-device=help command to produce the extended list of options in order to get the needed syntax to included in the --audio-device=<name>/<device> command?

Again, excuse my ignorance of your project inner workings. There are probably a number of other questions I should be asking?

Thank you.

**Comment by shinchiro** [comment]
Better ask on main repo's tracker though:
https://github.com/mpv-player/mpv

**Comment by AVRider** [comment]
ok thanks
