### ISSUE TITLE
Fetching RSS feed for youtube-dl: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

### ISSUE THREAD

**Issue by Pentaphon** [shinchiro/mpv-winbuild-cmake#111]
I get this when trying to update youtube-dl.

**Comment by shinchiro** [comment]
Worked fine to me.

**Comment by Pentaphon** [comment]
> Worked fine to me.

Hmmm it does work now. That's weird. I wonder why that happened. It came up twice but now it's fine. Sorry.
