### ISSUE TITLE
[Question]Is there anything blocking newer builds (specifically 0.33.1)?

### ISSUE THREAD

**Issue by Jules-A** [shinchiro/mpv-winbuild-cmake#115]
Sorry about this not being a project issue (you can close immediately) but I don't have a build environment set up and I was just wondering if there were any blockers or reason why there haven't been any new MPV Windows builds? While I'm more interested in few unrelated fixes, the last build was before the 0.33.1 release which included a security fix which says  "Users are advised to upgrade immediately". I feel this is confusing for people who are relying on prebuilt binaries.

**Comment by CharlesMengCA** [comment]
Hi shinchiro , my customized builds after April 20 have following issue.
https://github.com/mpv-player/mpv/issues/8775

I don't see a new build from you After Apr 4, could you create a build to see if you have the same problem?

Thanks a million time for your project and your hard work.

**Comment by Jules-A** [comment]
Since there was an official build I'm going to close this issue, @CharlesMengCA if you still have that issue you should probably make a new issue.
