### ISSUE TITLE
How to build a stable release

### ISSUE THREAD

**Issue by tasty0tomato** [shinchiro/mpv-winbuild-cmake#117]
the default setting is to build a latest master version and what should I do if I just want to build a stable build such as `v0.33.1`

**Comment by shinchiro** [comment]
Type `ninja mpv-stable` after built gcc. But currently, mpv-stable is broken since after major changes on current libplacebo git master

**Comment by tasty0tomato** [comment]
Thanks.

**Comment by tasty0tomato** [comment]
![ubuntu2004_3fQXmnCSIM](https://user-images.githubusercontent.com/48764449/116835034-46504380-abf3-11eb-88a4-11096762aa05.png)
It seems it does not use the right url
