### ISSUE TITLE
It seems that mpv-stable does not download the right target

### ISSUE THREAD

**Issue by tasty0tomato** [shinchiro/mpv-winbuild-cmake#119]
![ubuntu2004_3fQXmnCSIM](https://user-images.githubusercontent.com/48764449/117098291-9a4c5b00-ada0-11eb-8aca-6f6e68d2aad3.png)

**Comment by tasty0tomato** [comment]
Actually, there is the lastest mpv downloaded.
![explorer_hWUidvG3Zt](https://user-images.githubusercontent.com/48764449/117301497-4713fe80-aead-11eb-9fb2-b573767626fa.png)

**Comment by shinchiro** [comment]
Working fine on my side. Maybe you forgot to run `ninja mpv-stable` as `sudo`

**Comment by tasty0tomato** [comment]
> Working fine on my side. Maybe you forgot to run `ninja mpv-stable` as `sudo`

Really? I used Ubuntu 20.04 LTS with WSL, and it **definitely** not works
