### ISSUE TITLE
Compiling for LGPL

### ISSUE THREAD

**Issue by matthew-dews** [shinchiro/mpv-winbuild-cmake#12]
I was trying to follow [mpv's instructions](https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md) to make a Windows build of libmpv which is LGPL compliant. The version of FFmpeg that those steps use is not LGPL. While looking around at other options I came across this repo.

Do you have any thoughts or advice for compiling libmpv as LGPL? I know I will need to remove the --enable-gpl option from the FFmpeg build and add --enable-lgpl in the mpv build.

**Comment by matthew-dews** [comment]
Just to follow up in case others have this question:
From ffmpeg you must remove
--enable-gpl
--enable-version3
--enable-nonfree
--enable-avisynth
--enable-gmp
--enable-libx264
--enable-libaom (this doesn't result in a configure error, but a compile time one)
--enable-libxvid

From MPV add
--enable-lgpl
and remove
--enable-dvdread
--enable-dvdnav
--enable-rubberband

**Comment by alexmercerind** [comment]
> Just to follow up in case others have this question: From ffmpeg you must remove --enable-gpl --enable-version3 --enable-nonfree --enable-avisynth --enable-gmp --enable-libx264 --enable-libaom (this doesn't result in a configure error, but a compile time one) --enable-libxvid
> 
> From MPV add --enable-lgpl and remove --enable-dvdread --enable-dvdnav --enable-rubberband

Hello @matthew-dews,

Were you able to compile successfully? I've been getting error at compilation.

> FAILED: packages/ffmpeg-prefix/src/ffmpeg-stamp/ffmpeg-configure /home/runner/work/MPV-LGPL-Windows/MPV-LGPL-Windows/packages/ffmpeg-prefix/src/ffmpeg-stamp/ffmpeg-configure 
cd /home/runner/work/MPV-LGPL-Windows/MPV-LGPL-Windows/packages/ffmpeg-prefix/src/ffmpeg-build && /usr/local/bin/cmake -P /home/runner/work/MPV-LGPL-Windows/MPV-LGPL-Windows/packages/ffmpeg-prefix/src/ffmpeg-stamp/ffmpeg-configure-.cmake && /usr/local/bin/cmake -E touch /home/runner/work/MPV-LGPL-Windows/MPV-LGPL-Windows/packages/ffmpeg-prefix/src/ffmpeg-stamp/ffmpeg-configure
CMake Error at /home/runner/work/MPV-LGPL-Windows/MPV-LGPL-Windows/packages/ffmpeg-prefix/src/ffmpeg-stamp/ffmpeg-configure-.cmake:49 (message):
  Command failed: 1

>   '/home/runner/work/MPV-LGPL-Windows/MPV-LGPL-Windows/exec' '/home/runner/work/MPV-LGPL-Windows/MPV-LGPL-Windows/packages/ffmpeg-prefix/src/ffmpeg/configure' '--cross-prefix=x86_64-w64-mingw32-' '--prefix=/home/runner/work/MPV-LGPL-Windows/MPV-LGPL-Windows/install/mingw' '--arch=x86_64' '--target-os=mingw32' '--target-exec=wine' '--pkg-config-flags=--static' '--enable-cross-compile' '--enable-runtime-cpudetect' '--enable-postproc' '--enable-vapoursynth' '--enable-libass' '--enable-libbluray' '--enable-libfreetype' '--enable-libfribidi' '--enable-libmodplug' '--enable-libopenmpt' '--enable-libmp3lame' '--enable-libopus' '--enable-libsoxr' '--enable-libspeex' '--enable-libvorbis' '--enable-libbs2b' '--enable-libvpx' '--enable-libwebp' '--enable-libx265' '--enable-libaom' '--enable-libdav1d' '--enable-libzimg' '--enable-libtls' '--enable-libxml2' '--enable-libmysofa' '--enable-libssh' '--enable-libsrt' '--enable-libmfx' '--enable-cuda' '--enable-cuvid' '--enable-nvdec' '--enable-nvenc' '--enable-amf' '--disable-decoder=libaom_av1' '--extra-cflags='-DMODPLUG_STATIC''

Thanks

**Comment by matthew-dews** [comment]
Hi @alexmercerind,

Unfortunately it's been a long time since I've touched this and I ultimately went in another direction than libmpv, so I can't provide any insight here

**Comment by adlerzei** [comment]
If anyone comes back to this in the future, from ffmpeg you must also remove:
--enable-libdavs2
--enable-libx265
--enable-mbedtls

**Comment by alexmercerind** [comment]
I configured my fork for LGPL: https://github.com/alexmercerind/mpv-win32-cmake.
And... it's compiling successfully.
