### ISSUE TITLE
--mf-fps 0.25 does not work on windows 10

### ISSUE THREAD

**Issue by tmpsa** [shinchiro/mpv-winbuild-cmake#12]
I can successfully make a slide show on Linux with 'mpv -vo drm --mf-fps 0.25 foo.jpg bar.jpg', which shows  both images during 4 seconds each. (That's 0.25 frames per second). But on Windows the images are shown only briefly, presumably just as long as it takes for mpv to reload next image. This looks like a bug in the Windows port.

**Comment by shinchiro** [comment]
Your open issue here:
https://github.com/mpv-player/mpv/issues

**Comment by shinchiro** [comment]
I never tried to compile as LGPL, but it should be straightforward. Aside from `--enable-gpl` switch, you may need to disable other features in ffmpeg.
