### ISSUE TITLE
New question when building mpv-stable

### ISSUE THREAD

**Issue by tasty0tomato** [shinchiro/mpv-winbuild-cmake#120]
https://github.com/shinchiro/mpv-winbuild-cmake/issues/119
I know why this happened. Because I use `sudo su` at first and it seems that the root user has some error with this.
But now there is new question...

![ubuntu2004_J9rcSuaLFQ](https://user-images.githubusercontent.com/48764449/117401768-c2ba8d80-af37-11eb-81b9-b9df1b99c63b.png)
![ubuntu2004_SuM3sebkWG](https://user-images.githubusercontent.com/48764449/117401775-c51ce780-af37-11eb-9355-1b827d707907.png)

**Comment by shinchiro** [comment]
Yeah, I already know its broken since the stable mpv is incompatible to link with current libplacebo's git master

**Comment by tasty0tomato** [comment]
@shinchiro I do not know anything about libplacebo, and I just want to know the reason why building stable mpv needs libplacebo and what can we do to make changes to libplacebo.

**Comment by shinchiro** [comment]
`libplacebo` needed for vulkan support. Replace to `--disable-vulkan` in `mpv.cmake`

**Comment by tasty0tomato** [comment]
Was this problem solved in 0.34.0?

**Comment by shinchiro** [comment]
yes for now
