### ISSUE TITLE
command-line version vs. applications based on libmpv

### ISSUE THREAD

**Issue by PLeoncini** [shinchiro/mpv-winbuild-cmake#124]
Hi,
in order to reproject a 360° video into the six faces of a cubemap for a CAVE projection I started modifying the main in https://github.com/mpv-player/mpv-examples/tree/master/libmpv/sdl, and managed to get a quad drawn with the video texture mapped on leveraging the render-in-a-framebuffer facility of the excellent mpv - the perfect basis for my project, and it works flawlessly (my dev setup is Windows platform, Visual Studio 19, OpenGL, c). Yet I have some questions:
1. the Windows perf graph - GPU section - shows there's no actual hw video decode load. How to enable hw-based decoding in an app? I guess it's based on property setting, yet I'd appreciate a guide on this;
2.  my app won't be able to show some of the videos the command-line full version of mpv does, and it's not a matter of file format (mp4, mkv, webm or such). Is it normal? What should I add to the example code to support all video formats of the command-line version?
3.  I saw that a GLSL shader (e.g. un360) could be set in the mpv runtime env, which does a similar job yet with a fixed point of view. My case is more complex since I have to draw six viewports (or separate windows) each with a un360'ed cubemap face. To your expert opinion, would it be possible to do that kind of thing by only configuring the command-line runtime?

Thanks a lot in advance, and compliments for the excellent software.

**Comment by avih** [comment]
As far as I can tell, these are all mpv questions, and not related to a specific build process (which this repository is). So you should ask them at https://github.com/mpv-player/mpv

However, before you do that, you should read or at lleast skim once the mpv and libmpv documentation https://mpv.io/manual/master/ , and then read the whole of https://github.com/mpv-player/mpv/blob/master/libmpv/client.h and possibly other headers of this directory.

Then, if you have questions left or issues to report, then the mpv repo is the place for them - unless they're related to the specific build process which _this_ repository provides.

**Comment by shinchiro** [comment]
Yeah, right. You should open new issue on main repo: https://github.com/mpv-player/mpv
