### ISSUE TITLE
Trying to play any video

### ISSUE THREAD

**Issue by tmcog** [shinchiro/mpv-winbuild-cmake#125]
Every time i attempt to open any video with it, it shows the URL in the bottom left of the program like its going to load it however it closes itself immediately after. Any reasons or fixes i can try?

**Comment by hooke007** [comment]
It seems you always open URL, have you installed `youtube-dl` ?

**Comment by tmcog** [comment]
I would try that but am not very used to navigating or using python, if theirs a video link/tutorial somewhere i'd appreciate it.

**Comment by hooke007** [comment]
No, you think too much about it. Just add the folder which contains `youtube-dl.exe` to variable PATH (or put it with `mpv.exe`)
