### ISSUE TITLE
Where is the location of the custom fontconfig

### ISSUE THREAD

**Issue by akiirui** [shinchiro/mpv-winbuild-cmake#126]
OS: Windows 10

I have edit `mpv/fonts.conf` to customize fontconfig before, but this file always replace when update.

But now, this file have comment:

```
DO NOT EDIT THIS FILE.
IT WILL BE REPLACED WHEN FONTCONFIG IS UPDATED.
LOCAL CHANGES BELONG IN 'local.conf'.
```

So, Where to put the `local.conf`?

Thanks.

**Comment by shinchiro** [comment]
Not sure about that. Maybe you can try put the `local.conf` alongside with `fonts.conf` or in `%LOCALAPPDATA%/fontconfig`. See whether it works or not

**Comment by akiirui** [comment]
Thanks. But it not works.

Maybe I can set fonts.conf to read-only.
