### ISSUE TITLE
DEPENDEE force-update of crossc prevents -DENABLE_VCS_UPDATES=false

### ISSUE THREAD

**Issue by matthew-dews** [shinchiro/mpv-winbuild-cmake#13]
Environment: Ubuntu 18.10

Steps to reproduce:
- `mkdir build64`
- `cd build64`
- `cmake -DTARGET_ARCH=x86_64-w64-mingw32 -DENABLE_VCS_UPDATES=false -G Ninja ..`
- `ninja gcc`
- `ninja mpv`

These steps are the same as what is in the readme, except for the addition of -DENABLE_VCS_UPDATES=false 

Result:
`ninja: error: 'packages/crossc-prefix/src/crossc-stamp/cros-DENABLE_VCS_UPDATES=false sc-force-update', needed by 'packages/crossc-prefix/src/crossc-stamp/crossc-update-submodule', missing and no known rule to make it`

If i undo the change made in 321720bdc9c8baa83799474152b2963bc7a067aa then `ninja mpv ` completes without any errors but I don't know how safe this change is or if it will always work.

**Comment by shinchiro** [comment]
As the commit message stated, its to prevent 2 git process run simultaneously. Unfortunately, I cannot do anything better that this
