### ISSUE TITLE
Suggestion: Clamp Vulkan-Headers/Vulkan-Loader to tags

### ISSUE THREAD

**Issue by NotTsunami** [shinchiro/mpv-winbuild-cmake#130]
Hey, quick suggestion for the Vulkan repos. Instead of having a broken build in between when master branch is updated and when our patches are updated, I think it would be better to clamp each of the repos to the release tags, eg v1.2.179. That way the tag and patch can be updated at the same time without having people file issues for a broken build.

**Comment by shinchiro** [comment]
Not really feasible solution since that mean I need to track which package is outdated in future. Also, it just happen that the patch broken frequently in these weeks and probably not in future

**Comment by NotTsunami** [comment]
Sure, thanks for the response
