### ISSUE TITLE
"cannot index into a null array"

### ISSUE THREAD

**Issue by the-hotmann** [shinchiro/mpv-winbuild-cmake#135]
Since the last build I alwas encounter this problem when running the "updater.bat"

I rightclick and "run as administrator". Then after the RSS part the error "cannot index into a null array" pops up which just lets me quit the script.

Any toughts?

**Comment by wladitavar** [comment]
There is a bug on the updater, when it creates the settings xml file.

The value of <channel> element on the xml file may be empty. Change it to weekly or daily according to your needs.

I had the same problem and now it's working after I set the channel value to daily

Here follows my settings file

<settings>
  <channel>daily</channel>
  <autodelete>unset</autodelete>
</settings>

**Comment by cvzi** [comment]
My settings.xml looks like this, what do I need to change to avoid the error?
```xml
<settings>
  <channel>weekly</channel>
  <arch>x86_64</arch>
  <autodelete>true</autodelete>
  <getffmpeg>true</getffmpeg>
</settings>
```

**Comment by stonehellway** [comment]
@cvzi I had the same issue and changed the value for getffmpeg to false. Now it's working.

**Comment by cvzi** [comment]
@stonehellway Thanks, that works for me as well

**Comment by oakkitten** [comment]
Ran into the same error. Not sure what the exact problem was, but downloading a recent build and extracting it to a new directory, without overwriting the old files, helped.

**Comment by AZ-1282** [comment]
it said fetching RSS feed before the ''[Cannot index into a null array]''
