### ISSUE TITLE
Build with GCC V11

### ISSUE THREAD

**Issue by CharlesMengCA** [shinchiro/mpv-winbuild-cmake#136]
Just FYI.

I tried to built mpv with gcc v11(11-20210717), mingw-w64 V9.0 and binutils V2.36.1. 

Only OpenAL couldn't be built. 

After disabled OpenAL, I can build mpv with your script under above versions.

The JavaScript problem reported by avih is also gone.

mpv --idle --force-window --no-load-scripts --script=no-such-file.js

[no_such_file] Error: cannot open file: 'no-such-file.js'
[no_such_file]  at run_script (native)
[no_such_file] Could not load javascript no-such-file.js

**Comment by shinchiro** [comment]
Thanks for the info. I'll test it on weekend

**Comment by shinchiro** [comment]
Building with gcc 11  toolchain is in `gcc11` branch for now

**Comment by hooke007** [comment]
It was often stopped by `OpenAL` part. Strange...
(Manjaro 21)

Anyway, it is broken in windows, disable it would have no effect.
