### ISSUE TITLE
Get stuck on "Performing build step for 'binutils'" level

### ISSUE THREAD

**Issue by mohammadhoseinGhezelsofla** [shinchiro/mpv-winbuild-cmake#138]
When I execute the  written commands, when I get to the ninja gcc command, the steps go to the Performing build step for 'binutils', but after that nothing happens, the CPU percentage goes down.
OS: Windows 10 21H1 (x64) build 19043.1110.

**Comment by shinchiro** [comment]
My guess is some required program is not installed yet. Check the log in `*-stamp` folder

**Comment by hooke007** [comment]
![Snipaste_2021-08-11_16-55-00](https://user-images.githubusercontent.com/41094733/129000431-b3753828-7f3b-4305-87dc-20c449b87c17.jpg)
Arch. same here.
`binutils-build-*.log` is empty, but I got the message in `gendef-build-err.log`
```
/home/hooke007/mpvbuild/exec: line 6: make: command not found
```

**Comment by shinchiro** [comment]
Nothing wrong on my arch..make sure to update latest autoconf & automake

**Comment by hooke007** [comment]
Hmm...no help about this, I have to go back to ubuntu to build mpv.
