### ISSUE TITLE
Problem with building some libraries: internal compiler error, Segmentation fault

### ISSUE THREAD

**Issue by mohammadhoseinGhezelsofla** [shinchiro/mpv-winbuild-cmake#139]
After running the ninja mpv command, I encounter the following error in several libraries, including libressl and spirv-cross:
Building C object crypto/CMakeFiles/crypto.dir/sha/sha1dgst.c.obj
FAILED: crypto/CMakeFiles/crypto.dir/sha/sha1dgst.c.obj
/home/mohammadhosein/mpv-winbuild-cmake/build64/install/bin/i686-w64-mingw32-gcc.exe -DCPPFLAGS -DHAVE_ASPRINTF -DHAVE_CLOCK_GETTIME -DHAVE_STRCASECMP -DHAVE_STRNLEN -DLIBRESSL_INTERNAL -DNO_CRYPT -DNO_SYSLOG -DOPENSSLDIR=\"C:/Windows/libressl/ssl\" -DOPENSSL_NO_ASM -DOPENSSL_NO_HW_PADLOCK -DSIZEOF_TIME_T=4 -DSMALL_TIME_T -DWIN32_LEAN_AND_MEAN -D_CRT_DEPRECATED_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -D_GNU_SOURCE -D_POSIX -D_POSIX_SOURCE -D_POSIX_THREAD_SAFE_FUNCTIONS -D_REENTRANT -D_WIN32_WINNT=0x0600 -D__BEGIN_HIDDEN_DECLS="" -D__END_HIDDEN_DECLS="" -D__USE_MINGW_ANSI_STDIO -Drestrict -I/home/mohammadhosein/mpv-winbuild-cmake/build64/packages/libressl-prefix/src/libressl/crypto/. -I/home/mohammadhosein/mpv-winbuild-cmake/build64/packages/libressl-prefix/src/libressl/crypto/asn1 -I/home/mohammadhosein/mpv-winbuild-cmake/build64/packages/libressl-prefix/src/libressl/crypto/bn -I/home/mohammadhosein/mpv-winbuild-cmake/build64/packages/libressl-prefix/src/libressl/crypto/dsa -I/home/mohammadhosein/mpv-winbuild-cmake/build64/packages/libressl-prefix/src/libressl/crypto/ec -I/home/mohammadhosein/mpv-winbuild-cmake/build64/packages/libressl-prefix/src/libressl/crypto/ecdh -I/home/mohammadhosein/mpv-winbuild-cmake/build64/packages/libressl-prefix/src/libressl/crypto/ecdsa -I/home/mohammadhosein/mpv-winbuild-cmake/build64/packages/libressl-prefix/src/libressl/crypto/evp -I/home/mohammadhosein/mpv-winbuild-cmake/build64/packages/libressl-prefix/src/libressl/crypto/modes -I/home/mohammadhosein/mpv-winbuild-cmake/build64/packages/libressl-prefix/src/libressl/crypto/../include/compat -I/home/mohammadhosein/mpv-winbuild-cmake/build64/packages/libressl-prefix/src/libressl/crypto/../include -O2 -Wall -O3 -DNDEBUG   -Wno-pointer-sign -MD -MT crypto/CMakeFiles/crypto.dir/sha/sha1dgst.c.obj -MF crypto/CMakeFiles/crypto.dir/sha/sha1dgst.c.obj.d -o crypto/CMakeFiles/crypto.dir/sha/sha1dgst.c.obj -c /home/mohammadhosein/mpv-winbuild-cmake/build64/packages/libressl-prefix/src/libressl/crypto/sha/sha1dgst.c
i686-w64-mingw32-gcc: internal compiler error: Segmentation fault signal terminated program cc1
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
ninja: build stopped: subcommand failed.

I rebuilt the toolchain several times, even once completely deleting msys2 and reinstalling it, but the problem was not resolved.
Build environment: msys2, On windows 10 64-bit.

**Comment by shinchiro** [comment]
msys2 is kinda unsupported although it can be built on it so this problem is expected. Better compile it on WSL
