### ISSUE TITLE
libmfx support? 

### ISSUE THREAD

**Issue by aluo-x** [shinchiro/mpv-winbuild-cmake#14]
[myfreeer ](https://github.com/myfreeer/mpv-build-lite)has created [patches ](https://github.com/myfreeer/mpv-build-lite/search?q=libmfx&type=Commits)that add libmfx (intel quicksync) support to the build, would it be possible to have those also ported over?

**Comment by shinchiro** [comment]
what it's used for?

**Comment by aluo-x** [comment]
To enable Intel quicksync decoding of video
