### ISSUE TITLE
mpv doesn't read setting when include JP letter folder

### ISSUE THREAD

**Issue by ha2ne2** [shinchiro/mpv-winbuild-cmake#14]
thanks for build.
don't read setting when include JP letter folder

C:/ほげほげ/mpv/mpv.exe when
C:/ほげほげ/mpv/lua-settings/osc.conf <- don't read it

C:/hogehoge/mpv/mpv.exe when
C:/hogehoge/mpv/lua-settings/osc.conf <- read it

**Comment by shinchiro** [comment]
It worked for me when path contain hiragana/katakana characters. Tested with mpv.conf

Better ask on mpv's repo: https://github.com/mpv-player/mpv/issues/new
