### ISSUE TITLE
crashes with vo=direct3d

### ISSUE THREAD

**Issue by DangerPie** [shinchiro/mpv-winbuild-cmake#141]
Windows 7 SP1
mpv-x86_64-20210815-git-0c9e1e3.7z
mpv-x86_64-20200524-git-685bd6a.7z
crashes at any action (rewind, end of video...) when vo=direct3d

switching to full screen shows additional error:
```---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Assertion failed!

Program: V:\temp\mpv.exe
File: ../ta/ta.c
Line: 293

Expression: h->canary == CANARY

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)
```

mpv-x86_64-20200126-git-ae0520c.7z works

>mpv --no-config --log-file=output.txt --vo=direct3d test_crash.mp4 

[output.txt](https://github.com/shinchiro/mpv-winbuild-cmake/files/6988140/output.txt)

https://user-images.githubusercontent.com/3441063/129479347-62ca985a-0a34-45a5-99dd-295a9f0776fd.mp4

**Comment by shinchiro** [comment]
Report the bug on mpv's issue tracker:
https://github.com/mpv-player/mpv/issues
