### ISSUE TITLE
"-o file.jpg" stopped working

### ISSUE THREAD

**Issue by DangerPie** [shinchiro/mpv-winbuild-cmake#142]
https://github.com/mpv-player/mpv/issues/9053

https://i.imgur.com/A7M5U3z.mp4

mpv-x86_64-20210815-git-0c9e1e3.7z
mpv-x86_64-20210725-git-e2109b6.7z mpv 0.33.0-247-ge2109b606b
mpv-x86_64-20210627-git-a1c6762.7z mpv 0.33.0-204-ga1c6762156

```
>mpv --no-audio -frames 1 test.mp4 -o screen.jpg
 (+) Video --vid=1 (*) (h264 480x360 25.000fps)
VO: [lavc] 480x360 yuv420p
[vo/lavc] Opening encoder: MJPEG (Motion JPEG) [mjpeg]
[ffmpeg] mjpeg: Non full-range YUV is non-standard, set strict_std_compliance to at most unofficial to use it.
[vo/lavc] Could not initialize encoder.
Could not initialize video chain.
Video: no video

[encode] no data written to target file
Exiting... (Interrupted by error)
```

Older versions works:

mpv-x86_64-20210117-git-a3e440c.7z mpv 0.33.0-62-ga3e440c611

```
>mpv --no-audio -frames 1 test.mp4 -o screen.jpg
 (+) Video --vid=1 (*) (h264 480x360 25.000fps)
[autoconvert] Converting yuv420p -> yuvj422p
VO: [lavc] 480x360 yuvj422p
[vo/lavc] Opening encoder: MJPEG (Motion JPEG) [mjpeg]
[encode] Opening muxer: image2 sequence [image2]

[encode] video: encoded 35181 bytes
[encode] audio: encoded 0 bytes
[encode] muxing overhead -35203 bytes
Exiting... (End of file)
```

>mpv --no-config --log-file=output.txt -frames 1 -o test.jpg A7M5U3z.mp4 

[output.txt](https://github.com/shinchiro/mpv-winbuild-cmake/files/6988146/output.txt)

**Comment by shinchiro** [comment]
Report the bug on mpv's issue tracker:
https://github.com/mpv-player/mpv/issues

**Comment by DangerPie** [comment]
Already. They sent me here.
