### ISSUE TITLE
Consider renaming updater.bat to something not so generic.

### ISSUE THREAD

**Issue by mrplumber** [shinchiro/mpv-winbuild-cmake#143]
Hi,
I added mpv to %PATH% environment variable, so I could easily launch mpv.exe or update it globally from command line. Please consider renaming updater.bat to something more specific (e.g. mpv-updater.bat) so that command name is more informative of the action it is supposed to do. Thanks.

**Comment by NotTsunami** [comment]
I don't think this is necessary. It is standard convention to provide generic names. A lot of programs are bundled with an `uninstall.bat` or `uninstall.exe`. It goes without saying what each of these mean.

**Comment by shinchiro** [comment]
Well, personally I'll stick to the original filename
