### ISSUE TITLE
Problem in building mpv in wsl: Consuming memory on building gcc_base

### ISSUE THREAD

**Issue by mohammadhoseinGhezelsofla** [shinchiro/mpv-winbuild-cmake#146]
After entering the ninja gcc command, when it reaches step 39 of 67 and wants to build gcc_base, my memory is completely full and it is not finished.
My laptop has 8 gb ram and 8 core cpu.

**Comment by rorgoroth** [comment]
More cores, more RAM used.

Several solutions:
* Run ```ninja -j 1 gcc```  (this may still fail)
* Limit cores in CMakeList.txt: ```set(MAKEJOBS 4)```

Alternatively you can change wsl defaults, create .wslconfig in your Windows home folder containing:
```
[wsl2]
memory=5GB
processors=4
```

Run ```wsl --shutdown``` for changes to take effect.

**Comment by mohammadhoseinGhezelsofla** [comment]
limiting memory in .wslconfig file has solved the problem. Thank you @rorgoroth
