### ISSUE TITLE
[Request] Updater auto-close feature

### ISSUE THREAD

**Issue by Obegg** [shinchiro/mpv-winbuild-cmake#148]
Since the updater doesn't have an auto-update feature,
I decided to add updater.bat to startup on my Windows 10 PC so that every time my PC boots up - updater.bat will lunch (as Admin),
But that creates another problem - Every time it opens I have to manually close the updater window,
To counter that issue I edit the updater.bat and remove the last line `@pause`
But this gets more complicated and annoying when I have to do this each time it does find an update,
Since the update does update ALL the files, including "updater.bat", I have to keep deleting this last line.

My request is to permanently delete this last line `@pause`
If this is not acceptable, then use a countdown that will auto-close the updater in X seconds.

This is "updater.bat":
```
@echo OFF
:: This batch file exists to run updater.ps1 without hassle
pushd %~dp0
if exist "%~dp0\installer\updater.ps1" (
    set updater_script="%~dp0\installer\updater.ps1"
) else (
    set updater_script="%~dp0\updater.ps1"
)
powershell -noprofile -nologo -executionpolicy bypass -File %updater_script%

:: After update, updater.ps1 should not in same folder as mpv.exe
if exist "%~dp0\installer\updater.ps1" if exist "%~dp0\updater.ps1" (
    del "%~dp0\updater.ps1"
)
```

**Comment by shinchiro** [comment]
Fixed by replacing with `timeout` command so it will automatically close after 5 seconds
