### ISSUE TITLE
mpv updater return error code when updating mpv 

### ISSUE THREAD

**Issue by oct9** [shinchiro/mpv-winbuild-cmake#15]
"end of central directory record could not be found" - this error code is what i get when updating using the built-in updater in your mpv build. if there is no new version of mpv, then the youtube-dl update is successful with no error code present. i'm currently using your 64-bit build from the sourceforge website. thanks for your excellent work on this project!

**Comment by shinchiro** [comment]
Seem like the archive corrupted when downloading, resulting the error. Maybe antivirus or firewall interrupt with download process
