### ISSUE TITLE
[Request] Updater Auto Delete 7z File Upon Completion

### ISSUE THREAD

**Issue by Obegg** [shinchiro/mpv-winbuild-cmake#151]
Current Behavior:
Updater downloads and extracts the new MPV build as a 7z file and doesn't delete it upon completion, resulting in remaining junk files.

Requested Behavior:
Updater downloads and extracts the new MPV build as a 7z file and upon completion will delete the 7z file.

**Comment by shinchiro** [comment]
I made it to not automatically delete since weekly build can be buggy sometimes. People can extract back older build when problem happen
