### ISSUE TITLE
stable v0.33.0 and stable v0.34.0 .ass subtitle style are different? v0.34.0 showing subtitle style wrong.

### ISSUE THREAD

**Issue by erickyun** [shinchiro/mpv-winbuild-cmake#160]
stable v0.33.0 subtitle:
![mpv-shot0001](https://user-images.githubusercontent.com/71968711/141349215-33335a6c-4a42-49de-ad21-58c15180dd59.jpg)

stable v0.34.0 subtitle:
![mpv-shot0002](https://user-images.githubusercontent.com/71968711/141349697-6298d581-f147-4ad6-b2ea-310d1d24e2ba.jpg)

v0.33.0 subtitle style is right but v0.34.0 subtitle style is wrong it looks like the mpv android.

**Comment by hooke007** [comment]
I think u post the wrong issue in the wrong thread.

Here just build the exec, subs's issue (upstream-libass) should be reported there. https://github.com/libass/libass/issues

**Comment by erickyun** [comment]
> I think u post the wrong issue in the wrong thread.
> 
> Here just build the exec, subs's issue (upstream-libass) should be reported there. https://github.com/libass/libass/issues

Okay I understand my bad sorry. I will open there an issue then.
