### ISSUE TITLE
Option to remove recent files eg mp3s from history

### ISSUE THREAD

**Issue by MrTazocin** [shinchiro/mpv-winbuild-cmake#161]
All recent files (history) will display if right click mpv on the win10 start menu or pinned mpv on start/taskbar.
Any option to hide them rather than delete all the recent histories one-by-one?

**Comment by hooke007** [comment]
It should be microsoft's job. The system recorded your privacy, not mpv.

**Comment by shinchiro** [comment]
Yeah
