### ISSUE TITLE
Typo in sourceforge's README.rst

### ISSUE THREAD

**Issue by zhongfly** [shinchiro/mpv-winbuild-cmake#162]
[sourceforge's README.rst](https://sourceforge.net/projects/mpv-player-windows/files/) :

> You can read how-to setup here: https://github.com/shinchiro/mpv-winbuild-cmake/wiki/Setup-vapoursynth-in-mpv

the link is broken,should be `https://github.com/shinchiro/mpv-winbuild-cmake/wiki/Setup-vapoursynth-for-mpv` ('**in**' replaced to '**for**')

**Comment by shinchiro** [comment]
Fixed
