### ISSUE TITLE
Feature request: add clang version of libmpv

### ISSUE THREAD

**Issue by wangwenx190** [shinchiro/mpv-winbuild-cmake#17]
May I be able to know is there any plan to provide a new version of libmpv which uses Clang and LLD as it's compiler and linker?

**Comment by wangwenx190** [comment]
It's quite easy to use Clang to compile libmpv on Linux but I'm sorry that I don't know how to do it on Windows either, what a shame.

I think we should leave this issue open until someone find the satisfying solution.

**Comment by wangwenx190** [comment]
Clang and it's tools can be installed directly in MSYS2 without compiling. I just found an article which may be helpful: http://blog.johannesmp.com/2015/09/01/installing-clang-on-windows-pt3/ . According to this article, we can install clang through `pacman -S mingw-w64-x86_64-clang mingw-w64-i686-clang`.

Override the variables "CC" and "CXX" to use Clang as libmpv's compiler.
For example:
export CC=clang
export CXX=clang++

**Comment by wangwenx190** [comment]
Of course I'll build it myself if you are not able to provide one, but I'm not familiar with bash scripts, maybe you should change a little bit to make it workable with clang.

**Comment by wangwenx190** [comment]
Most of the compilation parameters of clang and gcc are compatible, you don't need to modify them.

**Comment by shinchiro** [comment]
Closing this as I didn't think I've motivation to get clang works
