### ISSUE TITLE
[Question] Difference?

### ISSUE THREAD

**Issue by Obegg** [shinchiro/mpv-winbuild-cmake#171]
I use mpv on WIndows,
I use shinchiro builds - https://sourceforge.net/projects/mpv-player-windows/files/64bit/
But it updates every 1-3 weeks.
On the other hand, zhongfly builds - https://github.com/zhongfly/mpv-winbuild
Are updated daily, which is great.

So my question here is what is the difference?
(I have 0 knowledge with "packages" and stuff)

And if it's okay for me to ask this - is it possible that shinchiro builds will be updated more frequently?

**Comment by zhongfly** [comment]
I'm the owner of https://github.com/zhongfly/mpv-winbuild
The repo use this toolchain to build mpv as same as shinchiro builds,so it contains the same packages and same build config as shinchiro's builds.
So there is no difference if we build mpv with completely same packages' version.
But as you can see packages update frequently and shinchiro update his builds every few weeks,so I decided to using shinchiro's toolchains to build mpv and release every day.

> Fun fact: my repo actually build mpv ervery hours if mpv have new commit,you can download them from https://github.com/zhongfly/mpv-winbuild/action.

**Comment by Obegg** [comment]
> I'm the owner of https://github.com/zhongfly/mpv-winbuild The repo use this toolchain to build mpv as same as shinchiro builds,so it contains the same packages and same build config as shinchiro's builds. So there is no difference if we build mpv with completely same packages' version. But as you can see packages update frequently and shinchiro update his builds every few weeks,so I decided to using shinchiro's toolchains to build mpv and release every day.
> 
> > Fun fact: my repo actually build mpv ervery hours if mpv have new commit,you can download them from https://github.com/zhongfly/mpv-winbuild/action.

Does it have the same auto-update feature? (cmd opens up and auto-download and install the new build for you)

**Comment by zhongfly** [comment]
> Does it have the same auto-update feature? (cmd opens up and auto-download and install the new build for you)

No,the auto-update bat in my builds is same as shinchiro's builds so it will download shinchiro's build not my build.
But if anyone want this feature,I will try to modify that bat.

**Comment by Obegg** [comment]
> > Does it have the same auto-update feature? (cmd opens up and auto-download and install the new build for you)
> 
> No,the auto-update bat in my builds is same as shinchiro's builds so it will download shinchiro's build not my build. But if anyone want this feature,I will try to modify that bat.

If the only difference is that you update daily - sure, I'll use it. Can you add auto-update?

**Comment by zhongfly** [comment]
> If the only difference is that you update daily - sure, I'll use it. Can you add auto-update?

I need some time to study how to modify that cmd to fit my repo.Please be patient, it may not be soon.

**Comment by Obegg** [comment]
> > If the only difference is that you update daily - sure, I'll use it. Can you add auto-update?
> 
> I need some time to study how to modify that cmd to fit my repo.Please be patient, it may not be soon.

No problem, also - if the end result is mpv build that updates daily with auto-update feature, why not include it (link) on the official website of mpv.io?

**Comment by zhongfly** [comment]
> No problem, also - if the end result is mpv build that updates daily with auto-update feature, why not include it (link) on the official website of mpv.io?

In fact, I don't know how to build mpv. My repo only uses the toolchain provided by shinchiro, so it is completely based on shinchiro's work and should be regarded as a supplement to shinchiro's builds. My repo may not be suitable to be regarded as a separate download channel like shinchiro's.
On the other hand, my repo uses GitHub Action to build mpv, and it may be difficult to maintain because of GitHub's changes to this function.

**Comment by Obegg** [comment]
> > No problem, also - if the end result is mpv build that updates daily with auto-update feature, why not include it (link) on the official website of mpv.io?
> 
> In fact, I don't know how to build mpv. My repo only uses the toolchain provided by shinchiro, so it is completely based on shinchiro's work and should be regarded as a supplement to shinchiro's builds. My repo may not be suitable to be regarded as a separate download channel like shinchiro's. On the other hand, my repo uses GitHub Action to build mpv, and it may be difficult to maintain because of GitHub's changes to this function.

Right... so here's an idea, a wild one that will "kill 2 birds with 1 stone" - how about you and shinchiro will embed a solution that will update mpv daily?

Daily updates is great, especially since I use ```vo=gpu-next``` (experimental feature) which has many fixes each day (zhongfly builds)
But auto-update is also great, I just add the cmd to startup and mpv updates every time I start the pc (shinchiro builds)
Take those two, combine them, everyone's happy.

I have 0 knowledge (as I already said), I have no idea if it's complicated or not, but the idea sounds doable

Edit:
It's better than to create a different "product" that no one knows of,
If you go to https://mpv.io/installation/ you can see shinchiro build there, it has lots of downloads and it already has auto-update, it only missing daily updates and that's it.
If it's somehow possible to take the idea of zhongfly and combine it with shinchiro that would be awesome.

**Comment by zhongfly** [comment]
> If the only difference is that you update daily - sure, I'll use it. Can you add auto-update?

I have added this feature.
The builds from now on will use modified updater.ps1 which download latest mpv from my releases, you can wait 2022.1.29 build or overwrite your `/installer/updater.ps1` with [this](https://github.com/zhongfly/mpv-packaging/blob/master/mpv-root/installer/updater.ps1).

**Comment by Obegg** [comment]
> > If the only difference is that you update daily - sure, I'll use it. Can you add auto-update?
> 
> I have added this feature. The builds from now on will use modified updater.ps1 which download latest mpv from my releases, you can wait 2022.1.29 build or overwrite your `/installer/updater.ps1` with [this](https://github.com/zhongfly/mpv-packaging/blob/master/mpv-root/installer/updater.ps1).

Awesome! I'll test it now!

**Comment by Obegg** [comment]
> > If the only difference is that you update daily - sure, I'll use it. Can you add auto-update?
> 
> I have added this feature. The builds from now on will use modified updater.ps1 which download latest mpv from my releases, you can wait 2022.1.29 build or overwrite your `/installer/updater.ps1` with [this](https://github.com/zhongfly/mpv-packaging/blob/master/mpv-root/installer/updater.ps1).

Okay, so:
I edited ```/installer/updater.ps1``` with [this](https://github.com/zhongfly/mpv-packaging/blob/master/mpv-root/installer/updater.ps1), and it did download the new build from zhongfly.
But then I wanted to update mpv again (to test if future-proof), this time it downloaded the build from shinchiro.

**Comment by Obegg** [comment]
Logs from shinchiro:
[   0.016][v][cplayer] List of enabled features: asm build-date cplayer cuda-hwaccel cuda-interop d3d-hwaccel d3d11 d3d9-hwaccel debug-build direct3d dos-paths dvdnav egl-angle egl-angle-win32 egl-helpers ffmpeg ffmpeg-aviocontext-bytes-read ffnvcodec gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win32 gpl iconv javascript jpeg lcms2 libarchive libass libavdevice libbluray libm libmpv-shared libplacebo libplacebo-v4 lua luajit mingw noexecstack openal optimize plain-gl posix-or-mingw rubberband sdl2 sdl2-audio sdl2-gamepad sdl2-video shaderc shaderc-static spirv-cross spirv-cross-static static-build stdatomic uchardet vapoursynth vector vulkan wasapi win32-desktop win32-internal-pthreads zimg zlib

Logs from zhongfly:
[   0.020][v][cplayer] List of enabled features: asm build-date cplayer cuda-hwaccel cuda-interop d3d-hwaccel d3d11 d3d9-hwaccel debug-build direct3d dos-paths dvdnav egl-angle egl-angle-win32 egl-helpers ffmpeg ffnvcodec gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win32 gpl iconv javascript jpeg lcms2 libarchive libass libavdevice libbluray libm libmpv-shared libplacebo libplacebo-v4 lua luajit mingw noexecstack openal optimize plain-gl posix-or-mingw rubberband sdl2 sdl2-audio sdl2-gamepad sdl2-video shaderc shaderc-static spirv-cross spirv-cross-static static-build stdatomic uchardet vapoursynth vector vulkan wasapi win32-desktop win32-internal-pthreads zimg zlib

They are different, it's hard to spot

Edit:
shinchiro:
ffmpeg-aviocontext-bytes-read ffnvcodec

zhongfly:
ffnvcodec

**Comment by zhongfly** [comment]
> > > If the only difference is that you update daily - sure, I'll use it. Can you add auto-update?
> > 
> > 
> > I have added this feature. The builds from now on will use modified updater.ps1 which download latest mpv from my releases, you can wait 2022.1.29 build or overwrite your `/installer/updater.ps1` with [this](https://github.com/zhongfly/mpv-packaging/blob/master/mpv-root/installer/updater.ps1).
> 
> Okay, so: I edited `/installer/updater.ps1` with [this](https://github.com/zhongfly/mpv-packaging/blob/master/mpv-root/installer/updater.ps1), and it did download the new build from zhongfly. But then I wanted to update mpv again (to test if future-proof), this time it downloaded the build from shinchiro.

Please wait until the new version of 2022.1.29 appears before running the update script. 
Because the update scripts in all builds at now are old scripts at present, all files will be overwritten with the downloaded build when running the update script, so the script you modified will also be restored to the old script.

**Comment by Obegg** [comment]
> > > > If the only difference is that you update daily - sure, I'll use it. Can you add auto-update?
> > > 
> > > 
> > > I have added this feature. The builds from now on will use modified updater.ps1 which download latest mpv from my releases, you can wait 2022.1.29 build or overwrite your `/installer/updater.ps1` with [this](https://github.com/zhongfly/mpv-packaging/blob/master/mpv-root/installer/updater.ps1).
> > 
> > 
> > Okay, so: I edited `/installer/updater.ps1` with [this](https://github.com/zhongfly/mpv-packaging/blob/master/mpv-root/installer/updater.ps1), and it did download the new build from zhongfly. But then I wanted to update mpv again (to test if future-proof), this time it downloaded the build from shinchiro.
> 
> Please wait until the new version of 2022.1.29 appears before running the update script. Because the update scripts in all builds at now are old scripts at present, all files will be overwritten with the downloaded build when running the update script, so the script you modified will also be restored to the old script.

Uh, right, yes, I understand. I will wait for the new build.

**Comment by zhongfly** [comment]
> Logs from shinchiro: [ 0.016][v][cplayer] List of enabled features: asm build-date cplayer cuda-hwaccel cuda-interop d3d-hwaccel d3d11 d3d9-hwaccel debug-build direct3d dos-paths dvdnav egl-angle egl-angle-win32 egl-helpers ffmpeg ffmpeg-aviocontext-bytes-read ffnvcodec gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win32 gpl iconv javascript jpeg lcms2 libarchive libass libavdevice libbluray libm libmpv-shared libplacebo libplacebo-v4 lua luajit mingw noexecstack openal optimize plain-gl posix-or-mingw rubberband sdl2 sdl2-audio sdl2-gamepad sdl2-video shaderc shaderc-static spirv-cross spirv-cross-static static-build stdatomic uchardet vapoursynth vector vulkan wasapi win32-desktop win32-internal-pthreads zimg zlib
> 
> Logs from zhongfly: [ 0.020][v][cplayer] List of enabled features: asm build-date cplayer cuda-hwaccel cuda-interop d3d-hwaccel d3d11 d3d9-hwaccel debug-build direct3d dos-paths dvdnav egl-angle egl-angle-win32 egl-helpers ffmpeg ffnvcodec gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win32 gpl iconv javascript jpeg lcms2 libarchive libass libavdevice libbluray libm libmpv-shared libplacebo libplacebo-v4 lua luajit mingw noexecstack openal optimize plain-gl posix-or-mingw rubberband sdl2 sdl2-audio sdl2-gamepad sdl2-video shaderc shaderc-static spirv-cross spirv-cross-static static-build stdatomic uchardet vapoursynth vector vulkan wasapi win32-desktop win32-internal-pthreads zimg zlib
> 
> They are different, it's hard to spot
> 
> Edit: shinchiro: ffmpeg-aviocontext-bytes-read ffnvcodec
> 
> zhongfly: ffnvcodec

Because latest mpv delete it,see https://github.com/mpv-player/mpv/commit/8087e3371f8ffbdc8ddcbc0445392b0480ef02a4#diff-b79856260b3cc9b3e958c83a55bae1e46e31d232125b925c581022786a7bc042 .
As I said before, I just used his toolchain and didn't modify any configuration, you shouldn't worry about it, all the differences are only from updates of projects like mpv.

**Comment by Obegg** [comment]
> 
> Because latest mpv delete it,see [mpv-player/mpv@8087e33](https://github.com/mpv-player/mpv/commit/8087e3371f8ffbdc8ddcbc0445392b0480ef02a4)

Thank you for the explanation, I checked the logs just to make sure that everything is fine, you just confirmed it for me.

I wanted to ask (but there's no way to open an issue there), what is `mpv-dev-x86_64`?
I use this `mpv-x86_64-20220128-git-19dd61f.7z`, but I have no idea what the other one is.
They are both from the master branch, so what's the difference between those?

**Comment by zhongfly** [comment]
> > Because latest mpv delete it,see [mpv-player/mpv@8087e33](https://github.com/mpv-player/mpv/commit/8087e3371f8ffbdc8ddcbc0445392b0480ef02a4)
> 
> Thank you for the explanation, I checked the logs just to make sure that everything is fine, you just confirmed it for me.
> 
> I wanted to ask (but there's no way to open an issue there), what is `mpv-dev-x86_64`? I use this `mpv-x86_64-20220128-git-19dd61f.7z`, but I have no idea what the other one is. They are both from the master branch, so what's the difference between those?

`mpv-dev-x86_64-xxxx.7z` is 64-bit libmpv version, including the `mpv-2.dll` file.
Some media players based on libmpv use mpv-2.dll.You can upgrade their libmpv version by overwriting mpv-2.dll.

**Comment by zhongfly** [comment]
> there's no way to open an issue there

you can go to https://github.com/zhongfly/mpv-winbuild/discussions
