### ISSUE TITLE
Daily updates

### ISSUE THREAD

**Issue by Obegg** [shinchiro/mpv-winbuild-cmake#174]
I use mpv every day, and there are experimental features that I use, such as ```vo=gpu-next```.
Those experimental features are buggy but each day they are slowly getting fixed.
The "problem" is the release cycle, shinchiro releases updates once a week to 3 weeks.
I guess the reason for that is it has been manually built, and shinchiro is busy so he doesn't have time.
But, it has been proven that daily releases are possible, automatically, using GitHub actions (By [zhongfly](https://github.com/zhongfly/mpv-winbuild))
So why not take that knowledge and experience with automating the releases by collaborating with zhongfly?
https://github.com/zhongfly/mpv-winbuild/discussions/13#discussioncomment-2074703

**Comment by shinchiro** [comment]
PR to add ci is welcome. As i'm getting busy and lazy, it can save my time

**Comment by zhongfly** [comment]
> PR to add ci is welcome. As i'm getting busy and lazy, it can save my time

@shinchiro 
I need to know some information before opening a PR.

1. Release
You've been released updates on sourceforge, I'm not familiar with it and can't test it, so need your help to complete this part
1. Release cycle
every day?
1. build environment
Github action can provide ubuntu 20.04 system, if you use docker, there are more systems to choose from. In my experience, it's easier to use Archlinux, what's your suggestion?
1. cache
https://help.github.com/github/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows
 We could use the cache to speed up every build, but we need to find a way to completely rebuild everything and update the cache when the toolchain is updated.
Of course, we could also not use the cache, build time would be longer, but it would make the whole thing simpler.
What do you think?

**Comment by shinchiro** [comment]
If there's no limit, every day release is good. I would like to retain 7 release on github repo for daily release and push one release  on sf repo for weekly release. Use archlinux docker. I would prefer the compile takes less time so using cache is a must. It also must compile 32bit and 64bit.

**Comment by zhongfly** [comment]
> retain 7 release on github repo for daily release

Keep only the last 7 builds？

Another problem:
If we add multiple tags to the same commit,there is a problem with the ordering of releases associated with these tags on github.
see https://github.community/t/the-latest-release-show-in-release-tab-isnt-real-latest/218086

**Comment by shinchiro** [comment]
If there's ordering issue, it's not big deal as I can grab the release's rss feed and sort it manually.

> Keep only the last 7 builds？

To keep rss feed in small size

**Comment by avih** [comment]
> To keep rss feed in small size

Personally I don't think this should be a factor. IMO the longer daily builds are retained - the better.

**Comment by hatharry** [comment]
I built this workflow for my needs
https://github.com/hatharry/mpv-winbuild-cmake/tree/master/.github/workflows
It can easy be modified for a daily schedule using cron syntax
https://www.jeffgeerling.com/blog/2020/running-github-actions-workflow-on-schedule-and-other-events

**Comment by Obegg** [comment]
Should probably also update the ```updater.ps1``` file: https://github.com/shinchiro/mpv-packaging/blob/master/mpv-root/installer/updater.ps1

**Comment by Obegg** [comment]
I just noticed that there are no releases yet, I checked on [GitHub actions](https://github.com/shinchiro/mpv-winbuild-cmake/actions) and all I see is error logs, so I guess it's not finished yet?

**Comment by shinchiro** [comment]
Yeah, it still not finished
