### ISSUE TITLE
The debug symbol will fail to build on the second build

### ISSUE THREAD

**Issue by zhongfly** [shinchiro/mpv-winbuild-cmake#175]
Reproduce Steps:
1. Build mpv normally, debug symbol file size is normal
2. Do not update the source code of mpv, but you can update other,then build mpv again(`ninja mpv`)
3. The size of the debug symbol file is too small, and it must be unusable, see https://github.com/zhongfly/mpv-test/actions/runs/1773368802

run `ninja mpv-removebuild` before build can fix it.

**Comment by shinchiro** [comment]
Cannot reproduce this issue

**Comment by zhongfly** [comment]
@shinchiro  Maybe off topic,I find a strange thing: after I delete `avisynth-headers-prefix`folder,if I run `ninja mpv-removebuild`, ninja will try to build ffmpeg first 
![image](https://user-images.githubusercontent.com/11155705/153988860-2070ee6d-0545-4572-b130-648cb08fa804.png)

**Comment by shinchiro** [comment]
Its normal. FFmpeg depend on avisynth packages. If the packages gone, ffmpeg will attempt to rebuild back since mpv depend on ffmpeg

**Comment by zhongfly** [comment]
> Its normal. FFmpeg depend on avisynth packages. If the packages gone, ffmpeg will attempt to rebuild back since mpv depend on ffmpeg

But you said "ninja **package-removebuild** -> Remove 'build' directory of a package."
From what I understand, this command is only used to delete some files, it does not involve building.
Why deleting mpv's build directory need building ffmpeg first…
