### ISSUE TITLE
Always lose focus in fullscreen mode

### ISSUE THREAD

**Issue by NeilTohno** [shinchiro/mpv-winbuild-cmake#180]
Recently, I open video files with mpv player fullscreen mode, after sometime, the program (mpv player) lose focus, I can't use shortcut keys until I click it with mouse.

I found no error in mpv's log file.
Thanks.

### Important Information

- mpv version
[mpv-x86_64-20220206-git-0197729.7z]
- Windows Version
win10 21H2 64bit
2950x cpu , vega 64

**Comment by hooke007** [comment]
I think it has nothing with building, unless you can prove that which commit/version in this repo leads to your issue...

**Comment by shinchiro** [comment]
Please report it on mpv github's repo
