### ISSUE TITLE
How to ignore force-update failures?

### ISSUE THREAD

**Issue by zhongfly** [shinchiro/mpv-winbuild-cmake#183]
Sometimes some packages will be inaccessible, which will cause the force-update step to fail(for example, the source code repository for [lame](https://salsa.debian.org/multimedia-team/lame) is now inaccessible), making the building unable to proceed.
Is there a way to ignore such force-update failures and continue building mpv?

**Comment by shinchiro** [comment]
The build cannot ignore it
