### ISSUE TITLE
Build with jack support?

### ISSUE THREAD

**Issue by ale-rinaldi** [shinchiro/mpv-winbuild-cmake#184]
Hello @shinchiro ,

first of all, thank you for your great work! Building mpv for Windows is quite annoying to be honest, and I love to have your builds ready to use and constantly updated.

For some odd reasons, I'm experimenting with using Jack on Windows: I need the output from MPV to be routed through other applications before reaching the soundcard, and I need to do this with a predictable timing. Using a virtual soundcard is not a viable solution since they have a made-up clock that is slightly different than the soundcard one, and I couldn't find any virtual soundcard that just passes audio as it is consumed. Seems strange, but the only solution I found that seems to be working is using Jack.

I managed to build Windows MPV following the official instuctions at https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md and installing $MINGW_PACKAGE_PREFIX-jack2 into MinGW, but it's not statically compiled and depends on lots of DLLs inside the MinGW folder.

I'd love to have Jack support inside your builds. Would you evaluate it?

Thank you!

**Comment by shinchiro** [comment]
Unfortunately, jack library depends on many libraries to build successfully like:

```
libsndfile
libsamplerate
libtre-git
libsystre
portaudio
libdb
```

As such, I'm hesitant to add jack support in mpv

**Comment by ale-rinaldi** [comment]
Thank you @shinchiro , I see your point.

I will try reproducing your builds following your README, instead of the official instructions: I aim at having a portable build like yours with no DLL dependencies. If I succeed, I'll fork the project and add Jack support for my specific use case.

Thanks!
