### ISSUE TITLE
Help: mpv with dependent dll's being shared

### ISSUE THREAD

**Issue by ksmuthucv** [shinchiro/mpv-winbuild-cmake#186]
Hello Team,
It is possible to generate the mpv build with all the dependent dll's being shared i.e. instead of mpv.exe embedding all the dependent dll's such ibavutil, libavcodec, libavformat, etc if all them can be placed in the build output folder with mpv.exe? This will help in leveraging functionalities from ffpmpeg as well, without maintaining two copies of ffmpeg. Please help/guide.

Thanks,
Muthu

**Comment by hooke007** [comment]
https://github.com/shinchiro/mpv-winbuild-cmake/issues/123

**Comment by shinchiro** [comment]
This repo is only build shared mpv's dll & static exe. You might need to use msys2 after all
