### ISSUE TITLE
updater.bat is broken

### ISSUE THREAD

**Issue by BrianG61UK** [shinchiro/mpv-winbuild-cmake#188]
I used to be able to update MPV on my Windows PCs by running your updater.bat file with elevated privilages.
Now I just get a little string of # characters slowly appearing followed by the red message:
Cannot bind argument to parameter 'Path' because it is an empty string.

**Comment by Obegg** [comment]
https://github.com/mpv-player/mpv/issues/10006#issuecomment-1075259243
So I guess you didn't choose between daily updates or weekly?

**Comment by n-buna404** [comment]
The thing is this error will occur if u press 1 or let # go by itself which is by default weekly. Maybe the path to weekly/sourceforge is empty? Daily github build works fine so maybe can choose daily build from github and update it whenever u like.
edit: the issue belong to this repo
https://github.com/shinchiro/mpv-packaging

**Comment by Pentaphon** [comment]
> [mpv-player/mpv#10006 (comment)](https://github.com/mpv-player/mpv/issues/10006#issuecomment-1075259243) So I guess you didn't choose between daily updates or weekly?

How do I go back to weekly if I picked daily by mistake?

**Comment by n-buna404** [comment]
> How do I go back to weekly if I picked daily by mistake?

There will be an empty file name 'daily' in directory same as mpv. Rename it to 'weekly' so u opt for the sourceforge weekly release again.

**Comment by BrianG61UK** [comment]
Why is it able to create the 'daily' file if you choose 2 but unable to create the 'weekly' file if you choose 1??
