### ISSUE TITLE
ffmpeg: add --enable-gnutls for mpv to work with -tls-verify=yes

### ISSUE THREAD

**Issue by mitzsch** [shinchiro/mpv-winbuild-cmake#189]
Hi!
Just tried this awesome repo to build mpv packages for windows! Just something I noticed is whenever you need to run mpv with `-tls_verify=yes` it will fail due to not finding a cert.pem! Would be awesome if this could be fixed!

`[ffmpeg] tls: failed to open CA file '/home/plex1/mpv/mpv-winbuild-cmake/build64/install/mingw/etc/ssl/cert.pem': No such file or directory`

**What is needed to fix this/Possible fix:**
Add --enable-gnutls to the ffmpeg.cmake and add the gnutls package to the packages that need to be compiled.

**Comment by shinchiro** [comment]
How can I reproduce it? libressl should support it fine

**Comment by mitzsch** [comment]
You can reproduce it by running 
`mpv.com https://www.youtube.com/watch?v=njX2bu-_Vw4 -tls-verify=yes`
You will get the following error
`[ffmpeg] tls: failed to open CA file '/home/shinchiro/build64/install/mingw/etc/ssl/cert.pem': No such file or directoryFailed to open https://www.youtube.com/watch?v=njX2bu-_Vw4.`


>  libressl should support it fine

I thought the same but somehow it does not. I managed to get gnutls in, and now it works.
If you like to try it out here is the modded version => https://we.tl/t-K7D9isIADm (youtube-dl not included)

The same `mpv.com https://www.youtube.com/watch?v=njX2bu-_Vw4 -tls-verify=yes` now runs fine.


How I managed to get it in. :)
**gnutls** 
dependencies 
=> gmp - already in
=> nettle - already in
=> libidn2 - newly added

**build os**
ubuntu jammy - nightly iso

**envoirenment variables**
export TARGET_HOST=x86_64-w64-mingw32
export TARGET_PREFIX="/home/alex/compile/mpv-winbuild-cmake/build64/install/mingw" 
export CC="/home/alex/compile/mpv-winbuild-cmake/build64/install/bin/x86_64-w64-mingw32-gcc"
export PKG_CONFIG="/home/alex/compile/mpv-winbuild-cmake/build64/install/bin/x86_64-w64-mingw32-pkg-config"
export PKG_CONFIG_LIBDIR="/home/alex/compile/mpv-winbuild-cmake/build64/install/mingw/lib/pkgconfig/"

"**./configure**"
libidn2 => `./configure ./configure --host=$TARGET_HOST --prefix=$TARGET_PREFIX --disable-doc --enable-shared=no`

gnutls =>` ./configure --host=$TARGET_HOST --prefix=$TARGET_PREFIX --enable-shared=no --enable-static=yes --without-p11-kit --with-included-libtasn1 --with-included-unistring --enable-local-libopts --disable-srp-authentication --disable-dtls-srtp-support --disable-heartbeat-support --disable-psk-authentication --disable-anon-authentication --disable-openssl-compatibility --without-tpm --disable-cxx --disable-guile --disable-doc --disable-maintainer-mode --disable-libdane --disable-full-test-suite LDFLAGS="-L$TARGET_PREFIX/lib"`

(I used the filezilla crosscompile (https://wiki.filezilla-project.org/Cross_Compiling_FileZilla_3_for_Windows_under_Ubuntu_or_Debian_GNU/Linux) guide as an reference for the options)

**Comment by garoto** [comment]
Give the location of the pem file to ffmpeg and it works:

`mpv --stream-lavf-o-add=cafile=C:/BIN/cacert.pem --tls-verify=yes https://www.youtube.com/watch?v=njX2bu-_Vw4`

**Comment by mitzsch** [comment]
Sure this will also work, mpv even has a dedicated command for that `-tls-ca-file=C:\path\to\cacert.pem`
The question is whether you want to specify that every time you run mpv (or put it in the mpv.conf) and keep the cacert.pem up to date or include gnutls and let it do this for you.

**Comment by garoto** [comment]
Ah ok, got it.

**Comment by shinchiro** [comment]
Gnutls seem heavy lib to be compiled & incorporated so I dont feel to replace libressl with it. You can use the workarounds to use the custom pem file

**Comment by mitzsch** [comment]
>Gnutls seem heavy lib to be compiled & incorporated so I dont feel to replace libressl with it.

Okay, I can totally understand this, but thanks for your time @shinchiro @garoto! :)

**Comment by rorgoroth** [comment]
An alternative is just to use schannel in ffmpeg, that's what I do and `mpv.com https://www.youtube.com/watch?v=njX2bu-_Vw4 -tls-verify=yes` works out of the box.

Not sure what the downside would be compared to libressl but it's certainly better than using GNUtls if you want it to just werkz. Although adding to mpv.conf is a one time thing and [cacert.pem](https://curl.se/ca/cacert.pem) could be added to packaging/updater.

**Comment by mitzsch** [comment]
Never heard of SChannel! But indeed it works! Just compiled it myself and wow - no dependencies necessary - just works!

Maybe reconsider compiling ffmpeg with `--enable-schannel`?

**Comment by rorgoroth** [comment]
> Never heard of SChannel! But indeed it works! Just compiled it myself and wow - no dependencies necessary - just works!
> 
> Maybe reconsider compiling ffmpeg with `--enable-schannel`?

The only problem is you have to disable any other tls provider to use schannel, I don't know if openssl/libressl is used for any specific reason.

**Comment by shinchiro** [comment]
fyi, libsrt & libssh still depend on libressl. I'm afraid mixing schannel and libressl could introduce some kind of bug later
