### ISSUE TITLE
How did you get around the gcc7 issues?

### ISSUE THREAD

**Issue by DeadSix27** [shinchiro/mpv-winbuild-cmake#19]
I'm unable to compile angle with gcc7.1.0, any ideas?
```
/xc/gcc6/workdir/xcompilers/mingw-w64-x86_64/include/c++/7.1.0/bits/istream.tcc:57:37: error: expected primary-expression before '.' token
        __streambuf_type* __sb = __in.rdbuf();
                                     ^
/xc/gcc6/workdir/xcompilers/mingw-w64-x86_64/include/c++/7.1.0/bits/istream.tcc:60:53: error: expected primary-expression before '.' token
        const __ctype_type& __ct = __check_facet(__in._M_ctype);
                                                     ^
/xc/gcc6/workdir/xcompilers/mingw-w64-x86_64/include/c++/7.1.0/bits/istream.tcc:74:15: error: expected primary-expression before '.' token
       if (__in.good() && __err == ios_base::goodbit)
               ^
/xc/gcc6/workdir/xcompilers/mingw-w64-x86_64/include/c++/7.1.0/bits/istream.tcc:79:8: error: expected primary-expression before '.' token
```

**Comment by shinchiro** [comment]
This patch is needed:
https://github.com/shinchiro/mpv-winbuild-cmake/blob/master/toolchain/gcc-0016-disable-weak-refs-in-libstdc%2B%2B.patch

**Comment by DeadSix27** [comment]
@shinchiro strange, I apply that patch since a long time it did not fix that, I had to apply this:
https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/thread/a5ec7029-e79a-08f1-c689-1c4bd9ea0276%40poczta.onet.pl/#msg35837097

**Comment by shinchiro** [comment]
Probably the problem lies on how gcc was built. I never got into the problem using gcc which was built with this cmake

**Comment by DeadSix27** [comment]
@shinchiro I'll compare the  way you build it with how i build it, if i find something ill report back.
