### ISSUE TITLE
Cannot index into a null array

### ISSUE THREAD

**Issue by MeijinLelouch** [shinchiro/mpv-winbuild-cmake#190]
I get this error when I run updater.bat with or without admin privillages.
I tried uninstall and reinstallation of the same version and also installing the latest version but still getting the same message
"Running script without administrator privileges
Checking Windows PowerShell version -- 5
Cannot index into a null array."

"Running script with administrator privileges
Checking Windows PowerShell version -- 5
Cannot index into a null array."

**Comment by shinchiro** [comment]
I cannot reproduce it. Download newest archive manually and try again

**Comment by Pentaphon** [comment]
Had the same problem. delete the settings.xml file and run it again. If you see it again, delete whatever it is trying to update, such as ffmpeg and run it again to let it update that itself. Or just start fresh with a new archive and empty folder.
