### ISSUE TITLE
great shinchiro 

### ISSUE THREAD

**Issue by 123ugo** [shinchiro/mpv-winbuild-cmake#191]
radeon amd hd  6870 and software radeon crismon in  windows 10 64 video colors control not work in directx 11

before  had amd hd 7750 it was perfect in radeon adrenalin , directx 12 , my dear gpu burn 

only the sharpness adjustment is missing after which I consider it the best video player ever and complete please take my idea into consideration sharpness- THERE ARE Contrast brightness gamma saturation it just lacks sharpness PLEASE YOU CAN DO IT so, control panels (AMD - NVIDIA) are no longer needed to optimize videos I AM ITALIAN EXCUSE FOR BAD ENGLISH REGARDS 😍😍😍

**Comment by shinchiro** [comment]
Better report on main mpv repo: https://github.com/mpv-player/mpv/issues

**Comment by hooke007** [comment]
The so called "sharpness adjustment" is here: https://mpv.io/manual/master/#options-sharpen

**Comment by 123ugo** [comment]
thanks shinkiro and hooke007

this 
--sharpen=<value> 

copy text in C:\Users\xxx\AppData\Roaming\mpv mpv.conf
example     --sharpen=<10> scale 1 to 10 or 10 to 100?
thanks
