### ISSUE TITLE
libressl 3.5.1 not working

### ISSUE THREAD

**Issue by CharlesMengCA** [shinchiro/mpv-winbuild-cmake#192]
Hi shinchiro,

Until someone upgrades libressl in ffmpeg to support version > v3.1.5. we have to stick with 3.1.5. 

Some sites will not work with libressl 3.5.1. For example: 

mpv -v https://www.cbc.ca/player/play/2021372483909

![image](https://user-images.githubusercontent.com/58993776/162586999-2deb16f1-447f-4240-a3a4-c7937e527134.png)

Same build options except libressl (3.1.5) will work on above URL.

**Comment by shinchiro** [comment]
Ok I withdraw the patch for now
