### ISSUE TITLE
libexpat 2.4.8 and zlib 1.2.12

### ISSUE THREAD

**Issue by CharlesMengCA** [shinchiro/mpv-winbuild-cmake#193]
Hi,

You could upgrade libexpat to 2.4.8 and zlib to 1.2.12.

libexpat 2.4.8 f79b8f904b749e3e0d20afeadecf8249c55b2e32d4ebb089ae378df479dcaf25
zlib 91844808532e5ce316b3c010929493c0244f3d37593afd6de04f71821d5136d9

**Comment by NotTsunami** [comment]
A few more libraries have been updated as well:
* libsdl2 2.0.20
* libopenmpt 0.5.17
