### ISSUE TITLE
mpv.conf

### ISSUE THREAD

**Issue by 123ugo** [shinchiro/mpv-winbuild-cmake#195]
in windows
C:\Users\my user\AppData\Roaming\mpv\mpv.conf

i copy  string 
 --sharpen=<100> in \mpv.conf
 value is 0 to 10 ?
0 to100 ?
I do not know value

please help thanks
hi

**Comment by hooke007** [comment]
Unlimited in theory.
And your issue is not related with building. Better to post to the [proper place](https://github.com/mpv-player/mpv/issues) not here.
