### ISSUE TITLE
Patch Error after Re-running CMake...

### ISSUE THREAD

**Issue by CharlesMengCA** [shinchiro/mpv-winbuild-cmake#198]
If I removed one folder in /build64/packages/, such as ffmpeg-prefix

The CMake will rerun to generate that package again. After that,  some packages will fail on patch step since no new file was downloaded, and the existing files were already patched.

Can you make the patch only run after the first download  or if there is a update? 

Thanks. :)

[0/1] Re-running CMake...
-- Parsing 8 toolchain packages
-- Parsing 83 packages
-- Configuring done
-- Generating done
-- Build files have been written to: /root/mpv-winbuild-cmake/build64
[1/44] Performing patch step for 'libbs2b'
FAILED: packages/libbs2b-prefix/src/libbs2b-stamp/libbs2b-patch /root/mpv-winbuild-cmake/build64/packages/libbs2b-prefix/src/libbs2b-stamp/libbs2b-patch 
cd /root/mpv-winbuild-cmake/build64/packages/libbs2b-prefix/src/libbs2b && /root/mpv-winbuild-cmake/build64/exec git am "/root/mpv-winbuild-cmake/packages/libbs2b-*.patch" && /usr/bin/cmake -E touch /root/mpv-winbuild-cmake/build64/packages/libbs2b-prefix/src/libbs2b-stamp/libbs2b-patch
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
[5/44] Creating directories for 'libsrt'
ninja: build stopped: subcommand failed.
[

**Comment by CharlesMengCA** [comment]
easy to reproduce.

ninja ffmpeg-removeprefix
ninja mpv

**Comment by shinchiro** [comment]
Only happen when the patch cannot be applied. This already in my todo list
