### ISSUE TITLE
Compile failed

### ISSUE THREAD

**Issue by yearharvest** [shinchiro/mpv-winbuild-cmake#2]
I'm trying to compile mpv on Windows7, and I got Error as follows:

### console log
<pre>
FAILED: packages/crossc-prefix/src/crossc-stamp/crossc-build
cd /home/Year/mpv-winbuild-cmake/build64/packages/crossc-prefix/src/crossc && /usr/bin/cmake.exe -P /home/Year/mpv-winbuild-cmake/build64/packages/crossc-prefix/src/crossc-stamp/crossc-build-.cmake && /usr/bin/cmake.exe -E touch /home/Year/mpv-winbuild-cmake/build64/packages/crossc-prefix/src/crossc-stamp/crossc-build
CMake Error at /home/Year/mpv-winbuild-cmake/build64/packages/crossc-prefix/src/crossc-stamp/crossc-build-.cmake:16 (message):
  Command failed: 2

   '/home/Year/mpv-winbuild-cmake/build64/exec' 'make' '-j8' 'CXX=x86_64-w64-mingw32-g++' 'AR=x86_64-w64-mingw32-ar'

  See also

    /home/Year/mpv-winbuild-cmake/build64/packages/crossc-prefix/src/crossc-stamp/crossc-build-*.log

</pre>

### crossc-build-out.log
<pre>
x86_64-w64-mingw32-g++ -c  -g -O2 -Wall -std=c++14 -MMD -MP SPIRV-Cross/spirv_glsl.cpp -o spirv_glsl.o
</pre>

### crossc-build-err.log
<pre>
during RTL pass: combine
SPIRV-Cross/spirv_glsl.cpp: In member function 'virtual void spirv_cross::CompilerGLSL::emit_instruction(const spirv_cross::Instruction&)':
SPIRV-Cross/spirv_glsl.cpp:8054:1: internal compiler error: in create_log_links, at combine.c:1072
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make: *** [Makefile:83：spirv_glsl.o] Error 1
</pre>

Does anybody have any idea how to fix this error?

**Comment by shinchiro** [comment]
It worked fine on WSL & linux. Probably the problem only specific with your build environment

**Comment by yearharvest** [comment]
i still don't know how to fix this error, such being the case, i want to try to compile in virtual machine. Thank you anyway!
