### ISSUE TITLE
[Question]Why not use openssl instead of libressl?

### ISSUE THREAD

**Issue by zhongfly** [shinchiro/mpv-winbuild-cmake#200]
Since #79, the version of libressl is fixed at 3.1.5. So why not use openssl instead of libressl? From a security point of view, a constantly updated openssl is more reliable than a fixed version of libressl
I have tested the ffmpeg compiled with openssl (https://github.com/BtbN/FFmpeg-Builds), ffplay will not report an error when playing twitter online video.

**Comment by zhongfly** [comment]
I found your previous [reply ](https://github.com/mpv-player/mpv/issues/5172#issuecomment-349289142)in mpv, maybe I already know part of the answer
I tested libressl 3.5.2 and the problem still exists.Maybe this bug should be submitted to ffmpeg or libressl

**Comment by shinchiro** [comment]
As someone mentioned in #192, ffmpeg need update itself to support newer libressl. Maybe in future, I'll consider to use schannel over libressl
