### ISSUE TITLE
[request] compile with frei0r filters

### ISSUE THREAD

**Issue by junguler** [shinchiro/mpv-winbuild-cmake#203]
hi, 

i wanted to know if it's possible to include frei0r filters with these binaries? i'm not knowledgeable enough to do it myself unfortunately and i need a specific filter from frei0r (colortap) because it turns very bright or flashing white screen to grey and makes it easier for me to watch videos inside mpv, 

thanks again for your work regardless of if you decided to include these or not.

**Comment by shinchiro** [comment]
Unfortunately, I think frei0r can only built & link as shared library so I cannot added it

**Comment by junguler** [comment]
i understand, thank you for taking the time to answer
