### ISSUE TITLE
[Request] Provide consistent URLs for latest release

### ISSUE THREAD

**Issue by Touceire** [shinchiro/mpv-winbuild-cmake#206]
Like [FFmpeg-Builds](https://github.com/BtbN/FFmpeg-Builds/releases) where in addition to the regular releases there is also a floating "Latest Auto-Build" always pointing to the most recent builds.

**Comment by shinchiro** [comment]
https://github.com/shinchiro/mpv-winbuild-cmake/releases/latest - will always redirect to latest release

**Comment by Touceire** [comment]
Yeah, but that's actually not what I meant. 
For examples FFmpeg-Builds has fixed URLs like [this](https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n5.0-latest-win64-gpl-5.0.zip) which will allow you to always download the most recent build with the same URL unlike mpv-winbuild-cmake where you have to go the release page and manually copy the link for the latest release.

**Comment by zhongfly** [comment]
> Yeah, but that's actually not what I meant. For examples FFmpeg-Builds has fixed URLs like [this](https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n5.0-latest-win64-gpl-5.0.zip) which will allow you to always download the most recent build with the same URL unlike mpv-winbuild-cmake where you have to go the release page and manually copy the link for the latest release.

maybe you can use a powershell script like this to update mpv : https://github.com/shinchiro/mpv-packaging/blob/master/mpv-root/installer/updater.ps1
