### ISSUE TITLE
mpv v0.34.1 stable build?

### ISSUE THREAD

**Issue by Barough** [shinchiro/mpv-winbuild-cmake#209]
Any change you could make a release available of v0.34.1 stable

**Comment by hooke007** [comment]
Off-topic:
It's meaningless for normal users to download the tag version.

1. the tag version is just a snapshot, it is not "stable".
2. I don't think you could get a real stable version, if you have checked the depens list.

**Comment by shinchiro** [comment]
Unfortunately, the tarball 0.34.1 is long ago, I'm afraid some of dependencies like libplacebo, etc already broken to link with it
