### ISSUE TITLE
aom is not up-to-date

### ISSUE THREAD

**Issue by zhongfly** [shinchiro/mpv-winbuild-cmake#211]
I found that the `aom` package downloaded by `ninja download` is not up-to-date, and `ninja update` cannot update it. The `aom` commit is always `402e264b94fd74bdf66837da216b6251805b4ae4`.
See https://aomedia.googlesource.com/aom/+log/refs/heads/main/?s=80c52241876661cd58592e673a427fe55bf9147b , after this commit, aom use `main` branch as actual main branch, but kept the `master` branch.

**Comment by zhongfly** [comment]
@shinchiro 
I have some questions about the use of ninja, is there any command to clear the source code of a package?
I recommend having `ninja package-fullclean` clean the source code of the package as well

**Comment by zhongfly** [comment]
In addition, I also found a strange thing, the .git folder of mingw-w64 is not `mpv-winbuild-cmake/src_packages/mingw-w64/.git`, but `mpv-winbuild-cmake/.git`

```bash
# input: git -C mpv-winbuild-cmake/src_packages/mingw-w64 rev-parse HEAD
e962ac5173df5844f99dd673594f5ca182dc87b9
# input: git -C mpv-winbuild-cmake/src_packages/mingw-w64 rev-parse --git-dir
/__w/action-test/action-test/mpv-winbuild-cmake/.git
```
is this normal?

**Comment by shinchiro** [comment]
> is there any command to clear the source code of a package?

nope. ninja `aom-removeprefix` and `rm -rf src/aom` should do the job

The git command you used probably wrong
