### ISSUE TITLE
Allow users to choose to update to ffmpeg release builds instead of just git builds?

### ISSUE THREAD

**Issue by Pentaphon** [shinchiro/mpv-winbuild-cmake#212]
The same way we can decide to get weekly/daily builds for mpv, can get also get the option to decide between git and release builds for ffmpeg?

I don't need every new git build of ffmpeg but I would like to get updated to the latest release builds of ffmpeg when they come out every few months. It would probably put less of a strain on whoever's build server we are using if some people decided to go with release builds instead of git.

**Comment by zhongfly** [comment]
ffmpeg is just something that will be built in the process of building mpv, and does not require additional resources.
If you just want a release build, you can download it elsewhere.

In addition, the current build comes from the freely available github action feature from github

**Comment by shinchiro** [comment]
Creating option for weekly/daily for ffmpeg is difficult as ffmpeg is uploaded here as byproduct when compiling mpv
