### ISSUE TITLE
libjxl patch need update

### ISSUE THREAD

**Issue by zhongfly** [shinchiro/mpv-winbuild-cmake#216]
After https://github.com/libjxl/libjxl/commit/9c1e1c1446982bddf6987a6236f0731e826570ad, libjxl patch failed.

**Comment by zhongfly** [comment]
Also need to pay attention to this [pr](https://github.com/libjxl/libjxl/pull/1443), after it is merged, the patch needs to be updated again, or the patch is no longer needed

**Comment by shinchiro** [comment]
Removed the patch for now & will force-push later when the PR is in

**Comment by zhongfly** [comment]
> Removed the patch for now & will force-push later when the PR is in

That pr doesn't completely fix libjxl, it still causes ffmpeg to not find libjxl

**Comment by Biswa96** [comment]
> it still causes ffmpeg to not find libjxl

Can you provide the error?
