### ISSUE TITLE
[Suggestion] Set a specific time to release

### ISSUE THREAD

**Issue by Obegg** [shinchiro/mpv-winbuild-cmake#218]
So I noticed that a new release is often not consistent, sometimes it's (by my time zone) 3 AM, sometimes 5 AM or 6 AM,
That's why I suggest making a specific time when there will be a new release
(Also so I can create a scheduled task where it will auto-update mpv, yt-dlp and ffmpeg)

**Comment by shinchiro** [comment]
There's no guarantee for release. It'll will release when its done
