### ISSUE TITLE
Feat .req. Try build with -ffast-math and -O3 flag

### ISSUE THREAD

**Issue by necros2k7** [shinchiro/mpv-winbuild-cmake#221]
subj

**Comment by adisib** [comment]
I wouldn't add those two in particular. I actually built with -O2 and noticed that mpv ran worse afterwards (though the file size was much smaller). However, a flag that should be added is -DNDEBUG which resulted in a significantly smaller file size for me.

**Comment by necros2k7** [comment]
> I wouldn't add those two in particular. I actually built with -O2 and noticed that mpv ran worse afterwards (though the file size was much smaller). However, a flag that should be added is -DNDEBUG which resulted in a significantly smaller file size for me.

It`s not about size but possible performance

**Comment by wangwenx190** [comment]
> I wouldn't add those two in particular. I actually built with -O2 and noticed that mpv ran worse afterwards (though the file size was much smaller). However, a flag that should be added is -DNDEBUG which resulted in a significantly smaller file size for me.

Normally the `NDEBUG` macro should be defined automatically for release builds (not sure about libmpv though)

**Comment by shinchiro** [comment]
While `-ffast-math` might have tiny performance, it also might also introduce weird error/crash on random cpu. Fyi, mpv was build with -O3 when release flag was set
