### ISSUE TITLE
Enable LTO optimization on mpv-2.dll?

### ISSUE THREAD

**Issue by CharlesMengCA** [shinchiro/mpv-winbuild-cmake#222]
Hi,

I don't know if the LTO optimization was also applied to mpv-2.dll.  Before adding the flag, the mpv.exe was always bigger than mpv-2.dll. Now the mpv.exe is smaller than mpv-2.dll.

Is there a way to check if the LTO optimization was also applied to mpv-2.dll? If not, is it possible to also apply the LTO to mpv-2.dll?

Thanks.

Also FYI. libiconv can be upgraded to 1.17.

mbedtls can be compiled with the head of git instead of v3.1.0.

**Comment by shinchiro** [comment]
The lib is not compiled separately, so yes it's compiled with lto too. I dont know how to verify it

> mbedtls can be compiled with the head of git instead of v3.1.0.

I prefer tarball release for mbedtls
