### ISSUE TITLE
Can't take a screenshot since mpv-x86_64-20220626-git-3a2838c

### ISSUE THREAD

**Issue by alexantr** [shinchiro/mpv-winbuild-cmake#228]
mpv-x86_64-20220625-git-3a2838c.7z and mpv-x86_64-20220626-git-3a2838c.7z based on same 3a2838c commit, but newer and all releases after it have bug: mpv just closes after pressing "s" button and no screenshot created.

Maybe problem is in your latest commit: https://github.com/shinchiro/mpv-winbuild-cmake/commit/ac5c78fff3757e7cc7afc9ebea7b85d0136d61c0

**Comment by ghost** [comment]
I can take screenshots but only for timestamps before one second. Odd. At any rate the 625 build does work and the 626 and 627 don't.

**Comment by plissken1138** [comment]
confirming, any screenshot function doesn't work - with or without subs, to file or to clipboard with clipshot.lua.

mpv-x86_64-20220625-git-3a2838c works, rolling back to it.

**Comment by plissken1138** [comment]
20220628 doesn't fix the problem.

mpv still closes instead of taking screenshot.

**Comment by alexantr** [comment]
@plissken1138 wait for next release. 20220628 was generated before fix was commited

**Comment by alexantr** [comment]
I checked 20220629, the problem has gone away 🎉

**Comment by n-buna404** [comment]
@shinchiro screenshot with jxl still failed with 20220630 version. may is due to this commit https://github.com/shinchiro/mpv-winbuild-cmake/commit/ac5c78fff3757e7cc7afc9ebea7b85d0136d61c0 i tested 20220623 was the last working version.
it will prompt error taking screenshot and produce jxl files with 0 bytes
