### ISSUE TITLE
You should be able to un-un-un-clamp the zimg commit now.

### ISSUE THREAD

**Issue by ghost** [shinchiro/mpv-winbuild-cmake#230]
https://github.com/sekrit-twc/zimg/commit/26131c19d014ebef2b48e611e986bc5246ac4a90 references https://github.com/sekrit-twc/zimg/issues/182 which references https://github.com/shinchiro/mpv-winbuild-cmake/issues/227 which was the justification for https://github.com/shinchiro/mpv-winbuild-cmake/commit/15d69f4c0e3c55d4ae0123c8b55f9f785a30bad9. Same time next Friday? :-D

Like I mentioned in https://github.com/shinchiro/mpv-winbuild-cmake/issues/227#issuecomment-1169446587, other projects have been using the [sekrit-twc/zimg:v3.0](https://github.com/sekrit-twc/zimg/tree/v3.0) branch instead of master, which is probably a more sustainable long-term option.

**Comment by shinchiro** [comment]
~Its partially fixed. `Ctrl+s` still crash mpv though~
nvm. Forgot to update graphengine too

**Comment by CrendKing** [comment]
@shinchiro Oh no, the crash is back again with the same stacktrace, at [20220703](https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20220703). Just open the image from https://github.com/mpv-player/mpv/issues/10239 to repro.

**Comment by CrendKing** [comment]
zimg [fixed another issue](https://github.com/sekrit-twc/zimg/issues/182#issuecomment-1174017320), and 20220705 build no longer crashes for me.
