### ISSUE TITLE
Procedure entry point GetPackagePathByFullName not found in DLL library kernel32.dll

### ISSUE THREAD

**Issue by idMysteries** [shinchiro/mpv-winbuild-cmake#234]
Versions with error:
mpv-x86_64-20220709-git-c7b17be 
mpv-x86_64-20220710-git-0044c19

Version mpv-x86_64-20220705-git-369168b works without errors

Error: Procedure entry point GetPackagePathByFullName not found in DLL library kernel32.dll

Win 7 SP1

**Comment by ghost** [comment]
Could you run it with -vv?

**Comment by shinchiro** [comment]
Latest changes in vulkan loader (https://github.com/KhronosGroup/Vulkan-Loader/commit/9a45e5a4ab79b81e27e1417ca65d53ecfe57ba37) makes vulkan not longer supported in windows 7

**Comment by idMysteries** [comment]
> Latest changes in vulkan loader ([KhronosGroup/Vulkan-Loader@9a45e5a](https://github.com/KhronosGroup/Vulkan-Loader/commit/9a45e5a4ab79b81e27e1417ca65d53ecfe57ba37)) makes vulkan not longer supported in windows 7

So... 20220705 is this the latest version for me? Apparently, it's time to switch to Linux.

**Comment by shinchiro** [comment]
20220712+ will support windows 7 back due to changes in upstream
