### ISSUE TITLE
I can't update with updater.bat

### ISSUE THREAD

**Issue by lucaspir7** [shinchiro/mpv-winbuild-cmake#238]
![Screenshot 2022-07-17 184540](https://user-images.githubusercontent.com/10765974/179419443-d8770704-5131-48ce-be91-a0658741a580.jpg)

I only get this message in my main PC. mpv is not open but to update it I have to manually extract the zipped file. I always get this strange error.

How can I fix it?

**Comment by garoto** [comment]
Zombie `mpv.exe` process in the background or AV shenanigans. Try running `taskkill.exe /t /f /im mpv.exe` before running the script.

Wrong repo btw.

**Comment by lucaspir7** [comment]
> Zombie `mpv.exe` process in the background or AV shenanigans. Try running `taskkill.exe /t /f /im mpv.exe` before running the script.
> 
> Wrong repo btw.

It tells me ERROR: The process "mpv.exe" not found.
But after I noticed it was the wrong repo I downloaded the correct one and it works like a charm.
I still don't understand why I get the [zhongfly](https://github.com/zhongfly) repo from the [shinchiro](https://sourceforge.net/u/shinchiro/profile/)

**Comment by Hackerpcs** [comment]
I have the same issue that appeared around a month ago, Windows 10 21h2, AV Windows Defender (disabling it doesn't do anything), mpv isn't on a protected folder that needs admin privileges. I'm on this repo

![Untitled](https://user-images.githubusercontent.com/17467335/181581150-c02270b9-59b3-4071-83a7-ec3cdcf53b14.png)

**Comment by j-mas** [comment]
Same here! 😣

**Comment by lucaspir7** [comment]
> I have the same issue that appeared around a month ago, Windows 10 21h2, AV Windows Defender (disabling it doesn't do anything), mpv isn't on a protected folder that needs admin privileges. I'm on this repo
> 
> ![Untitled](https://user-images.githubusercontent.com/17467335/181581150-c02270b9-59b3-4071-83a7-ec3cdcf53b14.png)

If you are using zhongfly I found out what was the problem at least in my case.
It was because of OneDrive, when I close it there is no error and I can update.

But still the shinchiro version has not this problem even with OneDrive active in the system background, this is why now I prefer it.

**Comment by Hackerpcs** [comment]
I don't have OneDrive installed at all and I'm on this repo, downloading the latest release and testing it with the weekly update so it tries to download 24 July build
