### ISSUE TITLE
Question about libjxl

### ISSUE THREAD

**Issue by CharlesMengCA** [shinchiro/mpv-winbuild-cmake#240]
Hi Shinchiro,

If I used your script without modification, the build would succeed.

If I disabled ffmpeg encoders and just enabled libjxl like following:
        --disable-encoders
        --enable-encoder=libjxl

I got this error:
root/mpv-winbuild-cmake/build64/install/lib/gcc/x86_64-w64-mingw32/12.1.1/../../../../x86_64-w64-mingw32/bin/ld: /root/mpv-winbuild-cmake/build64/install/mingw/lib/libzimg.a(libzimg_internal_la-libm_wrapper.o):libm_wrapper.c:(.text$powf[powf]+0x0): **multiple definition of `powf'**; /root/mpv-winbuild-cmake/build64/install/mingw/lib/libmingwex.a(lib64_libmingwex_a-powf.o):/root/mpv-winbuild-cmake/build64/toolchain/mingw-w64-prefix/src/mingw-w64/**mingw-w64-crt/math/powf.c:8: first defined here**

if I tried to manually link the exe and dll by removing mpv-winbuild-cmake/build64/install/mingw/lib/**libmingwex.a**, the link process would work. And the screen capture of my build to jxl format will work.

Is there a way to exclude libmingwex.a from link through meson parameters?

Thanks a lot,

Charles

**Comment by shinchiro** [comment]
> Is there a way to exclude libmingwex.a from link through meson parameters?

Not sure if there is way to exclude libs
