### ISSUE TITLE
Updater error when using x86_64-v3 with weekly builds

### ISSUE THREAD

**Issue by Silver-Fullbuster** [shinchiro/mpv-winbuild-cmake#246]
Using the updater for weekly builds and x86_64-v3 results in error, due to incorrect selection of latest file from rss. 

As can be seen from the debugger below, the latest selection logic chooses README.rst instead of the latest build, causing errors later into the script.
![image](https://user-images.githubusercontent.com/22327220/187097778-72c6709a-88e8-44c6-8790-1f36379752c7.png)

**Comment by shinchiro** [comment]
Should be fixed now
