### ISSUE TITLE
"The path is not of a legal form" when trying to update x86-64-v3

### ISSUE THREAD

**Issue by Pentaphon** [shinchiro/mpv-winbuild-cmake#247]
I moved to using v3 and on my Ryzen machine and mpv works fine but when trying out the updater, I got this error on the same folder I've been using mpv on for the past 2 years. 

![Untitled](https://user-images.githubusercontent.com/49374058/187156446-83f88daa-11cb-4d18-a403-1f4f2c10682b.png)

**Comment by shinchiro** [comment]
Download newer 7z archive

**Comment by Pentaphon** [comment]
> Download newer 7z archive

Thanks, I downloaded mpv-x86_64-v3-20220829-git-211ce69.7z that was uploaded to Sourceforge less than an hour ago and unzipping that worked. I guess the one from 2022-08-28 still had an issue.

**Comment by akiirui** [comment]
The true way is delete `settings.xml` and re-run `updater.bat` to generate a new `settings.xml`
