### ISSUE TITLE
another? libjxl and ffmpeg issue on ubuntu 22.04

### ISSUE THREAD

**Issue by nizmogtr** [shinchiro/mpv-winbuild-cmake#251]
ffmpeg compile errors out with the following:

/tmp/ffconf.739Bogl4/test.c: In function 'check_JxlDecoderVersion':
/tmp/ffconf.739Bogl4/test.c:3:45: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    3 | long check_JxlDecoderVersion(void) { return (long) JxlDecoderVersion; }
      |                                             ^
x86_64-w64-mingw32-gcc -L/opt/lib -L/usr/local/lib -Wl,--nxcompat,--dynamicbase -Wl,--high-entropy-va -Wl,--as-needed -Wl,--image-base,0x140000000 -DHWY_STATIC_DEFINE -I/home/dave/src/mpv-winbuild-cmake/build64/install/mingw/include -L/home/dave/src/mpv-winbuild-cmake/build64/install/mingw/lib -o /tmp/ffconf.739Bogl4/test.exe /tmp/ffconf.739Bogl4/test.o -ljxl -lm -lstdc++ -lhwy -lbrotlienc -lbrotlidec -lbrotlicommon -llcms2 -lm -lpthread
/home/dave/src/mpv-winbuild-cmake/build64/install/lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld: /tmp/ffconf.739Bogl4/test.o:test.c:(.text+0x2): undefined reference to `__imp_JxlDecoderVersion'
collect2: error: ld returned 1 exit status
ERROR: libjxl >= 0.7.0 not found using pkg-config

**Comment by shinchiro** [comment]
Cannot reproduce on my system. Make sure use latest git

**Comment by kasper93** [comment]
@nizmogtr: Fixed by https://github.com/shinchiro/mpv-winbuild-cmake/pull/257
