### ISSUE TITLE
not actually an issue but...

### ISSUE THREAD

**Issue by palunglaut** [shinchiro/mpv-winbuild-cmake#26]
First time mpv user here, where is the mpv.conf file located? i downloaded the latest build at https://sourceforge.net/projects/mpv-player-windows/files/ and i read the guide you need to put line manually in mpv.conf file for change, but i cannot found it anywhere even after i search my whole C drive. Thanks in advance.

**Comment by shinchiro** [comment]
In the archive, inside `installer` folder, there's file called `configure-opengl-hq.bat`. Running it will automatically create the `mpv.conf` file inside new `mpv` folder. You can open the file and edit it with any editor like notepad++ or something else

**Comment by palunglaut** [comment]
thank you for the help friend, no wonder i couldn't find it anywhere.
