### ISSUE TITLE
App freezes when video filter applied

### ISSUE THREAD

**Issue by efauk** [shinchiro/mpv-winbuild-cmake#26]
First of all, apologies if this bug shouldn't be reported here :)

I'm building mpv using mpv-winbuild-cmake. Once I have got the executable, If I start the app with the command:

> mpv.exe --vf=lavfi=[movie=C\\:/logo.png[watermark],[in][watermark]overlay=1:1] C:\movie.mp4

a logo is shown on top of the video using a ffmpeg video filter.

So far so good, but if i start seeking quickly, the app hangs after a few seeks.

I'm pretty sure that the app behaved well under the same conditions a couple of months ago, and some update of a third-party library is causing now the issue.

I'm trying to detect which library is causing the issue, but I'm a bit lost.

Any help will be appreciated.

**Comment by shinchiro** [comment]
Probably ffmpeg bugs. Better file an issue on their issue tracker
