### ISSUE TITLE
what is mpv-x86_64-v3

### ISSUE THREAD

**Issue by Goten87** [shinchiro/mpv-winbuild-cmake#262]
Sorry dint know where to ask it
But what is the difference for mpv-x86_64-v3 and mpv-x86_64 ?

**Comment by garoto** [comment]
`v3` are compiler optimizations targeted at CPUs (from Intel from what I gather) built after 2012 that ships with a specific set of instructions built-in.

See: https://github.com/shinchiro/mpv-winbuild-cmake/issues/244

**Comment by myfreeer** [comment]
See <https://github.com/shinchiro/mpv-winbuild-cmake/wiki/Difference-between-x86_64-and-x86_64-v3>
<https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels>

**Comment by shinchiro** [comment]
As said above

**Comment by paucoma** [comment]
It would be nice if this question/answer was in the README.rst which is in the sourceforge files page at https://sourceforge.net/projects/mpv-player-windows/files/ 

Something as short as a link to the page should be sufficient in my opinion: 

[Difference between x86_64 and x86_64 v3
](https://github.com/shinchiro/mpv-winbuild-cmake/wiki/Difference-between-x86_64-and-x86_64-v3/_history)

Thanks for providing these builds =)
