### ISSUE TITLE
Updater doesn't work on Windows 11

### ISSUE THREAD

**Issue by evoserver** [shinchiro/mpv-winbuild-cmake#264]
-- mpv version mpv-x86_64-20221016-git-cdcbd73
-- Windows 11 22H2 (build 22621.674)

Updater.bat doesn't work. Since Windows 11 the following message appears:

Running script without administrator privileges
Checking Windows PowerShell version -- 5
Fetching RSS feed for mpv
Formato del percorso non valido. (Invalid format of path)

The same happens with administrator privileges.

**Comment by djdv** [comment]
See: https://github.com/shinchiro/mpv-winbuild-cmake/issues/247
And specifically this comment after a manual update: https://github.com/shinchiro/mpv-winbuild-cmake/issues/247#issuecomment-1259687417

**Comment by BrianG61UK** [comment]
I've long since given up using the updater on any version of Windows. They keep changing it and breaking it.

**Comment by shinchiro** [comment]
I believed it already answered
