### ISSUE TITLE
feature request: adding decoders of avs2/3 (10bit)

### ISSUE THREAD

**Issue by hooke007** [shinchiro/mpv-winbuild-cmake#269]
related commit of mpv
https://github.com/mpv-player/mpv/commit/375076578f4c1c450ecf0b60de6290ad9942ddfc

ref
https://github.com/xatabhk/FFmpeg-avs2-avs3
https://github.com/xatabhk/davs2-10bit
https://github.com/uavs3/uavs3d

**Comment by zhongfly** [comment]
Btbn's ffmpeg build have avs2/3 support, so we can refer it.
See https://github.com/BtbN/FFmpeg-Builds/blob/master/scripts.d/50-davs2.sh and https://github.com/BtbN/FFmpeg-Builds/blob/master/scripts.d/50-uavs3d.sh

**Comment by hooke007** [comment]
> Btbn's ffmpeg build

I see but it doesn't support 10bit.

**Comment by hooke007** [comment]
@shinchiro Thanks for the quick response, unfortunately 10bit decoding could not work here.

Test samples
avs3 10bit https://github.com/xatabhk/avs2-avs3-video-samples/blob/master/jellyfish-640x360-avs3-10bit.mkv
avs2 10bit https://github.com/xatabhk/avs2-avs3-video-samples/blob/master/CCTV4K.AVS2-10bit.AC3.CB.08-27-6s.mkv

**Comment by shinchiro** [comment]
In theory, it should work for uavs3d. I dont what's wrong with it. davs2 dont support 10bit when compiling

**Comment by zhongfly** [comment]
https://github.com/uavs3/uavs3d/commit/b388875ee9e3ad3784ebc913c6eff3264f4a8720 should have fixed 10bit decode for uavs3
