### ISSUE TITLE
libEGL.dll & libGLESv2.dll from firefox don't work

### ISSUE THREAD

**Issue by shinstimulateshinstimulate** [shinchiro/mpv-winbuild-cmake#27]
When using libEGL.dll & libGLESv2.dll from  firefox latest stable 67.0.2 64bit installation I get this error in the log 
```
[11069520] vo/gpu/opengl: Initializing GPU context 'angle'
[11075684]     vo/gpu: Failed to load LIBEGL.DLL
[11079683]     vo/gpu: Failed initializing any suitable GPU context!
[11084104]    cplayer: Error opening/initializing the selected video_out (--vo) device.
```
and then mpv exits.

trying with -v --no-config --gpu-context=angle it falls back to direct3d 
```
[vo/gpu/opengl] Initializing GPU context 'angle'
[vo/gpu] Failed to load LIBEGL.DLL
[vo/direct3d] Setting backbuffer dimensions to (1920x1080).
```
Chrome dll files work fine

**Comment by shinstimulateshinstimulate** [comment]
Firefox dll: https://filebin.net/695bts7tw8dcybps
Chrome dll: https://filebin.net/33714m95it6zuvm9

**Comment by shinchiro** [comment]
Probably caused by old headers or whatsoever. Should be solved by now I think
