### ISSUE TITLE
New build will crash if using vulkan gpu-api

### ISSUE THREAD

**Issue by CharlesMengCA** [shinchiro/mpv-winbuild-cmake#273]
It is very likely related  to one of four commits on Oct 31, 2022 in Vulkan-Loader. no problem when built using tag d4cb3b54bb822c819b378af478145b60320e6679 of Oct 27.

![image](https://user-images.githubusercontent.com/58993776/199373793-130ade0c-2ad0-4d98-969c-027024ef1d80.png)

**Comment by shinchiro** [comment]
Better you open the issue on their repo as they might not notice the issue

**Comment by CharlesMengCA** [comment]
https://github.com/KhronosGroup/Vulkan-Loader/issues/1052
