### ISSUE TITLE
please add support for teletext subtitles (build ffmpeg with libzvbi)

### ISSUE THREAD

**Issue by cloph** [shinchiro/mpv-winbuild-cmake#276]
see topic - teletext based subtitles are still quite common here, but to decode the dvb-telextext, ffmpeg needs to be compiled with libzvbi
https://ffmpeg.org/ffplay-all.html#libzvbi_002dteletext

to use it in mpv, I have a input.conf statement that cycles through the commonly used teletext-page values (149, 150, 777 and 160 here, depending on the station)

**Comment by adlerzei** [comment]
can't you just add the `--enable-libzvbi` flag to the configure command in ./packages/ffmpeg.cmake?

**Comment by adlerzei** [comment]
I just tried to build mpv with the libzvbi flag. If you want I can provide you with the builds so that you can test if it works: https://github.com/adlerzei/mpv-winbuild-cmake/releases/tag/libzvbi

**Comment by cloph** [comment]
yes, that's how you can enable it in mpv-build/similar setups, my request is more targeted towards the generated windows binaries..

**Comment by adlerzei** [comment]
look at the release I linked in my last comment to get generated windows binaries
