### ISSUE TITLE
Latest build: back and forward problem.

### ISSUE THREAD

**Issue by RandomGuy456** [shinchiro/mpv-winbuild-cmake#28]
Using the last mpv-x86_64-20190622-git-c9e7473.7z, i've had a problem to move throught any kind of video, it freezes and stop the video.

Solved going back to the previous 20190616 version.

**Comment by efauk** [comment]
I had a similar issue, and the package causing it was mingw-w64.
If i forced it to download an older version, the issue disappeared.
I hope that helps :)

**Comment by RandomGuy456** [comment]
> I had a similar issue, and the package causing it was mingw-w64.
> If i forced it to download an older version, the issue disappeared.

how to force to download an older version of mingw-w64?

**Comment by shinchiro** [comment]
Cannot reproduce the problem on my windows 10. If mingw is the problem, I should face the same problem as well

**Comment by principealex1** [comment]
Oh, i forgot to mention that i use mpv with Smplayer ^^, so this new version has problems with Smplayer, so i think it's a problem that should solve the developer of that player.
