### ISSUE TITLE
GCC source down

### ISSUE THREAD

**Issue by adlerzei** [shinchiro/mpv-winbuild-cmake#288]
Just a short question:
Is there any reason why you used mirrorservice.org as source location of the gcc snapshot in gcc.cmake instead of the official snapshot by GNU ([https://gcc.gnu.org/pub/gcc/snapshots/12-20221022/](https://gcc.gnu.org/pub/gcc/snapshots/12-20221022/))? I'm asking because mirrorservice is down for network maintenance for the next two days and I want to replace the source location in my personal fork.

**Comment by rorgoroth** [comment]
In my experience mirrors are used to lighten the load on the "sources" resources just out of courtesy and to (ironically in this case) attempt to be more reliable than one link getting hammered by having many copies spread around.

You can set it to absolutely whatever you want.

**Comment by adlerzei** [comment]
Thanks
