### ISSUE TITLE
assertion failed

### ISSUE THREAD

**Issue by not-your-conscience** [shinchiro/mpv-winbuild-cmake#29]
mpv-x86_64-20170729-git-df12f76 build crashes on win7x64
![screenshot_1](https://user-images.githubusercontent.com/2331578/28882370-6039d0aa-77ee-11e7-83ff-dee12c259013.png)

**Comment by shinchiro** [comment]
Report here: https://github.com/mpv-player/mpv/issues/new

Post log too
