### ISSUE TITLE
mingw-w64-crt errors out at configure 

### ISSUE THREAD

**Issue by EndlesslyFlowering** [shinchiro/mpv-winbuild-cmake#291]
`configure: error: link tests are not allowed after AC_NO_EXECUTABLES`
I tried both on Ubuntu 22.04.1 LTS via WSL2 and Arch via WSL2 to the same result.

[mingw-w64-crt-configure-out.log](https://github.com/shinchiro/mpv-winbuild-cmake/files/10053558/mingw-w64-crt-configure-out.log)

**Comment by DeadSix27** [comment]
The issue is happening after this commit to mingw:

https://sourceforge.net/p/mingw-w64/mingw-w64/ci/7c6112f3ef026b308e9d0dc79475bd0cc85d5794/

you can stick to

https://sourceforge.net/p/mingw-w64/mingw-w64/ci/09a6458131cda15b85cabd4a380dd5426deb7943/

in the meantime

**Comment by CharlesMengCA** [comment]
mingw-w64 has fixed the problem. This can be closed.

**Comment by EndlesslyFlowering** [comment]
thank you both!
got gcc to build again :)
