### ISSUE TITLE
Build 20221126  crashed when trying to play some audio format

### ISSUE THREAD

**Issue by CharlesMengCA** [shinchiro/mpv-winbuild-cmake#292]
Hi Shinchiro,

FYI: Build 20221126  crashed when trying to play some audio format

Tested on your build and my own build. 

[cplayer] Command line options: 'e:\161223 JSJ Belly Dance Team Lim Seong-mi-Heart of Percussion Belly Dance Performance (Jungnang Club Madang Christmas Festival Jungnang East Market).webm' '-v'
[cplayer] mpv 0.35.0-22-ge97e0e4d92 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sat Nov 26 12:37:14 2022
[cplayer] libplacebo version: v5.229.1-33-g7ead30d
[cplayer] FFmpeg version: git-2022-11-25-0c5af908c
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       57.43.100
[cplayer]    libavcodec      59.54.100
[cplayer]    libavformat     59.34.102
[cplayer]    libswscale      6.8.112
[cplayer]    libavfilter     8.50.101
[cplayer]    libswresample   4.9.100
[cplayer] 
[cplayer] Configuration: meson configure build -Dprefix=/__w/mpv-winbuild-cmake/mpv-winbuild-cmake/build64-v3/install/mingw -Dbuildtype=release -Doptimization=3
[cplayer] List of enabled features: av-channel-layout build-date cplayer cuda-hwaccel cuda-interop d3d-hwaccel d3d11 d3d9-hwaccel direct3d dos-paths dvdnav egl-angle egl-angle-win32 egl-helpers ffmpeg ffnvcodec gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win32 gpl iconv javascript jpeg jpegxl lcms2 libarchive libass libavdevice libbluray libm libmpv-shared libplacebo libplacebo-next luajit manpage-build noexecstack openal pdf-build plain-gl rubberband rubberband-3 sdl2 sdl2-audio sdl2-gamepad sdl2-video shaderc spirv-cross stdatomic threads uchardet vapoursynth vector vulkan wasapi win32 win32-desktop win32-executable win32-internal-pthreads zimg zlib
[cplayer] Built with NDEBUG.
[cplayer] Setting option 'v' = '' (flags = 8)
[cplayer] Waiting for scripts...
[osd/libass] libass API version: 0x1600010
[osd/libass] libass source: commit: 5b3fe279a65f0881e8ca4b3016accd961e0da511
[osd/libass] Shaper: FriBidi 1.0.12 (SIMPLE) HarfBuzz-ng 5.3.1 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider directwrite (with GDI)
[osd/libass] Done.
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Done loading scripts.
[cplayer] Running hook: ytdl_hook/on_load
[ytdl_hook] ytdl:// hook 
[ytdl_hook] not a ytdl:// url 
[cplayer] Set property: shared-script-properties -> 1
[ifo_dvdnav] Opening e:\161223 JSJ Belly Dance Team Lim Seong-mi-Heart of Percussion Belly Dance Performance (Jungnang Club Madang Christmas Festival Jungnang East Market).webm
[bdmv/bluray] Opening e:\161223 JSJ Belly Dance Team Lim Seong-mi-Heart of Percussion Belly Dance Performance (Jungnang Club Madang Christmas Festival Jungnang East Market).webm
[file] Opening e:\161223 JSJ Belly Dance Team Lim Seong-mi-Heart of Percussion Belly Dance Performance (Jungnang Club Madang Christmas Festival Jungnang East Market).webm
[cplayer] Set property: shared-script-properties -> 1
[demux] Trying demuxers for level=normal.
[mkv] Deferring reading cues.
[mkv] All headers are parsed!
[osd/libass] libass API version: 0x1600010
[osd/libass] libass source: commit: 5b3fe279a65f0881e8ca4b3016accd961e0da511
[demux] Detected file format: Matroska
[cplayer] Opening done: e:\161223 JSJ Belly Dance Team Lim Seong-mi-Heart of Percussion Belly Dance Performance (Jungnang Club Madang Christmas Festival Jungnang East Market).webm
[osd/libass] Shaper: FriBidi 1.0.12 (SIMPLE) HarfBuzz-ng 5.3.1 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider directwrite (with GDI)
[osd/libass] Done.
[find_files] Loading external files in e:\
[cplayer] Running hook: ytdl_hook/on_preloaded
[mkv] select track 0
[mkv] select track 1
[cplayer]  (+) Video --vid=1 (*) (vp9 1080x1920 60.000fps)
[cplayer]  (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
[vo/gpu] Probing for best GPU context.
[vo/gpu/d3d11] Initializing GPU context 'd3d11'
[vo/gpu/d3d11] Using Direct3D 11 feature level 12_1
[vo/gpu/d3d11] Device Name: NVIDIA GeForce GTX 1650 SUPER
[vo/gpu/d3d11] Device ID: 10de:2187 (rev a1)
[vo/gpu/d3d11] Subsystem ID: 1028:1365
[vo/gpu/d3d11] LUID: 000000000000c748
[vo/gpu/d3d11] Initializing SPIR-V compiler 'shaderc'
[vo/gpu/d3d11] Using Direct3D 11.1 runtime
[vo/gpu/d3d11] Maximum Texture2D size: 16384x16384
[vo/gpu/d3d11] D3DCompiler version: 10.0.19041.868
[vo/gpu/d3d11] Using DXGI 1.2+
[vo/gpu/d3d11] Queried output: \\.\DISPLAY1, 2560x1440 @ 8 bits, colorspace: RGB_FULL_G22_NONE_P709 (0)
[vo/gpu/d3d11] Selected swapchain format R8G8B8A8_UNORM (28), attempting to utilize it.
[vo/gpu/d3d11] Selected swapchain color space RGB_FULL_G22_NONE_P709 (0), attempting to utilize it.
[vo/gpu/d3d11] Swapchain capabilities for color space RGB_FULL_G22_NONE_P709 (0): normal: yes, overlay: yes
[vo/gpu/d3d11] Swapchain successfully configured to color space RGB_FULL_G22_NONE_P709 (0)!
[vo/gpu/d3d11] Using flip-model presentation
[vo/gpu] Testing FBO format rgba16hf
[vo/gpu] Using FBO format rgba16hf.
[vo/gpu] No advanced processing required. Enabling dumb mode.
[vo/gpu/win32] DPI detected from the new API: 96
[vo/gpu/win32] display-fps: 74.971000
[vo/gpu/win32] color-profile: C:\Windows\system32\spool\drivers\color\S2721DS.icm
[vo/gpu] Assuming 74.971000 FPS for display sync.
[vd] Container reported FPS: 60.000002
[vd] Codec list:
[vd]     vp9 - Google VP9
[vd]     libvpx-vp9 (vp9) - libvpx VP9
[vd]     vp9_cuvid (vp9) - Nvidia CUVID VP9 decoder
[vd]     vp9_qsv (vp9) - VP9 video (Intel Quick Sync Video acceleration)
[vd] Opening decoder vp9
[vd] No hardware decoding requested.
[vd] Using software decoding.
[vd] Detected 16 logical cores.
[vd] Requesting 16 threads for decoding.
[vd] Selected codec: vp9 (Google VP9)
[vf] User filter list:
[vf]   (empty)
[ad] Codec list:
[ad]     opus - Opus
[ad]     libopus (opus) - libopus Opus
[ad] Opening decoder opus
[ad] Requesting 1 threads for decoding.
[ad] Selected codec: opus (Opus)
[af] User filter list:
[af]   (empty)
[cplayer] Starting playback...

**Comment by CharlesMengCA** [comment]
Same file played on 20221124 build

[cplayer] Command line options: '-v' 'e:\161223 JSJ Belly Dance Team Lim Seong-mi-Heart of Percussion Belly Dance Performance (Jungnang Club Madang Christmas Festival Jungnang East Market).webm'
[cplayer] mpv 0.35.0-21-gead8469454 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Thu Nov 24 12:53:09 2022
[cplayer] libplacebo version: v5.229.1-33-g7ead30d
[cplayer] FFmpeg version: git-2022-11-23-c8e9cc8d2
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       57.43.100
[cplayer]    libavcodec      59.54.100
[cplayer]    libavformat     59.34.102
[cplayer]    libswscale      6.8.112
[cplayer]    libavfilter     8.50.101
[cplayer]    libswresample   4.9.100
[cplayer] 
[cplayer] Configuration: meson configure build -Dprefix=/__w/mpv-winbuild-cmake/mpv-winbuild-cmake/build64-v3/install/mingw -Dbuildtype=release -Doptimization=3
[cplayer] List of enabled features: av-channel-layout build-date cplayer cuda-hwaccel cuda-interop d3d-hwaccel d3d11 d3d9-hwaccel direct3d dos-paths dvdnav egl-angle egl-angle-win32 egl-helpers ffmpeg ffnvcodec gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win32 gpl iconv javascript jpeg jpegxl lcms2 libarchive libass libavdevice libbluray libm libmpv-shared libplacebo libplacebo-next luajit manpage-build noexecstack openal pdf-build plain-gl rubberband rubberband-3 sdl2 sdl2-audio sdl2-gamepad sdl2-video shaderc spirv-cross stdatomic threads uchardet vapoursynth vector vulkan wasapi win32 win32-desktop win32-executable win32-internal-pthreads zimg zlib
[cplayer] Built with NDEBUG.
[cplayer] Setting option 'v' = '' (flags = 8)
[cplayer] Waiting for scripts...
[osd/libass] libass API version: 0x1600010
[osd/libass] libass source: commit: 5b3fe279a65f0881e8ca4b3016accd961e0da511
[osd/libass] Shaper: FriBidi 1.0.12 (SIMPLE) HarfBuzz-ng 5.3.1 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider directwrite (with GDI)
[osd/libass] Done.
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Done loading scripts.
[cplayer] Running hook: ytdl_hook/on_load
[ytdl_hook] ytdl:// hook 
[ytdl_hook] not a ytdl:// url 
[cplayer] Set property: shared-script-properties -> 1
[ifo_dvdnav] Opening e:\161223 JSJ Belly Dance Team Lim Seong-mi-Heart of Percussion Belly Dance Performance (Jungnang Club Madang Christmas Festival Jungnang East Market).webm
[bdmv/bluray] Opening e:\161223 JSJ Belly Dance Team Lim Seong-mi-Heart of Percussion Belly Dance Performance (Jungnang Club Madang Christmas Festival Jungnang East Market).webm
[file] Opening e:\161223 JSJ Belly Dance Team Lim Seong-mi-Heart of Percussion Belly Dance Performance (Jungnang Club Madang Christmas Festival Jungnang East Market).webm
[cplayer] Set property: shared-script-properties -> 1
[demux] Trying demuxers for level=normal.
[osd/libass] libass API version: 0x1600010
[osd/libass] libass source: commit: 5b3fe279a65f0881e8ca4b3016accd961e0da511
[mkv] Deferring reading cues.
[mkv] All headers are parsed!
[demux] Detected file format: Matroska
[cplayer] Opening done: e:\161223 JSJ Belly Dance Team Lim Seong-mi-Heart of Percussion Belly Dance Performance (Jungnang Club Madang Christmas Festival Jungnang East Market).webm
[osd/libass] Shaper: FriBidi 1.0.12 (SIMPLE) HarfBuzz-ng 5.3.1 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider directwrite (with GDI)
[osd/libass] Done.
[find_files] Loading external files in e:\
[cplayer] Running hook: ytdl_hook/on_preloaded
[mkv] select track 0
[mkv] select track 1
[cplayer]  (+) Video --vid=1 (*) (vp9 1080x1920 60.000fps)
[cplayer]  (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
[vo/gpu] Probing for best GPU context.
[vo/gpu/d3d11] Initializing GPU context 'd3d11'
[vo/gpu/d3d11] Using Direct3D 11 feature level 12_1
[vo/gpu/d3d11] Device Name: NVIDIA GeForce GTX 1650 SUPER
[vo/gpu/d3d11] Device ID: 10de:2187 (rev a1)
[vo/gpu/d3d11] Subsystem ID: 1028:1365
[vo/gpu/d3d11] LUID: 000000000000c748
[vo/gpu/d3d11] Initializing SPIR-V compiler 'shaderc'
[vo/gpu/d3d11] Using Direct3D 11.1 runtime
[vo/gpu/d3d11] Maximum Texture2D size: 16384x16384
[vo/gpu/d3d11] D3DCompiler version: 10.0.19041.868
[vo/gpu/d3d11] Using DXGI 1.2+
[vo/gpu/d3d11] Queried output: \\.\DISPLAY1, 2560x1440 @ 8 bits, colorspace: RGB_FULL_G22_NONE_P709 (0)
[vo/gpu/d3d11] Selected swapchain format R8G8B8A8_UNORM (28), attempting to utilize it.
[vo/gpu/d3d11] Selected swapchain color space RGB_FULL_G22_NONE_P709 (0), attempting to utilize it.
[vo/gpu/d3d11] Swapchain capabilities for color space RGB_FULL_G22_NONE_P709 (0): normal: yes, overlay: yes
[vo/gpu/d3d11] Swapchain successfully configured to color space RGB_FULL_G22_NONE_P709 (0)!
[vo/gpu/d3d11] Using flip-model presentation
[vo/gpu] Testing FBO format rgba16hf
[vo/gpu] Using FBO format rgba16hf.
[vo/gpu] No advanced processing required. Enabling dumb mode.
[vo/gpu/win32] DPI detected from the new API: 96
[vo/gpu/win32] display-fps: 74.971000
[vo/gpu/win32] color-profile: C:\Windows\system32\spool\drivers\color\S2721DS.icm
[vo/gpu] Assuming 74.971000 FPS for display sync.
[vd] Container reported FPS: 60.000002
[vd] Codec list:
[vd]     vp9 - Google VP9
[vd]     libvpx-vp9 (vp9) - libvpx VP9
[vd]     vp9_cuvid (vp9) - Nvidia CUVID VP9 decoder
[vd]     vp9_qsv (vp9) - VP9 video (Intel Quick Sync Video acceleration)
[vd] Opening decoder vp9
[vd] No hardware decoding requested.
[vd] Using software decoding.
[vd] Detected 16 logical cores.
[vd] Requesting 16 threads for decoding.
[vd] Selected codec: vp9 (Google VP9)
[vf] User filter list:
[vf]   (empty)
[ad] Codec list:
[ad]     opus - Opus
[ad]     libopus (opus) - libopus Opus
[ad] Opening decoder opus
[ad] Requesting 1 threads for decoding.
[ad] Selected codec: opus (Opus)
[af] User filter list:
[af]   (empty)
[cplayer] Starting playback...
[af] [in] 48000Hz stereo 2ch floatp
[vd] DR failed - disabling.
[af] [userspeed] 48000Hz stereo 2ch floatp
[af] [userspeed] (disabled)
[af] [convert] 48000Hz stereo 2ch floatp
[vd] Using software decoding.
[vd] Decoder format: 1080x1920 [0:1] yuv420p bt.709/auto/auto/limited/auto CL=unknown
[vd] Using container aspect ratio.
[vf] [in] 1080x1920 yuv420p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [userdeint] 1080x1920 yuv420p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [userdeint] (disabled)
[vf] [autorotate] 1080x1920 yuv420p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [autorotate] (disabled)
[vf] [convert] 1080x1920 yuv420p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [convert] (disabled)
[vf] [out] 1080x1920 yuv420p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[ao] Trying audio driver 'wasapi'
[ao/wasapi] requested format: 48000 Hz, stereo channels, floatp
[ao/wasapi] No device specified. Selecting default.
[ao/wasapi] Selecting device '{a244c14e-210c-4e7b-84f9-25c238e8fdcc}' (Speakers (MDR-1ADAC))
[ao/wasapi] Monitoring changes in device {0.0.0.00000000}.{a244c14e-210c-4e7b-84f9-25c238e8fdcc}
[ao/wasapi] Trying stereo float (32/32 bits) @ 48000hz (shared) -> ok
[ao/wasapi] Accepted as stereo float @ 48000hz -> stereo float (32/32 bits) @ 48000hz (shared)
[ao/wasapi] Device period: 10 ms
[ao/wasapi] Buffer frame count: 2400 (50 ms)
[ao/wasapi] IAudioClock::GetFrequency gave a frequency of 384000.
[ao/wasapi] device buffer: 2400 samples.
[ao/wasapi] using soft-buffer of 9600 samples.
[cplayer] AO: [wasapi] 48000Hz stereo 2ch float
[cplayer] AO: Description: Windows WASAPI audio output (event mode)
[autoconvert] inserting resampler
[swresample] format change, reinitializing resampler
[swresample] 48000Hz stereo floatp -> 48000Hz stereo float
[af] [out] 48000Hz stereo 2ch float
[cplayer] VO: [gpu] 1080x1920 yuv420p
[cplayer] VO: Description: Shader-based GPU Renderer
[vo/gpu] reconfig to 1080x1920 yuv420p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vo/gpu/win32] reset window bounds: 771:-228:1080:1920
[vo/gpu/win32] adjusted window bounds: 917:32:788:1401
[vo/gpu/win32] resize window: 788:1401
[vo/gpu/win32] resize window: 788:1401
[vo/gpu] Resize: 1080x1920
[vo/gpu] Window size: 1080x1920 (Borders: l=0 t=0 r=0 b=0)
[vo/gpu] Video source: 1080x1920 (1:1)
[vo/gpu] Video display: (0, 0) 1080x1920 -> (0, 0) 1080x1920
[vo/gpu] Video scale: 1.000000/1.000000
[vo/gpu] OSD borders: l=0 t=0 r=0 b=0
[vo/gpu] Video borders: l=0 t=0 r=0 b=0
[vo/gpu] Reported display depth: 8
[vo/gpu] Texture for plane 0: 1080x1920
[vo/gpu] Texture for plane 1: 540x960
[vo/gpu] Texture for plane 2: 540x960
[vo/gpu] Testing FBO format rgba16hf
[vo/gpu] Using FBO format rgba16hf.
[vo/gpu] No advanced processing required. Enabling dumb mode.
[vo/gpu] Resize: 788x1401
[vo/gpu] Window size: 788x1401 (Borders: l=0 t=0 r=0 b=0)
[vo/gpu] Video source: 1080x1920 (1:1)
[vo/gpu] Video display: (0, 0) 1080x1920 -> (0, 0) 788x1401
[vo/gpu] Video scale: 0.729630/0.729688
[vo/gpu] OSD borders: l=0 t=0 r=0 b=0
[vo/gpu] Video borders: l=0 t=0 r=0 b=0
[vo/gpu] Reported display depth: 8
[vo/gpu/d3d11] shaderc compile status 'success' (0 errors, 0 warnings)
[vo/gpu/d3d11] Compiled a vertex shader in 70264us
[vo/gpu/d3d11] shaderc: 67931us, SPIRV-Cross: 790us, D3DCompile: 1543us
[vo/gpu/d3d11] shaderc compile status 'success' (0 errors, 0 warnings)
[vo/gpu/d3d11] Compiled a fragment shader in 6330us
[vo/gpu/d3d11] shaderc: 3317us, SPIRV-Cross: 300us, D3DCompile: 2713us
[cplayer] first video frame after restart shown
[cplayer] audio ready
[cplayer] delaying audio start 0.001000 vs. 0.000000, diff=0.001000
[cplayer] playback restart complete @ 0.000000, audio=ready, video=playing
[cplayer] starting audio playback
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Set property: shared-script-properties -> 1
[cplayer] EOF code: 5  
[cplayer] finished playback, success (reason 3)
[cplayer] 
[cplayer] Exiting... (Quit)
[cplayer] Set property: shared-script-properties -> 1
[vo/gpu/win32] uninit

**Comment by CharlesMengCA** [comment]
Bug might be related to commits on Nov 24 by cyanreg.

BtbN's build (2022-11-25 12:36) - ffplay also crashed on the same file.

**Comment by rorgoroth** [comment]
My own builds began crashing yesterday too when attempting to play webm/vp9 youtube video, I've temporarily used ffmpeg latest release since I don't have time to hunt/bisect the recent ffmpeg changes but it does seem something from 24/25 in ffmpeg has caused this.

**Comment by shinchiro** [comment]
I noticed the issue, there's bug between the 24-26 https://github.com/FFmpeg/FFmpeg/compare/c8e9cc8d2...0c5af908c ,though someone should report to ffmpeg

**Comment by CharlesMengCA** [comment]
I don't have an account there. If someone has an account there, could you help us report?

**Comment by rorgoroth** [comment]
I seem to have narrowed it down:

fab97faf02118240c28695c1a6401e7bcc4b21a8 - BAD (https://github.com/FFmpeg/FFmpeg/commit/fab97faf02118240c28695c1a6401e7bcc4b21a8)
92100eee5b588e6cccc0b8fe3e14d35766e8bab2 - GOOD (https://github.com/FFmpeg/FFmpeg/commit/92100eee5b588e6cccc0b8fe3e14d35766e8bab2)

If someone else could double check that would be good. I tested using ffplay.

**Comment by cyanreg** [comment]
Thanks for bisecting.
Could anyone test the following diff against FFmpeg git master: https://0x0.st/o0ot.diff

**Comment by shinchiro** [comment]
Looks good. Didn't get crash so far

**Comment by CharlesMengCA** [comment]
Thanks cyanreg. It is working now.

**Comment by rorgoroth** [comment]
Yep, works for me too.

**Comment by cyanreg** [comment]
Fixed in https://github.com/FFmpeg/FFmpeg/commit/90c17a05aab798199f3cdafb7cab61f666f132be

**Comment by CharlesMengCA** [comment]
Hi shinchiro,  you may revert the clamp:  96eaa317914839ca829c24751a7cf83a4c685cd7

Thanks a lot cyanreg!
