### ISSUE TITLE
info request

### ISSUE THREAD

**Issue by wbtcpip2** [shinchiro/mpv-winbuild-cmake#303]
https://github.com/shinchiro/mpv-winbuild-cmake/releases
the mpv-2.dll of your builds is a dynamic-link library?
like any other windows dynamic dll is enough for me to wrap client.h and call the functions of mpv-2.dll or there are other steps to do to use the library?
can be used like libvlc?

thank you

**Comment by shinchiro** [comment]
Its dynamic link library. For guide using the ddl, better you ask the dev itself in their IRC
