### ISSUE TITLE
Information Request

### ISSUE THREAD

**Issue by omodia** [shinchiro/mpv-winbuild-cmake#305]
@shinchiro (I apologize for pinging you)
### Are you the author of [Mega Link Downloader](https://sites.google.com/site/shinchirosplayground/home/mega-link-downloader)?
- If you are the author, can you please provide dark theme support for [Mega Link Downloader](https://sites.google.com/site/shinchirosplayground/home/mega-link-downloader).
- I did not know how to contact you, so I apologize for creating an issue in another repository.

**Comment by shinchiro** [comment]
Sorry, it's unlikely I'll working on the downloader in the future
