### ISSUE TITLE
Switching from libmfx to libvpl

### ISSUE THREAD

**Issue by zhongfly** [shinchiro/mpv-winbuild-cmake#307]
oneVPL(libvpl) is the successor of mediaSDK(libmfx) and ffmpeg already supports using it by https://github.com/FFmpeg/FFmpeg/commit/7158f1e64d9b76afea78537a35c465447df0cff8.

**Comment by rorgoroth** [comment]
I can't test the functionality itself but I can confirm everything does build correctly enabling that library.

**Comment by shinchiro** [comment]
Merged as [f7a0825](https://github.com/shinchiro/mpv-winbuild-cmake/commit/f7a082543e02c038b46bf4c322b7f3caa8a64828)
