### ISSUE TITLE
patch of mujs broke

### ISSUE THREAD

**Issue by hooke007** [shinchiro/mpv-winbuild-cmake#308]
```
Performing patch step for 'mujs'
FAILED: packages/mujs-prefix/src/mujs-stamp/mujs-patch /__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/build64/packages/mujs-prefix/src/mujs-stamp/mujs-patch 
cd /__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/src_packages/mujs && /__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/build64/exec git am --3way "/__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/packages/mujs-*.patch" && /usr/bin/cmake -E touch /__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/build64/packages/mujs-prefix/src/mujs-stamp/mujs-patch
Applying: Add .exe to binary name
Using index info to reconstruct a base tree...
M	Makefile
Falling back to patching base and 3-way merge...
Auto-merging Makefile
CONFLICT (content): Merge conflict in Makefile
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0001 Add .exe to binary name
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
```

**Comment by zhongfly** [comment]
Maybe this can fix:https://github.com/zhongfly/mpv-winbuild-cmake/blob/mujs/packages/mujs-0001-add-exe-to-binary-name.patch

**Comment by avih** [comment]
There was a makefile change in mujs, so the patch doesn't apply anymore - https://github.com/shinchiro/mpv-winbuild-cmake/blob/master/packages/mujs-0001-add-exe-to-binary-name.patch

However, I don't understand why the patch is needed at all. It changes `mujs` to `mujs.exe`, but that is not used at all by mpv anyway. mpv only uses the library `libmujs.a`, and not the stand-alone mujs binary. So this patch is not needed as far as I can tell.

**Comment by shinchiro** [comment]
mingw produce .exe binary. If there's no exe suffix at the end, _make install_ will fail

**Comment by avih** [comment]
> mingw produce .exe binary. If there's no exe suffix at the end, _make install_ will fail

Hmmm, I'll try to forward thar report, but in the future, if you encounter an issue, you can report it here https://github.com/ccxvii/mujs/
