### ISSUE TITLE
The webpage prompted that 7z file is infected with malware

### ISSUE THREAD

**Issue by talentyang** [shinchiro/mpv-winbuild-cmake#31]
hi,
When I download 64bit mpv player(windows) from sourceforge.net, 
https://sourceforge.net/projects/mpv-player-windows/files/32bit/
The webpage prompted that 7z file is infected with malware.
Is this normal?

**Comment by shinchiro** [comment]
Obviously, it was false positive. So far, it only flagged 32bit builds. I dont know what causing it
https://www.virustotal.com/#/file/9bce4bc0b0b1b938189ccdf2bc26ead88943559470df436d25c40533c47d3a69/detection

**Comment by shinchiro** [comment]
Sourceforge already whitelisted them as per my ask
