### ISSUE TITLE
Completed bootstrapper process in Windows 11 but apps still cannot find libmpv nor .dll files

### ISSUE THREAD

**Issue by frozen-cdn** [shinchiro/mpv-winbuild-cmake#323]
Hello there, I downloaded the bootstrapper, ran the .bat file as admin, it downloaded and says it successfully installed everything but libmpv is still not working in my app (SFVIP player) that calls for it.

It either errors, in-app, saying it cannot find mpv-2.dll .  Or it says libmpv is not found in the Windows Path:  https://i.imgur.com/NmNv57q.png

Furthermore I cannot find any of these .dll files, nor .conf files - the documentation is non-existent for Windows users as far as I can tell?

Any advice would be great, thank you!  How do I install full libmpv in Windows properly?

**Comment by shinchiro** [comment]
The bootstrapper is meant to download archive that contains `mpv.exe` only. For `libmpv-2.dll`, download `mpv-dev` archive in `libmpv` directory in SF
