### ISSUE TITLE
question: 0.35.1?

### ISSUE THREAD

**Issue by wbtcpip2** [shinchiro/mpv-winbuild-cmake#326]
i see you're still building mpv 0.35.0-215-ga3340645

when you'll start build 0.35.1?

**Comment by tasty0tomato** [comment]
> when you'll start build 0.35.1?

https://sourceforge.net/projects/mpv-player-windows/files/release/

**Comment by zhongfly** [comment]
I think you are hoping to get the latest build.
Each build uses the latest source code of mpv, so please don't pay attention to whether the version number shows 0.35.0 or 0.35.1

**Comment by wbtcpip2** [comment]
are you saying that if i download this: https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20230208/mpv-dev-i686-20230208-git-a334064.7z it include all the fix listed here: https://github.com/mpv-player/mpv/releases/tag/v0.35.1 ?

**Comment by zhongfly** [comment]
So you think the latest source code (master branch) doesn't include the 0.35.1 fix?

**Comment by wbtcpip2** [comment]
no, i'm only asking because the build show version mpv 0.35.0-215-ga3340645 and i did not know that you don't follow the mpv source version number.

**Comment by shinchiro** [comment]
Well, you expect it would show **0.35.1**-215-ga3340645 but thats not the case how versioning works. Just cross check the commit hash with git master
