### ISSUE TITLE
run cmake fails on a fresh environment (clean build)

### ISSUE THREAD

**Issue by adlerzei** [shinchiro/mpv-winbuild-cmake#327]
I tried executing the build chain on a fresh Ubuntu 22.04 environment and was following your steps described in the readme. I ran in a conflict while running cmake. How can I fix this? Thanks.

Error is to long for this comment so I moved it to https://gist.github.com/adlerzei/7cd7102b230f6f911b8e0686c3e5013a

**Comment by NotSaifA** [comment]
You need to have the latest version of CMake. Useful guide: https://askubuntu.com/a/865294

**Comment by shinchiro** [comment]
I didn't encounter this problem in cmake version 3.25.2. Try update cmake
