### ISSUE TITLE
nvenc support?

### ISSUE THREAD

**Issue by saha1914** [shinchiro/mpv-winbuild-cmake#329]
whenever i try to use nvenc with each version it says unsupported hwdec

**Comment by zhongfly** [comment]
Nvidia NVENC (short for Nvidia **Encoder**)

hwdec means 'hardware video **decoder**'

So did you notice the difference? hwdec should select the options listed in the manual, https://mpv.io/manual/master/#options-hwdec .
I think you want to use `nvdec` or `nvdec-copy`.

**Comment by saha1914** [comment]
> Nvidia NVENC (short for Nvidia **Encoder**)
> 
> hwdec means 'hardware video **decoder**'
> 
> So did you notice the difference? hwdec should select the options listed in the manual, https://mpv.io/manual/master/#options-hwdec . I think you want to use `nvdec` or `nvdec-copy`.

so is it mpv that use nvenc or ffmpeg either way how to know if its working? i saw some people issue this about activation problem so i thought if there is any way of active it on windows 10 also if i set hwdec to nvdec-copy it works but nvdec wont with no notification about it.ty

**Comment by shinchiro** [comment]
nvdec is available in this build. You can check with `mpv --hwdec=help`
