### ISSUE TITLE
Help/Request: Custom Build

### ISSUE THREAD

**Issue by ksmuthucv** [shinchiro/mpv-winbuild-cmake#333]
Hello shinchiro,
We have a custom requirement of load balancing the available gpus while decoding the file/stream. We made the required modification in a file (d3d11_helpers.c). We would like to copy this file to the mpv's source location (build64/packages/mpv-prefix/src/mpv/*) once mpv code is fetched from the git repository and then continue with the build process. can you please advise how could we achieve this. using your build methods?

Thanks,
Muthu

**Comment by NotTsunami** [comment]
Not the project creator, but I can tell you that you'll want to look into patches. Create a git patch for mpv, and have it run after mpv is cloned (look at other libraries that apply patches within this project to see how this done).

**Comment by shinchiro** [comment]
Basically, create your own patch and in `mpv.cmake` file, add the patch command like this:
https://github.com/shinchiro/mpv-winbuild-cmake/blob/7dd82a3b4d1118e1d3c6fa8c941878b76cda97a5/packages/libbs2b.cmake#L5

**Comment by ksmuthucv** [comment]
Thank you @shinchiro and @NotTsunami. Your help is really appreciated.
