### ISSUE TITLE
MPV doesn't start when using Vulkan api

### ISSUE THREAD

**Issue by XZTence** [shinchiro/mpv-winbuild-cmake#335]
I recently updated mpv to the newest build and now when I try to start mpv using the vulkan gpu api it tries to start then shuts down. doesn't happen with other api. my previous build I used which worked fine, was from 29 August last year. tried other recent builds and all have the same problem.

**Comment by shinchiro** [comment]
Better ask in https://github.com/mpv-player/mpv/issues
