### ISSUE TITLE
Provide an actual setup (msi or exe)

### ISSUE THREAD

**Issue by RealDolos** [shinchiro/mpv-winbuild-cmake#34]
Because users like click-click-done stuff
As it happens, I prepared something that might just work even when cross-compiling, based on nsis.
https://github.com/RealDolos/mpv-setup

If there is interest, just take it, or tell me and I will polish it and try to integrate it into the build scripts and make a PR out of it.

**Comment by shinchiro** [comment]
It's not bad idea but bundling it in exe or msi will lose the portability.

Having a installer which will download latest 7z package from sourceforge and do setup stuff afterward is more appropriate to me

**Comment by RealDolos** [comment]
huh? What portability? You'd release the NSIS setup.exe along with the .7z...
That way, lazy people (myself included tbh) and the not-so-savvy can download the installer, double-click, click, click, done, while the people preferring to extract an archive wherever can still do just that.

Of course, you could make the installer actually a stub that downloads the 7z, but that's really a hassle as you need to figure out a way to point it to the latest release, teach it to extract 7z even if the user does not have 7zip installed, deal with pesky firewalls claiming your installer is a botnet because it tries to internet, etc, the works. So the easy route is just to make a 7z and an exe installer and upload both.

**Comment by shinchiro** [comment]
> ..but that's really a hassle as you need to figure out a way to point it to the latest release, teach it to extract 7z even if the user does not have 7zip installed..

Well, I already did it though...
https://github.com/shinchiro/mpv-packaging/blob/master/mpv-root/installer/updater.ps1

> So the easy route is just to make a 7z and an exe installer and upload both.

I've shit upload speed so I hate uploading same thing for every week.

**Comment by RealDolos** [comment]
fair enough, tho a powershell file is something a regular user will hate

**Comment by shinchiro** [comment]
Closing as I provided a bootstrapper now which did the job
