### ISSUE TITLE
Direct3D 11 SDK

### ISSUE THREAD

**Issue by Obegg** [shinchiro/mpv-winbuild-cmake#342]
I'm trying to use ```vo=gpu-next``` and```gpu-debug``` with ```gpu-api=d3d11``` and I get this error:
```
[   1.814][f][vo/gpu-next/d3d11] Failed to create Direct3D 11 device: The application requested an operation that depends on an SDK component that is missing or mismatched. (0x887a002d)
```

Created an issue on mpv github
https://github.com/mpv-player/mpv/issues/11512

But I guess it can only be done on [mpv-winbuild-cmake](https://github.com/shinchiro/mpv-winbuild-cmake)

**Comment by shinchiro** [comment]
Most probably, the function it requested not available in current mingw headers. So nothing can do about it
