### ISSUE TITLE
[Question] Nightly builds launch slower than releases. Is this intentional?

### ISSUE THREAD

**Issue by NotMithical** [shinchiro/mpv-winbuild-cmake#343]
Latest release of MPV launches in less than half a second while nightly builds take 4-5 seconds. I have tested across multiple releases and older nightly builds. The only difference I am aware of is that cplayer, libmpv-shared, and plain-gl are listed as enabled in the release version's log when I launch it but not in the nightly build's. My questions are, is this what would be causing slower launching? And if so, what is the purpose of this omission?

**Comment by hooke007** [comment]
Cannot reproduce.
I think you should post the issue to mpv.

> cplayer libmpv-shared ... not in the nightly build's

These are enabled in nightly builds.

**Comment by NotMithical** [comment]
> I think you should post the issue to mpv.

I'll do that, thanks for checking.

**Comment by NotMithical** [comment]
Just attempted to reproduce this issue so I could get the log files again and it works fine now. Must have been an issue on my end. Strange since this has happened consistently between reboots and updates but oh well.
