### ISSUE TITLE
libpng and libdvdread fail to buil on cygwin

### ISSUE THREAD

**Issue by nshtg** [shinchiro/mpv-winbuild-cmake#35]
Hello,

sometime in the last two days the builds started to fail for me on cygwin (x86_64). Before they always worked. The problems with libass and the missing d3d11_3.h files were fixed by you already, but I encounter new errors that prevent a successful build:

libpng: https://gist.githubusercontent.com/anonymous/4ea0641835e960cd9226c93d84cc16d2/raw/281306a2b72be0ba65e0c6a1139e3a5a2fb29ff7/libpng-install-*.log
libdvdread: https://gist.githubusercontent.com/anonymous/4ea0641835e960cd9226c93d84cc16d2/raw/281306a2b72be0ba65e0c6a1139e3a5a2fb29ff7/libdvdread-configure-*.log

Greetings and thanks for your work!

**Comment by nshtg** [comment]
Allright I figured it out, seems like the autobuild.sh didn't run ```ninja gcc``` and that made the build fail at this late stage.

**Comment by shinchiro** [comment]
Does compiling angle on cywgin ever work? Last time I tested on msys2, it gives segfault with gcc 7.1. I don't if it gets better on gcc 7.2

**Comment by nshtg** [comment]
Yes it works fine using your scripts. But its cygwin I dont use msys2.
