### ISSUE TITLE
request deletion

### ISSUE THREAD

**Issue by suger520HT** [shinchiro/mpv-winbuild-cmake#355]

**Comment by hooke007** [comment]
Here is not the issue tracker of yt-dlp.

**Comment by suger520HT** [comment]
大佬帮忙反馈一个MPV的BUG问题&nbsp;在230507版本中配合yt-dlp解析youtube直播是视频分片不是完整的直播




▄︻┻═┳一
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shinchiro/mpv-winbuild-cmake"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月8日(星期一) 中午12:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shinchiro/mpv-winbuild-cmake] 230507 BUG (Issue #355)





 
Here is not the issue tracker of yt-dlp.
