### ISSUE TITLE
Issue with detecting formats the last two weekends

### ISSUE THREAD

**Issue by kungfubeaner** [shinchiro/mpv-winbuild-cmake#358]
MPV for windows from sourceforge (MPV v3) no longer detects available formats using yt-dlp + quality menu user script.   The lastest one that works is the one from 4-30-2023.   The last two releases do not detect formats for Chaturbate urls but works fine on youtube.  Excuse my English it is not my first language.  Also embarrassing to report but someone has to notify about the bug.  It doesn't seem to be a bug with either yt-dlp or quality menu user script since the MPV v3 released on04/30/2023 works just fine.

**Comment by shinchiro** [comment]
You should report on mpv github tracker. Btw, there's issue similar as this, https://github.com/mpv-player/mpv/issues/11674

**Comment by ZaquL** [comment]
Porn from chaturbate will work now after https://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=954d16fa3f09a04c7917a1c69a5c3e283554cb1d
