### ISSUE TITLE
Unicode characters in m3u8 files

### ISSUE THREAD

**Issue by kungfubeaner** [shinchiro/mpv-winbuild-cmake#360]
MPV on windows can play filenames with unicode characters just fine but when opening files inside a playlist it fails to play.  Example: 
X-Files has an episode named:  Folie à Deux.   The a with the accent on top causes it not to be able to play from a playlist file.

**Comment by shinchiro** [comment]
You should report on mpv github tracker. Btw, there's issue similar as this, https://github.com/mpv-player/mpv/issues/11674

**Comment by ZaquL** [comment]
Fixed in http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=954d16fa3f09a04c7917a1c69a5c3e283554cb1d that per RFC parses Content-Type.

**Comment by Traneptora** [comment]
Completely unrelated issue, stop posting garbage.

**Comment by garoto** [comment]
It's ValZapod's alt acc, but the unhinged behavior is exactly the same.
