### ISSUE TITLE
How to build with the d3dcompiler_43.dll and other files?

### ISSUE THREAD

**Issue by T-10001** [shinchiro/mpv-winbuild-cmake#37]
The builds on the https://sourceforge.net/projects/mpv-player-windows/files/64bit/ website have the other files such as `d3dcompiler_43.dll`, `updater.bat` and `installer` folder.

When I build I only get the `doc` folder, `mpv.exe` and `mpv.com`. How to get the other files? Are those files needed for something?

**Comment by onomatopellan** [comment]
https://github.com/shinchiro/mpv-packaging

d3dcompiler_43.dll is already installed if you did run at some time the DirectX End-User Runtime Web Installer.

**Comment by shinchiro** [comment]
Or run command:
```scripts/autobuild.sh 64 <path_to_build_folder>```

and you will get everything bundled inside 7z archives at the end
