### ISSUE TITLE
Add libaom-av1

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [shinchiro/mpv-winbuild-cmake#379]
to support https://github.com/mpv-player/mpv/pull/11495

https://trac.ffmpeg.org/wiki/Encode/AV1

**Comment by hooke007** [comment]
It has been supported(https://github.com/shinchiro/mpv-winbuild-cmake/issues/338) by rav1e or your hardware encoder.

https://mpv.io/manual/master/#options-screenshot-avif-encoder
