### ISSUE TITLE
vf_libplacebo is missing in the current build

### ISSUE THREAD

**Issue by hooke007** [shinchiro/mpv-winbuild-cmake#382]
It seems to have a long time.
Have no idea but it was in previous builds.

The last build which has vf_libplacebo https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230620

**Comment by hooke007** [comment]
It doesn't make sense.
shin's ffmpeg build do not have this filter

**Comment by hooke007** [comment]
use `mpv --vf=help` instead
it is not linked in mpv

**Comment by shinchiro** [comment]
Even explicitly enable libplacebo when building also gave same result. So probably there's change in upstream

**Comment by hooke007** [comment]
Not our issue.
