### ISSUE TITLE
subtitles not loading properly

### ISSUE THREAD

**Issue by akn19** [shinchiro/mpv-winbuild-cmake#384]
if video has 1 subtitle, it will not load. if the video has 2 subtitles, second subtitle will be loaded.

![image](https://github.com/shinchiro/mpv-winbuild-cmake/assets/86169232/5532c902-ede9-4c57-9a2f-537fbf93919c)

![image](https://github.com/shinchiro/mpv-winbuild-cmake/assets/86169232/e1931bad-2233-4529-81b1-c5e0cc3f2001)

**Comment by zhongfly** [comment]
report to mpv,not here.
https://github.com/mpv-player/mpv/issues

**Comment by akn19** [comment]
oh ok
