### ISSUE TITLE
Any plans for mpv 0.36.0 release?  

### ISSUE THREAD

**Issue by Raza-0007** [shinchiro/mpv-winbuild-cmake#387]
@shinchiro, [mpv version 0.36.0](https://github.com/mpv-player/mpv/releases/tag/v0.36.0)  was release on 2023-7-23. I noticed that it is not available on either your Sourceforge repository or on GitHub. Will you be posting a release soon or is there a reason for not compiling mpv 0.36.0?

Thanks,

~Raza

**Comment by zhongfly** [comment]
If you want to use latest mpv, just use the latest build.It already contains the 0.36.0 update.

**Comment by Raza-0007** [comment]
@zhongfly, I did download the 20230726 release from @shinchiro that has mpv 0.36.0, but I prefer to use release candidates over daily builds just for stability. That is why I asked. I will be upgrading from the 0.35.1 release.

**Comment by zhongfly** [comment]
Release do not means stable!

https://github.com/mpv-player/mpv/blob/master/DOCS/release-policy.md
> The goal of releases is to provide Linux distributions with something to package. If you want the newest features, just use the master branch. We try our best to keep it deployable at all times.

The latest build will always have newest fix and improvement.If you find a bug, report it to mpv's developers and then try an older build.
Honestly, the mpv has always been stable if you're not going to use the new features that have been added recently.

**Comment by Raza-0007** [comment]
@zhongfly, I agree with everything you are saying. But in daily builds, sometimes a code is added in one build and then later removed in another build, and if you happen to set a custom option based on the added code, mpv might misbehave when that code is pulled and you were not aware of its removal.  

I usually choose the release builds as the code is fixed till that point in time, and I do not mind waiting for a few months in between upgrades.

**Comment by shinchiro** [comment]
For release build, I need to trigger the build process manually which I'm too lazy. Atm, I trigger building the release version. Should be finished compile later if no problem occur
