### ISSUE TITLE
can we get a 0.36 build?

### ISSUE THREAD

**Issue by gh-log** [shinchiro/mpv-winbuild-cmake#388]

**Comment by gh-log** [comment]
was expecting 2023 07 23 build to be 0.36 but mpv.exe keeps showing 0.35.

mpv-x86_64-v3-20230723-git-ca4192e
0.35

**Comment by gh-log** [comment]
mpv-x86_64-v3-20230723-git-ca4192e
0.35

**Comment by zhongfly** [comment]
The commit (https://github.com/mpv-player/mpv/commit/60a263246e03d23c894ae0ef6bbfa29a5f1855dc) that changed version commited on Jul 23 17:10(UTC).
mpv-x86_64-v3-20230723-git-ca4192e is released on Jul 23 1:37(UTC).
So, would you be willing to lend us your time machine?

**Comment by gh-log** [comment]
funny
just wondering when 0.36 would be compiled by you

**Comment by zhongfly** [comment]
> when 0.36 would be compiled

https://github.com/shinchiro/mpv-winbuild-cmake/issues/387#issuecomment-1653358761
It should have been there a few days ago, but it looks like that build didn't work out.

**Comment by gh-log** [comment]
is it a weekly thing?

**Comment by zhongfly** [comment]
> is it a weekly thing?

no,that comment have said "need to trigger the build process manually",so please waitting for shinchiro trigger it again.

**Comment by Raza-0007** [comment]
It appears @shinchiro has been having some issues compiling 0.36.0 release version. Hopefully it will be sorted out soon. As a stopgap measure I have been using his [2023/07/26 release ](https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230726), it has mpv 0.36 in it. Code-wise it should be almost identical to the official 0.36.0 that was released on the 23rd.

I might even stick to this 2023/07/26 release, as I have read that they had to downgrade the libplacebo version in the official release from 6.292.0 back to 5.264.1, just for the linux distributions. Some issue with it or something. I use gpu-next, so libplacebo is very important for me.

**Comment by zhongfly** [comment]
> they had to downgrade the libplacebo version in the official release from 6.292.0 back to 5.264.1, just for the linux distributions. 

I'd like to know which commit or pr requires that mpv can only be built with libplacebo 5.264.1?
In shinchiro's toolchain, mpv has always been built with libplacebo's git master, not with its release.

If you are talking about pr #11952 ,they are discussing the minimal version of libplacebo, not the fact that only a certain version can be used.

**Comment by Raza-0007** [comment]
@zhongfly, I don't actually understand what you mean. 

I read on the mpv page under some issue that they (the mpv release team) downgraded the libplecebo version in the 0.36.0 release version for linux distributions packages. I cannot confirm if that happened or not. However, the libplacebo version is the latest in the development daily builds.

**Comment by zhongfly** [comment]
> I read on the mpv page under some issue that they (the mpv release team) downgraded the libplecebo version in the 0.36.0 release version for linux distributions packages. 

You may have misunderstood what minimum version means.
Since libplacebo v6 on linux has not been released yet, they don't want to mpv must be build with libplacebo >= 6.292.0.

Simply put, someone just want to be able to build mpv with libplacebo >= v5 , not build mpv with libplacebo == v5. The mpv team is just trying to raise the minimum version, there is no restriction on the maximum version.

**Comment by Raza-0007** [comment]
>Since libplacebo v6 on linux has not been released yet, they don't want to mpv must be build with libplacebo >= 6.292.0.

That might be it. I am trying to find the discussion where I read it, but have not found it yet. I was not paying too much intention as I do not use linux, but I made a mental note of it. I might have misunderstood what they are talking about. 

Thanks for the clarification.

**Comment by shinchiro** [comment]
0.36 release was up on sourceforge. This should be done earlier but sourceforge was acting up last week.

**Comment by gh-log** [comment]
Thanks for 0.36 release.
