### ISSUE TITLE
Newest Vulkan fails to compile due to the new? mock ICD

### ISSUE THREAD

**Issue by DeadSix27** [shinchiro/mpv-winbuild-cmake#39]
Not sure if that is needed for mpv, probably not, ICD is needed on the system playing back using vulkan right? Not during compiling.

Anyway, disabling it via the newly added switch `-DBUILD_ICD=OFF` fixes the build.

EDIT: Made a PR: https://github.com/shinchiro/mpv-winbuild-cmake/pull/40

**Comment by shinchiro** [comment]
Yeah, we only need the loader
