### ISSUE TITLE
Windows Dark Theme Support

### ISSUE THREAD

**Issue by mortyobnoxious** [shinchiro/mpv-winbuild-cmake#39]
Hi, this is when window is active:
![explorer_efLg4QZFl3](https://user-images.githubusercontent.com/42044258/63857797-02805200-c9ad-11e9-913b-64348645016d.png)

This is when it's inactive:
![explorer_sUHSx6oipy](https://user-images.githubusercontent.com/42044258/63857827-0e6c1400-c9ad-11e9-994a-505b319a2542.png)

Top bar of the File Explorer is dark when window is inactive.

But with MPV, it's white when window is inactive(not focused).
![mpv_Urt1y7ZG5G](https://user-images.githubusercontent.com/42044258/63858027-728ed800-c9ad-11e9-83ed-b6236f56b0a0.png)

Could you please add support for this.

**Comment by myfreeer** [comment]
Maybe better to post this to https://github.com/mpv-player/mpv

**Comment by mortyobnoxious** [comment]
@myfreeer submitted there. thank you.
