### ISSUE TITLE
build docker run failed

### ISSUE THREAD

**Issue by eko5624** [shinchiro/mpv-winbuild-cmake#393]
Your building Archlinux docker workflow runs failed, could you fix it?
https://github.com/shinchiro/archlinux-docker/actions/runs/5829822914

**Comment by shinchiro** [comment]
I dont know whats the problem but [official archlinux docker](https://hub.docker.com/_/archlinux) also has problem building docker daily

**Comment by eko5624** [comment]
https://gitlab.archlinux.org/archlinux/archlinux-docker/-/issues/99
They haven't fixed it yet.

**Comment by shinchiro** [comment]
I've fixed it with https://github.com/shinchiro/archlinux-docker/commit/70ceb293af030856e086b18d57a6fa5e7bc15486

**Comment by eko5624** [comment]
Thanks!

**Comment by eko5624** [comment]
I try to build archlinux docker, but always failed. Can you give me some help?
```
Error: buildx failed with: ERROR: failed to solve: failed to push ghcr.io/eko5624/archlinux:latest: unexpected status from POST request to https://ghcr.io/v2/eko5624/archlinux/blobs/uploads/: 403 Forbidden
```
https://github.com/eko5624/archlinux-docker/actions/runs/5916874194/job/16044622699

**Comment by zhongfly** [comment]
> 403 Forbidden

Looklike permisson issue.
Maybe you should give github action the 'package: write' permisson

https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

**Comment by eko5624** [comment]
Like this?
https://github.com/eko5624/archlinux-docker/blob/master/.github/workflows/main.yml#L17
Didn't work either.  And my settings seem not wrong , don't why.
<img width="820" alt="0" src="https://github.com/shinchiro/mpv-winbuild-cmake/assets/84926938/0987e258-8143-4f56-9d0e-3ad3b086429c">
<img width="852" alt="1" src="https://github.com/shinchiro/mpv-winbuild-cmake/assets/84926938/8a449c8a-4489-47e5-b575-25da4d5b6f00">

**Comment by eko5624** [comment]
> > 403 Forbidden
> 
> Looklike permisson issue. Maybe you should give github action the 'package: write' permisson
> 
> https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

Thanks. Following your link, I figure it out now.
