### ISSUE TITLE
Using openssl instead of mbedtls for x86-64-v3 builds

### ISSUE THREAD

**Issue by ghost** [shinchiro/mpv-winbuild-cmake#398]

**Comment by zhongfly** [comment]
https://github.com/shinchiro/mpv-winbuild-cmake/issues/200#issuecomment-1112330487
> As someone mentioned in https://github.com/shinchiro/mpv-winbuild-cmake/issues/192, ffmpeg need update itself to support newer libressl.

**Comment by shinchiro** [comment]
More fat = more headache to maintain. mbedtls is lightweight and it never gives me compiling issue. That's good enough
