### ISSUE TITLE
Create tar releases.

### ISSUE THREAD

**Issue by ghost** [shinchiro/mpv-winbuild-cmake#400]
There is no need to strictly use 7zip, in fact Windows now ships out BSDtar, i also need tar releases for a project i am working on, i would rather not download a one time use executable to unzip the contents. 

Would it be possible?

Thanks
-Movrsi

**Comment by shinchiro** [comment]
Current archive release use LZMA2 compression which bring the size of binaries as small as possible. I heard that windows 11 will support LZMA2 decompression. Not sure if already there or not. But I will stay with current 7z archive format

**Comment by ghost** [comment]
> Current archive release use LZMA2 compression which bring the size of binaries as small as possible. I heard that windows 11 will support LZMA2 decompression. Not sure if already there or not. But I will stay with current 7z archive format

yeah i get 7zip is a bit better in terms of compression; however, it makes attempting to update mpv itself kind of cumbersome in terms of an updating script. its a trade off in terms of size yes, however the script im working on is intended to be fired weekly from the task scheduler, i know its not an issue in terms of downloading the standalone 7zip executable each time (as i dont wish to force a requirement to the user) however, that is assuming the 7zip site didn't get compromised and that executable is what it says it is. Mostly for me its a security concern for the users, as the script im working on verifies files from a hash.

Understandable from your point of view, however providing `tar` `zip` and `7zip` choices can make it so users can decide on which benefits their use case.

**Comment by shinchiro** [comment]
>  i know its not an issue in terms of downloading the standalone 7zip executable each time

You dont need to download the 7zr everytime to update. My updater scripts only download `7zr` once and never download it again if it already exist in the folder
