### ISSUE TITLE
[question] build libplacebo with glslang instead of shaderc

### ISSUE THREAD

**Issue by mitzsch** [shinchiro/mpv-winbuild-cmake#401]
hi! 

I just got a small question. Is it possible to get this to work? I am currently trying to build libplacebo with glslang instead of shaderc for testing purposes but it's not working. I added `-Dshaderc=disabled -Dglslang=enabled` to the libplacebo.cmake but every time I try to compile it I get a building error saying `../libplacebo/src/glsl/meson.build:34:16: ERROR: C++ static library 'SPIRV' not found`. Which SPIRV version is meant? The spirv-cross one is already built... I also thought glslang is also compiled alongside those spirv packages? 

Thanks!

**Comment by shinchiro** [comment]
The `spirv` library is not directly compiled

**Comment by mitzsch** [comment]
okay, but is it possible to enable it or would this involve creating a new *.cmake?
