### ISSUE TITLE
Wheel up/down and wheel left/right are inverted

### ISSUE THREAD

**Issue by csb99** [shinchiro/mpv-winbuild-cmake#408]
(I'm using a translator so sorry for any errors) I'm using the latest 64bit release (from here: https://sourceforge.net/projects/mpv-player-windows/files/64bit/) and when I try to use these commands with both mouse and touchpad I noticed that they are inverted

**Comment by zhongfly** [comment]
Not related to this repo, here is not mpv issue tracker.

But I can answer your question: please see this commit https://github.com/mpv-player/mpv/commit/981a9372ff0034178a986f8bc1ec1ad6b973bb6c

**Comment by csb99** [comment]
This is where I got to with the link in the support section on sourceforge so I thought it was ok to write here, anyway I just care that the commands work as before and if I am in the wrong place here I will ask elsewhere

**Comment by zhongfly** [comment]
> This is where I got to with the link in the support section on sourceforge so I thought it was ok to write here, anyway I just care that the commands work as before and if I am in the wrong place here I will ask elsewhere

Read mpv's manual : https://mpv.io/manual/master/ ,you can customize the key bindings by using `input.conf`.

If you have any question about using mpv, ask in https://github.com/mpv-player/mpv/issues
This repo is something to building Windows binaries of mpv.

**Comment by csb99** [comment]
Thanks, now I fixed it, somehow being in the wrong place helped anyway
