### ISSUE TITLE
libplacebo fails to build

### ISSUE THREAD

**Issue by mitzsch** [shinchiro/mpv-winbuild-cmake#411]
With the current upstream version of libplacebo containing this commit => https://github.com/haasn/libplacebo/commit/9b9987cc12b3513ecd48239fdfdc4220bc61260f

...building fails. :/
`../libplacebo/src/meson.build:226:17: ERROR: Include dir ../3rdparty/fast_float/include does not exist.`

**Comment by zhongfly** [comment]
need to add a new package `fast_float` like `glad`
