### ISSUE TITLE
Problem with streaming

### ISSUE THREAD

**Issue by dokax** [shinchiro/mpv-winbuild-cmake#414]
https://github.com/yt-dlp/yt-dlp/issues/3950

When using yt-dlp through mpv, sometimes instead of loading the entire stream as normal it will load just the first hls chunk or a random hls chunk in the middle of the video, making seeking impossible. It will continue to load from that point forward, but to seek 15m ahead for example, you have to wait for it to cache 15m worth of video. This doesn't happen everywhere but it does seem to happen across multiple sites, Pornhub being the one that seems to do it the most. It does not seem to do this across all sites, for example it never happens on YouTube. If I close the mpv window and try to open the same URL, it will usually eventually work after a number of tries. This behavior has been present for me for probably multiple years now.

**Comment by Andarwinux** [comment]
You should ask at https://github.com/mpv-player/mpv, not here.
