### ISSUE TITLE
why using "disable-stack-smash-protection" and "D_FORTIFY_SOURCE=0"  for package flac ?

### ISSUE THREAD

**Issue by trclst** [shinchiro/mpv-winbuild-cmake#433]
hello,

i want to understand why the following settings used for [flac package](https://github.com/shinchiro/mpv-winbuild-cmake/blob/master/packages/flac.cmake):

[disable-stack-smash-protection](https://github.com/shinchiro/mpv-winbuild-cmake/blob/7c36398516237fcca98a06c46021f3412df0213a/packages/flac.cmake#L17)
[D_FORTIFY_SOURCE=0](https://github.com/shinchiro/mpv-winbuild-cmake/blob/7c36398516237fcca98a06c46021f3412df0213a/packages/flac.cmake#L18C15-L18C37)

at first sight as far as i can tell, these settings could worsen security.
is there an explanation for the use of supposedly unsafe settings?

thank you !

**Comment by Andarwinux** [comment]
https://github.com/xiph/flac/issues/346
