### ISSUE TITLE
Deinterlace not working in Clang Build

### ISSUE THREAD

**Issue by CharlesMengCA** [shinchiro/mpv-winbuild-cmake#436]
We may need to stay on gcc build for a while.

I don't see noticeable performance gain using Clang build. 

```
 (+) Video --vid=1 (*) (vp9 1920x1080 25.000fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
Using hardware decoding (nvdec).
AO: [wasapi] 48000Hz stereo 2ch float
VO: [gpu-next] 1920x1080 cuda[nv12]
AV: 00:00:02 / 00:04:07 (1%) A-V:  0.000
[lavfi] filter 'yadif_cuda' not found or failed to allocate
[deint] Creating filter 'yadif_cuda' failed.
[deint] creating deinterlacer failed
[autoconvert] HW-downloading from cuda
AV: 00:00:02 / 00:04:07 (1%) A-V:  0.000
VO: [gpu-next] 1920x1080 yuv420p
AV: 00:00:04 / 00:04:07 (2%) A-V:  0.000
```

**Comment by Andarwinux** [comment]
Should be fixed by https://github.com/shinchiro/mpv-winbuild-cmake/pull/426

**Comment by NotTsunami** [comment]
> We may need to stay on gcc build for a while.

It hasn't even been that long since clang support was merged! Give it a little window to stabilize.

**Comment by Andarwinux** [comment]
All known issues should have been resolved by now. Please feel free to report any clang build problems.
