### ISSUE TITLE
build fail WSL

### ISSUE THREAD

**Issue by dijkstrah** [shinchiro/mpv-winbuild-cmake#440]
First time attempt to build this on Windows 11 WSL: Linux 5.15.90.1-microsoft-standard-WSL2. 

Please see attached for actual messages. 

[cmakeerror.log](https://github.com/shinchiro/mpv-winbuild-cmake/files/12702293/cmakeerror.log)

**Comment by Andarwinux** [comment]
Try deleting cmake/* and CMakeCache.txt and then re-running cmake

**Comment by dijkstrah** [comment]
Did that and find the result in the attached log file. Spinning up a VM, as I think the WSL build option, at least on my instance, is broken. 

[cmake_error.log](https://github.com/shinchiro/mpv-winbuild-cmake/files/12704528/cmake_error.log)

**Comment by Andarwinux** [comment]
can't find file to patch at input line 18
can't find file to patch at input line 72
https://github.com/shinchiro/mpv-winbuild-cmake/blob/master/cmake/download_externalproject.cmake#L19
It looks like you're having problems with your internet connection.

**Comment by dijkstrah** [comment]
My internet connection is working just fine. Anything you suggest I should try to verify?

**Comment by dijkstrah** [comment]
Installed arch in a vm, followed the instructions, did not result in success. My internet connection is just fine.

[cmake_error.log](https://github.com/shinchiro/mpv-winbuild-cmake/files/12705946/cmake_error.log)

**Comment by Andarwinux** [comment]
curl -sL https://gitlab.kitware.com/cmake/cmake/-/archive/release/cmake-release.tar.gz
curl -sLO https://gitlab.kitware.com/cmake/cmake/-/raw/v3.26.4/Modules/ExternalProject.cmake

**Comment by dijkstrah** [comment]
The first curl command fails. The second one works fine with this message

* Failure writing output to destination.

Pasting the url in the browser works fine. wget works also fine. Adding O to the -sL in the first command also results in downloaded file. The curl command in the cmake file 

COMMAND curl -sL https://gitlab.kitware.com/cmake/cmake/-/archive/release/cmake-release.tar.gz?path=Modules/ExternalProject -o modules.tar.gz

also works fine by itself.

**Comment by Andarwinux** [comment]
That's very strange. I can't reproduce this on Arch and Ubuntu-Preview WSL.

Maybe delete the entire build64 directory and try again?

**Comment by shinchiro** [comment]
Run with `sudo` to have write permission

**Comment by dijkstrah** [comment]
Sudo helped a lot on the arch vm. It got the cmake portion done. Why would we need elevated rights though? 

Sudo did nothing for WSL, I am not going to touch that anytime soon. 

On arch, it now fails in the ninja gcc step:

[50/68] Performing install step for 'rustup'
FAILED: toolchain/rustup-prefix/src/rustup-stamp/rustup-install /home/unpo/mpv-winbuild-cmake/build64/toolchain/rustup-prefix/src/rustup-stamp/rustup-install
cd /home/unpo/mpv-winbuild-cmake/build64/toolchain/rustup-prefix/src/rustup-build && /usr/bin/cmake -P /home/unpo/mpv-winbuild-cmake/build64/toolchain/rustup-prefix/src/rustup-stamp/rustup-install-.cmake && /usr/bin/cmake -E touch /home/unpo/mpv-winbuild-cmake/build64/toolchain/rustup-prefix/src/rustup-stamp/rustup-install
CMake Error at /home/unpo/mpv-winbuild-cmake/build64/toolchain/rustup-prefix/src/rustup-stamp/rustup-install-.cmake:49 (message):
  Command failed: 101

   '/home/unpo/mpv-winbuild-cmake/build64/exec' 'cargo' 'install' 'cargo-c' '--profile=release-strip' '--features=vendored-openssl'

  See also

    /home/unpo/mpv-winbuild-cmake/build64/toolchain/rustup-prefix/src/rustup-stamp/rustup-install-*.log


[51/68] Performing build step for 'gcc'
FAILED: toolchain/gcc-prefix/src/gcc-stamp/gcc-build /home/unpo/mpv-winbuild-cmake/build64/toolchain/gcc-prefix/src/gcc-stamp/gcc-build
cd /home/unpo/mpv-winbuild-cmake/build64/toolchain/gcc-prefix/src/gcc-build && /usr/bin/cmake -P /home/unpo/mpv-winbuild-cmake/build64/toolchain/gcc-prefix/src/gcc-stamp/gcc-build-.cmake && /usr/bin/cmake -E touch /home/unpo/mpv-winbuild-cmake/build64/toolchain/gcc-prefix/src/gcc-stamp/gcc-build
CMake Error at /home/unpo/mpv-winbuild-cmake/build64/toolchain/gcc-prefix/src/gcc-stamp/gcc-build-.cmake:49 (message):
  Command failed: 2

   'make' '-j4' 'all-gcc'

  See also

    /home/unpo/mpv-winbuild-cmake/build64/toolchain/gcc-prefix/src/gcc-stamp/gcc-build-*.log


ninja: build stopped: subcommand failed.

**Comment by Andarwinux** [comment]
Send `gcc-build-*.log` and `rustup-install-*.log`

**Comment by dijkstrah** [comment]
On the arch vm I have now succesfully passed the gcc stage. Turns out tmpfs was not big enough, giving disk-full errors.

In the mpv stage I now encounter this one: 

FAILED: packages/libmodplug-prefix/src/libmodplug-stamp/libmodplug-patch /home/unpo/mpv-winbuild-cmake/build64/packages/libmodplug-prefix/src/libmodplug-stamp/libmodplug-patch
cd /home/unpo/mpv-winbuild-cmake/build64/packages/libmodplug-prefix/src/libmodplug && /home/unpo/mpv-winbuild-cmake/build64/exec git am --3way "/home/unpo/mpv-winbuild-cmake/packages/libmodplug-*.patch" && /usr/bin/cmake -E touch /home/unpo/mpv-winbuild-cmake/build64/packages/libmodplug-prefix/src/libmodplug-stamp/libmodplug-patch
Committer identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@archi.(none)')

and these:

[11/688] Performing build step for 'gmp'
ninja: build stopped: subcommand failed.

After restarting the build it fails at a different step.

**Comment by Andarwinux** [comment]
Feel free to set a username and email

**Comment by dijkstrah** [comment]
I did and it didn't make a difference. It fails first with "gmp" step.

**Comment by Andarwinux** [comment]
`ninja gmp-removeprefix && ninja download && ninja mpv`

If the error still occurs, send `gmp-build-*.log`

**Comment by dijkstrah** [comment]
I am not sure what's going on. ninja mpv keeps failing, performing those individual steps with ninja <component> completes without errors. Are too many things happening at the same time? Any way to control this?

**Comment by Andarwinux** [comment]
`-DMAKEJOBS=1`

**Comment by Andarwinux** [comment]
You should limit wslconfig.processors, or increase wslconfig.memory

example:
```
[wsl2]
memory=16GB
processors=8
```

https://learn.microsoft.com/en-us/windows/wsl/wsl-config

I recommend 2GB per processor

**Comment by dijkstrah** [comment]
Allright, the arch linux build has completed without errors. Finally! 

As I stated before, the WSL one still cannot make it through the first step on my machine. I leave it at that.

**Comment by Andarwinux** [comment]
I don't know if you put the build directory inside WSL, but if you put it in the Windows directory, all sorts of weird problems are to be expected.

**Comment by dijkstrah** [comment]
I installed WSL standard Ubuntu, startup WSL with created user, git clone the repo into the home directory, create the build64 directory, "sudo cmake -DTARGET_ARCH=x86_64-w64-mingw32 -DGCC_ARCH=x86-64-v3 -G Ninja .." and then it bombs with the output in the log file as attached in the first post. I have reinstalled WSL just to check. Does the exact same thing again.
