### ISSUE TITLE
[RFC] Multi-platform support

### ISSUE THREAD

**Issue by Andarwinux** [shinchiro/mpv-winbuild-cmake#449]
Thanks to the cmake/ninja build system, this project has good scalability, and perhaps in the future support could be considered for the addition of Linux/macOS build target support, which would allow all three of mpv's major platforms to have easy access to the latest statically linked binaries. In the long run, this would advance vo_gpu-next to eventually replace vo_gpu, a goal for which the main resistance at the moment is dependency hell on various Linux distributions.

**Comment by shinchiro** [comment]
Disagree but you're free to fork & modify this repo for linux/mac compilation
