### ISSUE TITLE
mpv doesn't do anything

### ISSUE THREAD

**Issue by fizwack729** [shinchiro/mpv-winbuild-cmake#452]
Windows 10
Intel(R) Core(TM) i7 CPU       X 980  @ 3.33GHz, 3334 Mhz, 6 Core(s), 12 Logical Processor(s)
very old cpu, uptodate OS

Installed this
https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20230924-git-140d018.7z
doesn't do anything on command line
also the powershell script doesn't find youtube-dl or ytdl (neither of which work very well these days) or
ffmpeg, which has been recently updated, even tho the administrator command window has them in its path

**Comment by zhongfly** [comment]
https://github.com/shinchiro/mpv-winbuild-cmake/issues/445
issue duplicate

**Comment by shinchiro** [comment]
20231001 release should be working as usual
