### ISSUE TITLE
Remove/update opengl-hq configure script

### ISSUE THREAD

**Issue by ghost** [shinchiro/mpv-winbuild-cmake#453]
opengl-hq has been removed from newer mpv builds and is in general very outdated (the setting was deprecated ~6 years ago or so). It should either be updated to set profile=high-quality (and maybe gpu-next aswell as some high-quality settings depend on it?) or just be removed entirely.

**Comment by NotTsunami** [comment]
I agree, might be better to raise a ticket in the `mpv-packaging` repo instead though, since that's where that script lives: https://github.com/shinchiro/mpv-packaging/issues
