### ISSUE TITLE
High GPU on 2023-09-24 and 2023-10-01 64bit-v3

### ISSUE THREAD

**Issue by hsyong** [shinchiro/mpv-winbuild-cmake#457]
Before update, for 2023-09-17, GPU runs at 4% for a 720p video but after updating to 2023-09-24 64bit-v3 (and 2023-10-01 64bit-v3) the same video uses 15% GPU.  Other videos show high GPU as well. [Seen from Task Manager]

Setting in mpv.conf is hwdec=auto.

Device: Dell Inspiron 15 laptop (Core i5-1135G7), up-to-date Windows 11, Intel Iris Xe with latest driver (11/7/2023)

Thank you for your help.

**Comment by Andarwinux** [comment]
`profile=fast`

This is not a problem with mpv-winbuild-cmake, please complain directly [upstream](https://github.com/mpv-player/mpv/issues/new/choose).

**Comment by hsyong** [comment]
> `profile=fast`
> 
> This is not a problem with mpv-winbuild-cmake, please complain directly [upstream](https://github.com/mpv-player/mpv/issues/new/choose).

Thank you.

**Comment by Andarwinux** [comment]
If there are no further questions, please close this issue, thank you.
