### ISSUE TITLE
libmpv generates FLOAT_INVALID_OPERATION in Windows LoadLibrary API

### ISSUE THREAD

**Issue by BazzaCuda** [shinchiro/mpv-winbuild-cmake#458]
Hi.

I'm on Windows 10.

All builds up to and including the build released 2023/09/17 work fine.

All builds since that date have been 9mb larger and generate a Windows "Invalid Floating Point Operation" during LoadLibrary (standard Windows API call).

I have tried it with builds from https://sourceforge.net/projects/mpv-player-windows/files/libmpv/ and from https://github.com/zhongfly/mpv-winbuild/releases
All of these fail to load. The moment I revert to the build posted 2023/09/17, all is good.
EDIT: I have also just tried the v3 build from https://github.com/shinchiro/mpv-winbuild-cmake/releases
Same problem.

I have a project on Github (https://github.com/BazzaCuda/MinimalistMediaPlayerX/releases) which can be used to demonstrate this, if that would help at all.

Regards,
Baz.

**Comment by shinchiro** [comment]
gcc build: https://github.com/shinchiro/mpv-winbuild-cmake/suites/16765458467/artifacts/957412751

clang64 build: https://github.com/shinchiro/mpv-winbuild-cmake/suites/16804223217/artifacts/960791967

try these

**Comment by BazzaCuda** [comment]
> Not sure what compiler your program was built with, but since 09/24, libmpv built with clang x86_64-w64-mingw32 with ControlFlowGuard, there may be ABI incompatibilities.

Hi, Thanks for your replies.
I'm using Delphi 11.3. It makes a standard Windows API call to LoadLibrary in kernel32.dll, which returns the floating point error.

**Comment by BazzaCuda** [comment]
> I tested libmpv with [mpv.net](https://github.com/mpvnet-player/mpv.net) which is also based on libmpv (compiled with MSVC) and everything works fine, so it might be a problem with your Pascal toolchain, I heard that they have a [new backend](https://wiki.freepascal.org/LLVM) based on LLVM, maybe you can try it.

I'm using Delphi rather than Free Pascal. Unfortunately, they're not project-compatible.

**Comment by shinchiro** [comment]
Then you should test with libmpv 32bit since its not built with controlflowguard

**Comment by BazzaCuda** [comment]
> Then you should test with libmpv 32bit since its not built with controlflowguard

I create 64bit .exe binaries which load 64bit DLLs. It sounds (from what Andarwinux says) that I need to only use GCC-built versions of libmpv-2.dll, not the Clang ones. Where would I get these from, please?

**Comment by zhongfly** [comment]
> I create 64bit .exe binaries which load 64bit DLLs. It sounds (from what Andarwinux says) that I need to only use GCC-built versions of libmpv-2.dll, not the Clang ones. Where would I get these from, please?

you can use this repo to compile libmpv by yourself.

**Comment by BazzaCuda** [comment]
I'm not familiar with any of this but I'm willing to giving it a go.

Edit: Also, I can confirm that the latest GCC build (2023-10-02) from https://github.com/zhongfly/mpv-winbuild/releases works for me, so that's definitely what the issue is. Thanks!!

Would you be kind enough to explain (in idiot terms) how I can trigger a new Github Action please. On the https://github.com/zhongfly/mpv-winbuild/actions page, I can only seem to see what others, like zhongfly, have done with no options to do this myself. Thanks.

**Comment by BazzaCuda** [comment]
Thank you so much. I appreciate that. I'll give it go.

**Comment by BazzaCuda** [comment]
It worked! It built mpv first time as I'm sure you expected and I now have my own GCC 64-bit build of libmpv-2.dll which works with my application.
Thanks Andarwinux - Firstly, for correctly identifying what my problem was and then providing me with a solution so I can keep my project up to date with the latest MPV dev.

 I am deeply indebted to you.
