### ISSUE TITLE
[pkg-config] srt not found by ffmpeg

### ISSUE THREAD

**Issue by mitzsch** [shinchiro/mpv-winbuild-cmake#467]
When trying to compile mpv, ffmpeg fails: 
`ERROR: srt >= 1.3.0 not found using pkg-config`

Removing "--enable-libsrt" from the ffmpeg.cmake makes it compilable again.

-- Compiler used: gcc
-- Target toolchain to build: x86_64-w64-mingw32

**Comment by Andarwinux** [comment]
try 
`ninja {mbedtls,libsrt}-fullclean && ninja ffmpeg-removeprefix && ninja download && ninja update && ninja mpv`

**Comment by shinchiro** [comment]
Rebuild libsrt & libssh again

**Comment by mitzsch** [comment]
Thanks and sorry for not responding quickly...

I tried "ninja {mbedtls,libsrt}-fullclean && ninja ffmpeg-removeprefix && ninja download && ninja update && ninja mpv" but that did not help, I also started from scratch (two times by now) with the same result...

I don`t get it, maybe an update to the os (in my case arch) bricked it?

**Comment by Andarwinux** [comment]
Are you sure you are using the latest mpv-winbuild-cmake? Can you send ffmpeg-build/ffbuild/config.log?

**Comment by mitzsch** [comment]
Yes, should be up-to-date. 
I just ran this again: 
```
git clone https://github.com/shinchiro/mpv-winbuild-cmake.git
cmake -DTARGET_ARCH=x86_64-w64-mingw32 -DGCC_ARCH=x86-64-v3 -G Ninja -B build64
ninja gcc
ninja ffmpeg
```

Logs: I´m currently rebuilding again, I will drop the logs as soon as it fails.

**Comment by mitzsch** [comment]
Just failed again, attached the `mpv-winbuild-cmake/build64/packages/ffmpeg-prefix/src/ffmpeg-build/ffbuild/config.log`
[config.log](https://github.com/shinchiro/mpv-winbuild-cmake/files/12840303/config.log)

**Comment by Andarwinux** [comment]
It looks like https://github.com/shinchiro/mpv-winbuild-cmake/commit/8ae34590d33b6f6760df9d7d26838cfbba40388a caused libsrt to generate a wrong pkgconfig

**Comment by shinchiro** [comment]
What's content of your `srt.pc`

**Comment by Andarwinux** [comment]
```
prefix=/mpv-winbuild-cmake/build/install/x86_64-w64-mingw32
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: srt
Description: SRT library set
Version: 1.5.3
Libs: -L${libdir} -lsrt
Libs.private:  /mpv-winbuild-cmake/build/install/x86_64-w64-mingw32/bin/../lib/libmbedtls.a /mpv-winbuild-cmake/build/install/x86_64-w64-mingw32/bin/../lib/libmbedcrypto.a /mpv-winbuild-cmake/build/install/x86_64-w64-mingw32/bin/../lib/libmbedx509.a -lwsock32 -lbcrypt -lws2_32 -lc++ -lmingw32 -lunwind -lmoldname -lmingwex -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 -lunwind -lmoldname -lmingwex -lkernel32
Cflags: -I${includedir} -I${includedir}/srt
Requires.private:
```

**Comment by Andarwinux** [comment]
lld seems to accept absolute paths, but bfd does not.

**Comment by shinchiro** [comment]
That should not be issue since libsrt was always worked before

https://github.com/shinchiro/mpv-winbuild-cmake/blob/e5a2f4188b3d1627a840c008566c770c3b39a7b5/packages/libsrt.cmake#L16-L18
Either way, try add `-DMBEDTLS_PREFIX=${MINGW_INSTALL_PREFIX}` to CONFIGURE_COMMAND

**Comment by Andarwinux** [comment]
> That should not be issue since libsrt was always worked before

But changing these to -lmbedtls -lmbedcrypto -lmbedx509 did fix the problem for me.

> Either way, try add `-DMBEDTLS_PREFIX=${MINGW_INSTALL_PREFIX}` to CONFIGURE_COMMAND

From x86_64-w64-mingw32/bin/... /lib/ to x86_64-w64-mingw32/lib64/, then it still fails.

**Comment by mitzsch** [comment]
Applying https://github.com/shinchiro/mpv-winbuild-cmake/pull/468 also fixes it for me. Thanks! :)
