### ISSUE TITLE
ERROR: opus not found using pkg-config

### ISSUE THREAD

**Issue by krakow10** [shinchiro/mpv-winbuild-cmake#47]
Got this error in build64/packages/ffmpeg-prefix/src/ffmpeg-stamp/ffmpeg-configure-out.log when trying to compile on three separate Ubuntu 19.04 computers

**Comment by shinchiro** [comment]
Try adding this line `-DCMAKE_C_FLAGS='${CMAKE_C_FLAGS} -D_FORTIFY_SOURCE=0'` in opus.cmake like this pic and run `ninja opus` and `ninja ffmpeg` afterward.
![image](https://user-images.githubusercontent.com/9623615/66709064-e7b44200-ed8e-11e9-9226-c1a82603d8a0.png)

**Comment by krakow10** [comment]
That seems to have done the trick.  Thanks!
