### ISSUE TITLE
Tip: Upstream has dropped Windows 7 support

### ISSUE THREAD

**Issue by Andarwinux** [shinchiro/mpv-winbuild-cmake#475]
https://github.com/mpv-player/mpv/commit/66c3110a856f11c1fc68044e6ef426991911aa25

mpv has completely dropped support for Windows 7, so gcc builds will not run on Windows 7 either, this is not a problem with mpv-winbuild-cmake.

Please don't open any issue about Windows 7 not working repeatedly here, and please don't open any issue about Windows 7 not working at mpv-player/mpv, thanks.

**Comment by garoto** [comment]
Wow... fucking degenerates, hard deprecating Win7, the balls. But expected behavior for new-fangled-thing FOSS-style of Windows programmers.

**Comment by DOSforever** [comment]
Could you tell me which is the latest version that support Windows 7?
