### ISSUE TITLE
Updating mpv without youtube-dl?

### ISSUE THREAD

**Issue by NorioTomokawa** [shinchiro/mpv-winbuild-cmake#48]
I highly appreciate your speedy mpv builds. However, I have no use for youtube-dl.exe. I have tried a couple of ways to remove it, but it always comes back in the end when I run updater.bat.

I tried:

- Deleting youtube-dl.exe. The updater batch file says "youtube-dl not found" but proceeds to download youtube-dl anyway.

- Deleting the youtube-dl bits from the PowerShell script. This also doesn't work because the updater downloads a new copy of this PowerShell script with each update, and then proceeds to download youtube-dl.

Is there a way to update mpv without getting youtube-dl in the process? Thanks!

**Comment by shinchiro** [comment]
Maybe I should not forcing the script to download the youtube-dl when it doesn't even exist seems plausible solution

**Comment by shinchiro** [comment]
Fixed. In next release, the script will not download youtube-dl anymore if youtube-dl doesn't exist
