### ISSUE TITLE
Integrate binaries to https://github.com/mpv-player/mpv/releases

### ISSUE THREAD

**Issue by necros2k7** [shinchiro/mpv-winbuild-cmake#48]
if no migrate from SF to Github

**Comment by NotTsunami** [comment]
The releases on the mpv-player repository mainly point towards versions in source code, no binaries are provided for any platform. Given the nature and how configurable mpv is, there wouldn't be a build that fits everyone's use cases perfectly, which is assumably why it's left up to the user to either compile or choose from the list of semi-official builds [here](https://mpv.io/installation/). If you have an issue with SourceForge, once again, compile it yourself.
