### ISSUE TITLE
CMP0135 not available with cmake that comes with ubuntu 22.04

### ISSUE THREAD

**Issue by tari3x** [shinchiro/mpv-winbuild-cmake#483]
Ubuntu 22.04 has cmake 3.22.1. Trying to build with that results in tons of "cmake_policy GET given policy "CMP0135" which is not known to this version of CMake.". 

Would it be possible to provide instructions for building on ubuntu?

**Comment by Andarwinux** [comment]
~~https://github.com/shinchiro/mpv-winbuild-cmake/issues/274~~
~~Not sure why this fix isn't working.~~

https://github.com/shinchiro/mpv-winbuild-cmake/issues/327

**Comment by tari3x** [comment]
Ok, I got a newer cmake and I can run it successfully now. Thanks!
