### ISSUE TITLE
/usr/bin/ld: cannot find -lwinmm: No such file or directory

### ISSUE THREAD

**Issue by tari3x** [shinchiro/mpv-winbuild-cmake#488]
On Ubuntu 22.04. I think I installed all the packages mentioned in the readme, and it's not obvious what else I need.

**Comment by tari3x** [comment]
Oh, hold on, i do need to build gcc before building mpv, it won't just know to do it automatically.

**Comment by rorgoroth** [comment]
This is mentioned in the instructions contained in the README. 🙂
