### ISSUE TITLE
Unable to drop (URL)links if player is pinned to taskbar

### ISSUE THREAD

**Issue by dnmTX** [shinchiro/mpv-winbuild-cmake#5]
@shinchiro  as the title says and i'm not sure that the problem is coming from your build or it's the player itself. If it's the player,let me know and i'll open a issue there.Basically if i pin the player to the taskbar and try to drag and drop some link it wouldn't accept it,if i place a shortcut to the desktop it's all good,works fine.Let me know what you think and what to do next.Thank you. 👍 
Using your latest build
Windows 10 x64 Enterprise LTSB 1607

**Comment by shinchiro** [comment]
I dont think you can drag&open items to the pinned item in taskbar. Not mpv only but also applied to other apps like firefox, photos etc
