### ISSUE TITLE
`mpv-x86_64-v3-20231106-git-84de84b.7z` build doesn't work

### ISSUE THREAD

**Issue by Obegg** [shinchiro/mpv-winbuild-cmake#500]
`mpv-x86_64-v3-20231105-git-7480efa.7z` = No issues.
`mpv-x86_64-v3-20231106-git-84de84b.7z`  = `mpv.exe` have issues.
I tried to debug the issue by using the `log-file` command but mpv doesn't seem to create the file, so I can't debug it.
Weirdly enough when I open Task Manager I do see `mpv.exe`.

It's probably not an issue with `mpv-packaging` because nothing was changed [today](https://github.com/shinchiro/mpv-packaging/pulse/daily).
So my guess it's either [mpv daily changes](https://github.com/mpv-player/mpv/pulse/daily) or it's [mpv-winbuild-cmake daily changes](https://github.com/shinchiro/mpv-winbuild-cmake/pulse/daily).

**Comment by zhongfly** [comment]
try these build by order：
mpv-winbuild-cmake update: https://github.com/zhongfly/mpv-winbuild/actions/runs/6761476818
mpv update 1: https://github.com/zhongfly/mpv-winbuild/actions/runs/6762326856
mpv update 2: https://github.com/zhongfly/mpv-winbuild/actions/runs/6762893585

Is it not working from the first one?

**Comment by Jules-A** [comment]
I can reproduce, R5 3600 / 6700XT.

**Comment by Obegg** [comment]
It should be fixed by https://github.com/mpv-player/mpv/pull/12821
I will wait for tomorrow's build to see if it's fixed

**Comment by Andarwinux** [comment]
I've confirmed the fix with a local build, you can use zhongfly's build for now.

**Comment by Obegg** [comment]
So I will close this issue.
