### ISSUE TITLE
Issues with 84de84b builds not starting?

### ISSUE THREAD

**Issue by cascardian** [shinchiro/mpv-winbuild-cmake#502]
Tested on Coffee Lake, Kaby Lake and Ryzen 5 so far. All on Windows 11 23H2.

~~It's either https://github.com/shinchiro/mpv-winbuild-cmake/commit/178e6232b0ca308e92543f7af432d1afdbdd547a or https://github.com/shinchiro/mpv-winbuild-cmake/commit/81aca4fb23b8beb762bf4cdd1c420f5fa7521598.~~ All builds before those (7480efa) start normally. All 84de84b builds, both GCC and Clang, v3 or not, don't start.

**Comment by Andarwinux** [comment]
duplicate of #500. Please wait for the next build.
