### ISSUE TITLE
OSC delayed reaction as of 20231107

### ISSUE THREAD

**Issue by plissken1138** [shinchiro/mpv-winbuild-cmake#506]
OSC weirdly delayed on mouse move, takes a few seconds to show or respond to clicking on the timeline, although right-click pauses playback instantly.  Started happening with 20231107, also in 20231108.

win10edu amd fx-6300

**Comment by zhongfly** [comment]
Look like mpv issue.
So you should open issue in mpv's repo https://github.com/mpv-player/mpv/issues.

**Comment by hooke007** [comment]
Are you talking about https://github.com/mpv-player/mpv/issues/12825 ?

**Comment by plissken1138** [comment]
> Are you talking about [mpv-player/mpv#12825](https://github.com/mpv-player/mpv/issues/12825) ?

yes, it seems like that's the issue that manifests on my end, although I don't have video-out-params in mpv.conf or input.conf

**Comment by hooke007** [comment]
You could try today's build again to check.

**Comment by plissken1138** [comment]
> You could try today's build again to check.

It's working fine now! Cheers!
