### ISSUE TITLE
add video-aspect doesnt work [unknows proberty]

### ISSUE THREAD

**Issue by saha1914** [shinchiro/mpv-winbuild-cmake#508]
add video-aspect says [unknows proberty] and video aspect override doesnt fit some resolutions

**Comment by zhongfly** [comment]
https://github.com/mpv-player/mpv/commit/3ab5401b38d1ff1c1bb85f108f26d508cc334c82
`video-aspect`has been deprecated 4 years and finally removed.
Also this repo is only for issue related to building Windows binaries of mpv, not for solving mpv questions on usage.

**Comment by saha1914** [comment]
> [mpv-player/mpv@3ab5401](https://github.com/mpv-player/mpv/commit/3ab5401b38d1ff1c1bb85f108f26d508cc334c82) `video-aspect`has been deprecated 4 years and finally removed. Also this repo is only for issue related to building Windows binaries of mpv, not for solving mpv questions on usage.

then plz how can one make some videos that dont fit fit?

**Comment by zhongfly** [comment]
Read https://github.com/mpv-player/mpv/commit/3ab5401b38d1ff1c1bb85f108f26d508cc334c82, then you will know `video-aspect` can be replaced by `video-aspect-override`.
https://mpv.io/manual/master/#options-video-aspect-override Read manual for more info.
And if you have question about using mpv, ask in https://github.com/mpv-player/mpv/issues
