### ISSUE TITLE
How to use pdb files

### ISSUE THREAD

**Issue by snylonue** [shinchiro/mpv-winbuild-cmake#509]
I'm debugging my cplugin(written in rust) on windows using codelldb, which crashes in `mpv_wait_event`.
But when stepping into `mpv_wait_event`, the debug symbols are unavailable and only assembly is shown.
I tried to load pdb files via ` target modules add "D:/software/mpv/mpv.exe" -s "D:/software/mpv/mpv.pdb"` but in vain.
I'm wondering how to properly use these files to debug mpv.

**Comment by kasper93** [comment]
> windows using codelldb

Ask over at codelldb issue tracker how to load pdb debug symbols.

**Comment by snylonue** [comment]
> > windows using codelldb
> 
> Ask over at codelldb issue tracker how to load pdb debug symbols.

Could you recommend a debug tool?
