### ISSUE TITLE
mpv.exe - Entry Point Not Found 

### ISSUE THREAD

**Issue by Theo1996** [shinchiro/mpv-winbuild-cmake#511]
I downloaded this `mpv-x86_64-20231105-git-7480efa` version and when I run mpv in cmd it pops this error :

` mpv.exe - Entry Point Not Found The procedure entry point GetSystemTimePreciseAsFileTime could not be located in the dynamic link library KERNEL32.dll.  `
CMD doesnt say anything.
Is this win 7 support issue?
win7 64-bit

**Comment by zhongfly** [comment]
https://github.com/shinchiro/mpv-winbuild-cmake/issues/475

**Comment by Theo1996** [comment]
From what I read support for  windows 7 has dropped,  clownworld.
