### ISSUE TITLE
antimalware service executable is get crazy when open mpv

### ISSUE THREAD

**Issue by Ammar-A7med** [shinchiro/mpv-winbuild-cmake#514]
antimalware service executable gets crazy when opening mpv and goes to 90% of CPU
and that slow mpv startup
and when I add MPV to the exclusions list it reduces the impact of MPV but it still goes to 10% of the CPU

**Comment by Andarwinux** [comment]
Are you using x86-64 or x86-64-v3 version?

**Comment by Ammar-A7med** [comment]
> Are you using x86-64 or x86-64-v3 version?

I use x86-64 version

**Comment by Andarwinux** [comment]
If your CPU support avx2, try v3 version, we enabled cfguard for v3, which might prevent antimalware false positives.

**Comment by Ammar-A7med** [comment]
> If your CPU support avx2, try v3 version, we enabled cfguard for v3, which might prevent antimalware false positives.

my CPU does not support avx2 I try v3 and I wont run

**Comment by shinchiro** [comment]
Thats sad but I cannot do anything
