### ISSUE TITLE
build trouble, need any help?

### ISSUE THREAD

**Issue by dotor1** [shinchiro/mpv-winbuild-cmake#516]
hello,

I'm build mpv-winbuild-cmake in ubuntu 22.04.3 LTS.(cmake:3.28.0-rc5)

when input 'ninja mpv', the following error occured.

![image](https://github.com/shinchiro/mpv-winbuild-cmake/assets/96975946/7cb84f71-efc7-4358-907c-003821a33fe2)

and, the following is the rubberband-build-out.log
![image](https://github.com/shinchiro/mpv-winbuild-cmake/assets/96975946/bcbd553a-098f-428e-a995-ba9b5b8de955)

despite something wrong , i don't know what it is.

any advice? thx,bro

**Comment by zhongfly** [comment]
What's in the `rubberband-build-error.log`?

**Comment by Andarwinux** [comment]
It is possible that OOM is triggered by insufficient memory, you can increase the memory or limit the number of concurrent jobs with `-DMAKEJOBS=n`.

**Comment by dotor1** [comment]
@zhongfly, thx for ur concern, the build process was nothing wrong. the problem was out of memory. from yesterday until now, I appreciate ur concern sincerely. thx bro.

**Comment by dotor1** [comment]
@Andarwinux, u'r right. it was because of the OOM. my ubuntu machine has 8gb memroy. that's the cause. I enlarge the memory, the problem solved. during compiling, the terminal sometimes has quitted without any warning. now if it was because of oom, I can understand it. thx for ur advice. it was a huge help to me. thx
