### ISSUE TITLE
build trouble, sos plz

### ISSUE THREAD

**Issue by dotor1** [shinchiro/mpv-winbuild-cmake#518]
hello,

I'm build mpv-winbuild-cmake in ubuntu 22.04.3 LTS.(cmake:3.28.0-rc5)

in this time, clang 64bit.

when input 'ninja mpv', the following error occured.

![image](https://github.com/shinchiro/mpv-winbuild-cmake/assets/96975946/4bb1c9fd-7c49-4aa1-9830-37437b4a9832)

is this because of OOM,too?

in this case, the memory is 64gb.

this is my configure command.( I just want to build using 64. not 64-v3. configure command is little confusing. sorry about that. I'm trying to get used to it.. still progress)

![image](https://github.com/shinchiro/mpv-winbuild-cmake/assets/96975946/928f163e-2336-480d-8d4d-317158dd5437)

and some logs.
![image](https://github.com/shinchiro/mpv-winbuild-cmake/assets/96975946/36b65fa8-fc63-4e1d-8e2b-1c7293585ee0)
![image](https://github.com/shinchiro/mpv-winbuild-cmake/assets/96975946/c8459791-a9c5-438d-b3a1-24d5e7ffd776)
![image](https://github.com/shinchiro/mpv-winbuild-cmake/assets/96975946/000c152e-c020-404b-9eca-66dc6fa9c8db)

/home/dotory/dotory_work2/mpv-winbuild-cmake/packages/openal-soft/common/polyphase_resampler.cpp:48:17: error: no member named 'cyl_bessel_i' in namespace 'std'

/home/dotory/dotory_work2/mpv-winbuild-cmake/packages/openal-soft/common/polyphase_resampler.cpp:125:38: error: no member named 'cyl_bessel_i' in namespace 'std'

it's clang build and,, std namespace does not contain cyl_bessel_i....

I maybe missed something. but I don't know.

(extra info)
![image](https://github.com/shinchiro/mpv-winbuild-cmake/assets/96975946/272ba762-8c1c-43a6-acd7-b09f834dc758)

thx

**Comment by Andarwinux** [comment]
fixed by https://github.com/kcat/openal-soft/commit/d6d572df66eb2b5beeb3da7f3b11a328500c33c3

**Comment by Andarwinux** [comment]
This issue has been fixed from upstream, please close this issue.
