### ISSUE TITLE
Using VapourSynth for motion interpolation

### ISSUE THREAD

**Issue by tp78903** [shinchiro/mpv-winbuild-cmake#52]
I'm trying to get motion interpolation (60 FPS) working for mpv, but the information on sourceforge about VapourSynth is not clear to me at all. I end up with errors like `Could not initialize VapourSynth scripting` and others. Could someone provide some instructions on how to make this work, and which scripts to use. Thank you.

**Comment by shinchiro** [comment]
**Here's quick steps:**

1. Download latest [Vapoursynth](https://github.com/vapoursynth/vapoursynth/releases). If you've download portable version, extract it in same folder as mpv.exe
2. Download [Python 3.6.x](https://www.python.org/downloads/release/python-364). If you want portable one, download the embed one and extract in same folder as mpv.exe
3. Download additional vapoursynth plugin like [mvtools](https://github.com/dubhater/vapoursynth-mvtools/releases). Extract the library and copy into `vapoursynth64\plugins` folder
4. You may need additional plugins, depends on what the vapoursynth script do

**Comment by tp78903** [comment]
Thank you - that works.

Do you recommend [mvtools.vpy](https://github.com/haasn/gentoo-conf/blob/xor/home/nand/.mpv/filters/mvtools.vpy) for interpolation, or something else?

Btw does your latest mpv build still include vapoursynth support?

**Comment by shinchiro** [comment]
> Btw does your latest mpv build still include vapoursynth support?

Yes. You can check it by typing `mpv --vf=help` in command prompt and look for vapoursynth

I dont use interpolation so better ask somewhere else

**Comment by zc62** [comment]
@tp78903 I use [SVP4](https://www.svp-team.com/wiki/Purchase). But you need to pay some money to have the mpv/vapoursynth support in Windows.
