### ISSUE TITLE
Found error "Failed to initialize VAAPI: unknown libva error" when set hwdec=vaapi-copy

### ISSUE THREAD

**Issue by sakuhanachan** [shinchiro/mpv-winbuild-cmake#522]
As said in the title.

When I set ``hwdec=vaapi-copy`` in config or command, I found error as
```
[vaapi] Failed to initialize VAAPI: unknown libva error
```
but this error not appear when I set ``hwdec=vaapi``

My setting
```
##specs: Intel Core i5 4690 + NVIDIA Geforce GTX 1050 /w 546.17 driver installed##
profile=high-quality
vo=gpu-next
gpu-api=vulkan
```

Test file: https://files.catbox.moe/yp6p2c.mp4
Pre-built ``vaon12_drv_video.dll`` driver in use: https://github.com/pal1000/mesa-dist-win (ver.23.3.0rc4)

I open issue here since I not sure this problem appear on upstream, this build (20231123 Clang), pre-built driver or my PC.

**Comment by sakuhanachan** [comment]
I tried to set env and launch to play video again, found mpv crashed.

**Comment by sakuhanachan** [comment]
It's running fine as show adapters list.
![image](https://github.com/shinchiro/mpv-winbuild-cmake/assets/2475440/a26285a0-0d51-4123-b630-b7925918b0e8)

Also I set adepter to my 1050 (``vaapi-device="NVIDIA GeForce GTX 1050"``), it's running fine.
![image](https://github.com/shinchiro/mpv-winbuild-cmake/assets/2475440/d13a6e4d-9db0-4462-847c-49944a42a8f8)

**Comment by sakuhanachan** [comment]
Should I close issue now or keep it until mesa solve this problem?

**Comment by zhongfly** [comment]
> Make sure ENV `LIBVA_DRIVER_NAME` and `LIBVA_DRIVERS_PATH` are properly export.

Add this to readme.md or wiki will help user know how to use vaapi.
@Andarwinux @shinchiro
