### ISSUE TITLE
support for --demuxer-lavf-format=vapoursynth

### ISSUE THREAD

**Issue by stax76** [shinchiro/mpv-winbuild-cmake#54]
I use your builds in mpv.net and consider using it for StaxRip as well. For both apps it's very important to open vpy files which currently don't seem to work.

```
Desktop> mpv --demuxer-lavf-format=vapoursynth D:\Samples\test.vpy
[lavf] Unknown lavf format vapoursynth
```

https://github.com/mpv-player/mpv/issues/7213

**Comment by shinchiro** [comment]
Be sure to check the [wiki](https://github.com/shinchiro/mpv-winbuild-cmake/wiki/Setup-vapoursynth-in-mpv) on how to setup vapoursynth properly.

**Comment by stax76** [comment]
> Get latest Vapoursynth with same type (32/64-bit) as mpv. Download portable version and extract it in same folder as mpv.exe.

> Get Python 3.7.x. Download the embeddable file and extract it in same folder as mpv.exe

I don't think I can do that for several reasons. I need to eat my own dog foot so the mpv.net build I use for my playback is also my debug developer build and release build (I release debug builds), I can't just put everything in one directory because that would be an unmanageable mess, things have to be separated in sub folders. I can try to set the process wide Path variable and see if a sub folder works.

There are other reasons why it's a no go for me, people are already complaining that both StaxRip and mpv.net need too much download and disk space (they call it bloat), so I and the users of mpv.net and StaxRip need vpy playback in the same way as **all other apps work, using the installed Python and VapourSynth**, in MPC-BE and dozens of other apps it just works out of the box and by default.

**Comment by stax76** [comment]
I give this issue another go.

https://forum.doom9.org/showthread.php?t=180433
