### ISSUE TITLE
No fallback with av1

### ISSUE THREAD

**Issue by SanokKule** [shinchiro/mpv-winbuild-cmake#541]
Build `20231123` and up with `hwdec=auto` when playing av1 crashes instead of falling back to software decoding.
`Exception code: 0x80000003`

`20231122` works fine.

Windows 11
GTX 1060

**Comment by zhongfly** [comment]
try latest build:
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20231128

and report issue to mpv: https://github.com/mpv-player/mpv/issues

**Comment by SanokKule** [comment]
Yes sorry, i didn't try builds newer than `20231126`, `20231127` and up works fine...
