### ISSUE TITLE
cannot index into a null array

### ISSUE THREAD

**Issue by grandpa1946** [shinchiro/mpv-winbuild-cmake#544]
i know this issue has been asked here a lot, but idk why it tells me that. i have an [amd ryzen 5 7600](https://www.amd.com/en/product/12756) and my windows version is windows 11 22621.2715

**Comment by Flax4** [comment]
I just started getting the same problem.

Windows 10 LTSC (19044.3693)
Intel(R) Core(TM) i9-10900K CPU
RTX 3080

**Comment by Bec-de-Xorbin** [comment]
Latest mpv x86_64-v3 version missing, I guess that's the problem.

**Comment by FNageki** [comment]
For now you can edit settings.xml and change the channel to weekly, or the arch to x86_64.

**Comment by shinchiro** [comment]
Should be fixed after I reset the github action cache
