### ISSUE TITLE
gcc build 32 builds fails at libopenmpt-prefix

### ISSUE THREAD

**Issue by wbtcpip2** [shinchiro/mpv-winbuild-cmake#563]
i'm sorry to open a new issue but i'm still trying to compile gcc 32 bits libmpv. This time i get:

`FAILED: packages/libopenmpt-prefix/src/libopenmpt-stamp/libopenmpt-removeprefix /__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/build32/packages/libopenmpt-prefix/src/libopenmpt-stamp/libopenmpt-removeprefix `

https://github.com/wbtcpip2/mpv-winbuild/actions/runs/7151304876/job/19475482213

**Comment by wbtcpip2** [comment]
ok thank you

**Comment by shinchiro** [comment]
Should be working since CI for gcc didnt failed
