### ISSUE TITLE
[Request] patch to ffmpeg build

### ISSUE THREAD

**Issue by Obegg** [shinchiro/mpv-winbuild-cmake#564]
current behavior:
```
af=surround:chl_out=5.1(side):focus=1:overlap=0.875:win_size=16384:win_func=hann
```
introduces audio delay.

solution: apply this patch to ffmpeg: https://github.com/librempeg/librempeg/commit/5d2a66861ef6c736545b80ca05732dcb72e84925

full issue: https://github.com/mpv-player/mpv/issues/13030

**Comment by hooke007** [comment]
Let it be now. It hasn't prove it can be alive longer than Libav.
What if more and more patches he posted only in his fork? And then merged everthing manually in this repo? It's absurd.

**Comment by shinchiro** [comment]
Its more appropriate you ask ffmpeg team to merge that commit.
