### ISSUE TITLE
error: pathspec 'version' when building gcc

### ISSUE THREAD

**Issue by wbtcpip2** [shinchiro/mpv-winbuild-cmake#570]
hi,
trying to build mpv gcc here: https://github.com/wbtcpip2/mpv-winbuild/actions/runs/7227795056/job/19697348405

i'm having an error when publishing release

```
Run git fetch --tags
error: pathspec 'version' did not match any file(s) known to git
fatal: 'origin/version' is not a commit and a branch 'version' cannot be created from it
Switched to a new branch 'version'
rm '.github/dependabot.yml'
rm '.github/workflows/clean.yml'
rm '.github/workflows/mpv.yml'
rm '.github/workflows/toolchain.yml'
rm 'LICENSE'
rm 'README.md'
rm 'build.sh'
rm 'patch_pr/0000-mpv-add-patch.patch'
rm 'prunetags.sh'
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
[version (root-commit) 0c1b87e] 2023-12-16-054dde0
 1 file changed, 1 insertion(+)
 create mode 100644 version
remote: Permission to wbtcpip2/mpv-winbuild.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/wbtcpip2/mpv-winbuild/': The requested URL returned error: 403
Error: Process completed with exit code 128.
```
could you please help me to understand how i can fix it?

thank you

**Comment by zhongfly** [comment]
Not related to this repo

`Permission to wbtcpip2/mpv-winbuild.git denied to github-actions[bot]`
You can try to use google or any other search tool first
one of search results: https://stackoverflow.com/questions/72851548/permission-denied-to-github-actionsbot

Close issue after you resolve problem.
![image](https://github.com/shinchiro/mpv-winbuild-cmake/assets/11155705/b0acef68-8c4f-4476-9cd9-458ad9dc9d2a)

**Comment by wbtcpip2** [comment]
thank you
