### ISSUE TITLE
truehd audio decoder missing since mpv windows version mpv-x86_64-v3-20231218-git-702b3eb

### ISSUE THREAD

**Issue by maartinsd** [shinchiro/mpv-winbuild-cmake#576]
Provide following Information:

mpv version: mpv-x86_64-v3-20231219-git-17be6e1
Platform and Version: Windows 10 Home 22H2 19045.3803
mpv does not play the Dolby TrueHD audio track, video is displayed correctly. I checked with --ad=help: the truehd decoder is missing from the decoder list. In mpv-x86_64-v3-20231211-git-566a96f everything works fine and there is a truehd decoder in the decoder list. Question: how to in recent mpv builds play movies with Dolby truehd audio and dvd audio with mlp file?

**Comment by llyyr** [comment]
lto shouldn't be worth such a widely popular codec not being supported. Especially considering the performance gains from lto should fall below the threshold of significance for any meaningful benchmarking or real word benefits. Can you provide any benchmarks for lto vs non-lto builds?

**Comment by shinchiro** [comment]
Well, I didnt aware disabling mlp will disable dolby things though. Disabled lto for now until things getting better

**Comment by shinchiro** [comment]
Please test again with https://github.com/shinchiro/mpv-winbuild-cmake/actions/runs/7268873148/artifacts/1125443098 release whether you can play truehd audio without problem?

**Comment by maartinsd** [comment]
Thank you. Dolby TrueHD and MLP work great in mpv versions mpv-winbuild-cmake/actions/runs/7268873148/artifacts/1125443098 and mpv-x86_64-v3-20231220-git-17be6e1.

**Comment by maartinsd** [comment]
Dolby TrueHD and MLP works fine
