### ISSUE TITLE
MPV gives me a blocked icon when I try to drag a clip in for viewing. Sorry this needs to be closed. Newbie didn't know what he was doing. 

### ISSUE THREAD

**Issue by huskereurocat** [shinchiro/mpv-winbuild-cmake#579]
![image](https://github.com/shinchiro/mpv-winbuild-cmake/assets/52609668/b0c9c019-ac5a-4218-88b0-510926ce30c9)
Not sure why, but the MPV player just gives me a blocked or stop icon when I try to drag my video clip into it. Not sure what I may be doing wrong. 

![image](https://github.com/shinchiro/mpv-winbuild-cmake/assets/52609668/30373a65-356b-4750-a239-4ad6aec5d871)
I just click on the mpv.exe application to activate the program, correct?

**Comment by Obegg** [comment]
First - reopen the issue.
Second - I guess it's probably because you run `mpv.exe` as administrator, I know that because I did the same and couldn't figure out why I couldn't drag and drop anymore.

**Comment by huskereurocat** [comment]
Please add some more detail about how this issue affects you. For me, MPV wouldn't play a video at all, until I watched a video from YT that showed me that I had to import all the different files that MPV would recognize and play. Then if I right click the clip or video that I want to play and choose to open it with MPV, the player will activate and play the file. For now, it still will not simply drag and drop then start playing, which I thought it was supposed to do. I'll leave this open in case it truly is supposed to have drag and drop support.
