### ISSUE TITLE
vapoursynth crash with mvtools

### ISSUE THREAD

**Issue by bitingsock** [shinchiro/mpv-winbuild-cmake#58]
The first build that you published that enabled vapoursynth "build 20171229" works properly with https://github.com/haasn/gentoo-conf/blob/xor/home/nand/.mpv/filters/mvtools.vpy every successive build hangs mpv when attempting to apply the filter. Log doesn't really provide anything useful: 
[log.txt](https://github.com/shinchiro/mpv-winbuild-cmake/files/1679486/log.txt)
I notice later builds don't include "vapoursynth.dll" and "vsscript.dll". Deleting them from my folder doesn't do anything.

**Comment by shinchiro** [comment]
Yeah, I made the build doesn't depend on those dll's on startup unless you're using vs. The crash will happen if mpv cannot find those 2 dlls when try loading vs script. Make sure to put install vapoursynth properly or just put the 2 dll in same folder as mpv.exe

**Comment by bitingsock** [comment]
My vapoursynth may need reinstall but placing the dlls along side newer builds does not fix the crash. This means it is finding the vs install but breaking?

**Comment by bitingsock** [comment]
Well I can't find why it would be installed wrong. running python from commandline returns the python prompt correctly and `from vapoursynth import core
print(core.version())` returns VS version info

**Comment by bitingsock** [comment]
I think I had mismatching 32/64bit versions of stuff. Installed both version of everything and it works now.

**Comment by shinchiro** [comment]
Yeah, the dll's must have same type (32/64-bit) as mpv
