### ISSUE TITLE
Cannot build 2 modules nightly  202401122

### ISSUE THREAD

**Issue by emveepee** [shinchiro/mpv-winbuild-cmake#596]
Running Ubuntu 22.04.3 two module uchardet and libjxl don't build on gcc or clang.

On uchardet it is the uchardet-tests.exe  Full logs here https://pastebin.com/F4fShwQ6 and https://pastebin.com/bBi1SS7L

For   libjxl   clang and gcc are quite different  https://pastebin.com/cMAmNiLb and https://pastebin.com/pLRPgx4Z

**Comment by emveepee** [comment]
Both of those where with cmake into new empty folders using the command line on GitHub  I did have to update to current cmake to get them to build.  

100's of module build correctly if I loop on the error, up until ffmpeg needs to start.

[1/28] Performing build step for 'uchardet'

**Comment by zhongfly** [comment]
> It seems to be caused by typo in the wrapper. Not sure why it can't be reproduced on archlinux based systems.

https://www.gnu.org/software/bash/manual/bash.html#index-_005b_005b

bash support `==`, but other shell doesn't support it.
ArchLinux use bash as default shell.

https://stackoverflow.com/questions/20449543/shell-equality-operators-eq

**Comment by emveepee** [comment]
I applied the patch and uchardet and libjxl do compile on their own and I can get to the but mpv does not compile.  I get to the end and see an error stripping mpv.com  '/home/martin/build64/packages/mpv-prefix/src/mpv-build/mpv.com': No such file so it fails.  There is a ./packages/mpv-prefix/src/mpv-build/player/mpv.com and copying that seems to work.

Afterwards I can't just rerun because there is something corrupting libjxl, spriv-cross, luajit and vulkan forcing me to removeprefix these package

**Comment by emveepee** [comment]
Again this was a fresh install so the mpv.com strip error was from the build system, was nothing to update.

I would have thought after running ninja mpv successfully, running it a second time with no changes would "just work"

**Comment by shinchiro** [comment]
what meson version u used? I guess it is below 1.3 which made  the `.com` generated in `player` directory

**Comment by emveepee** [comment]
> what meson version u used? I guess it is below 1.3 which made the `.com` generated in `player` directory

Yes it is lower, 1.0.1

**Comment by shinchiro** [comment]
I would suggest you install meson through pip
