### ISSUE TITLE
gdigrab captures a single frame, then closes

### ISSUE THREAD

**Issue by csolisr** [shinchiro/mpv-winbuild-cmake#60]
I'm currently attempting to capture desktop footage in order to post-process it with mpv via vapoursynth and display it back to the screen. In order to do so, I'm using gdigrab (via ffmpeg) to capture a specific window, with the command `mpv av://gdigrab:title="Title of the window"`. However, whenever I attempt it, the window shows a single frame of footage, then closes shortly after. Running the script by testing a full-desktop capture, with my standard configuration file outputs the following:

[mpv_error.log.txt](https://github.com/shinchiro/mpv-winbuild-cmake/files/4245501/mpv_error.log.txt)

Some particular lines that were of my interest:

```
[vd] Codec list:
[vd]     bmp - BMP (Windows and OS/2 bitmap)
[vd] Opening decoder bmp
[vd] No hardware decoding requested.
[vd] Using software decoding.
[vd] Detected 4 logical cores.
[vd] Requesting 5 threads for decoding.
[vd] Selected codec: bmp (BMP (Windows and OS/2 bitmap))
[vf] User filter list:
[vf]   (empty)
[cplayer] Starting playback...
[vd] DR failed - disabling.
[ffmpeg/demuxer] gdigrab: Failed to capture image (error 6)
[lavf] error reading packet: I/O error.
[lavf] EOF reached.
[vd] Decoder format: 1920x1080 [0:1] bgra auto/auto/auto/auto/auto CL=unknown
[vf] [in] 1920x1080 bgra rgb/bt.709/srgb/full/display SP=1.000000 CL=mpeg1/jpeg
[vf] [userdeint] 1920x1080 bgra rgb/bt.709/srgb/full/display SP=1.000000 CL=mpeg1/jpeg
[vf] [userdeint] (disabled)
[vf] [autorotate] 1920x1080 bgra rgb/bt.709/srgb/full/display SP=1.000000 CL=mpeg1/jpeg
[vf] [autorotate] (disabled)
[vf] [convert] 1920x1080 bgra rgb/bt.709/srgb/full/display SP=1.000000 CL=mpeg1/jpeg
[vf] [convert] (disabled)
[vf] [out] 1920x1080 bgra rgb/bt.709/srgb/full/display SP=1.000000 CL=mpeg1/jpeg
[vf] filter input EOF
[ffmpeg/demuxer] gdigrab: Failed to capture image (error 6)
[vf] filter output EOF
[lavf] error reading packet: I/O error.
```

At first I thought the issue was with my configuration file, so I also attempted to run it with the `--no-config` option, with similar results:

[mpv_error_2.log.txt](https://github.com/shinchiro/mpv-winbuild-cmake/files/4245502/mpv_error_2.log.txt)

More lines of interest:

```
[ffmpeg/demuxer] gdigrab: Capturing whole desktop as 1920x1080x32 at (0,0)
[lavf] Could not set AVOption user_agent='libmpv'
[lavf] Could not set AVOption tls_verify='0'
[lavf] Could not set AVOption icy='1'
[lavf] Could not set AVOption timeout='60000000'
[cplayer] Set property: shared-script-properties -> 1
[ffmpeg/demuxer] gdigrab: Stream #0: not enough frames to estimate rate; consider increasing probesize
[lavf] avformat_find_stream_info() finished after 0 bytes.
```

I have already tried using a large value `--demuxer-lavf-probesize` (in order to increase the amount of bytes probed (around 1920x1080x32x2 = `132710400` to be absolutely safe), as it might be sampling a single frame and declaring it a standalone bitmap file, but the change didn't seem to fix the issue.

**Comment by shinchiro** [comment]
Please send the report to official mpv github: https://github.com/mpv-player/mpv/issues/new/choose
