### ISSUE TITLE
Does this build support Intel QuickSync and Nvidia NVENC?

### ISSUE THREAD

**Issue by sofakng** [shinchiro/mpv-winbuild-cmake#60]
Does this build support Intel QuickSync and Nvidia NVENC?

If not, would you accept a pull request to add support?

Also, it looks like you are compiling x265, but not including it in the FFmpeg build.  (it requires --enable-libx265).

**Comment by shinchiro** [comment]
> Does this build support Intel QuickSync and Nvidia NVENC?

Nope. What benefits it bring to mpv?

**Comment by sofakng** [comment]
I'm not sure, but SVP (https://www.svp-team.com) has stated that MPV should have QuickSync/NVENC/x265 to work with their VapourSynth plugin.

I think would also allow more HW decoding support (NVENC/QuickSync) and x265 support would also be nice to have.  It looks like you meant to have it supported, but with your script FFmpeg doesn't include support for it.

**Comment by shinchiro** [comment]
nvenc is always enabled before. I also add amf support in ffmpeg but I dont plan adding x265 and quicksync
