### ISSUE TITLE
mpv-1.dll built with libressl doesn't work in Plex Media Player

### ISSUE THREAD

**Issue by chainikdn** [shinchiro/mpv-winbuild-cmake#61]
`2018-02-11 15:56:06 [ DEBUG ] PlayerComponent.cpp @ 583 - ffmpeg: Opening https://192.168.1.5:32400/video/:/transcode/universal/start?hasMDE=1&...`
...
`2018-02-11 15:56:06 [ ERROR ] PlayerComponent.cpp @ 589 - ffmpeg: tls: server name not specified `
`2018-02-11 15:56:06 [ ERROR ] PlayerComponent.cpp @ 589 - stream: Failed to open https://192.168.1.5:32400/video/:/transcode/universal/start?hasMDE=1&..`

schannel build used to work

**Comment by chainikdn** [comment]
https://github.com/libressl-portable/openbsd/blob/master/src/lib/libtls/tls_util.c

```
/* Find the port seperator. */
if ((p = strchr(p, ':')) == NULL)
	goto done;

/* If there is another separator then we have issues. */
if (strchr(p + 1, ':') != NULL)
	goto done;
```

**Comment by chainikdn** [comment]
Nevermind. The correct answer is there: https://github.com/libressl-portable/openbsd/issues/90

**Comment by shinchiro** [comment]
should be fix in this unmerged ffmpeg's patch:
https://patchwork.ffmpeg.org/patch/7693/
