### ISSUE TITLE
Can't install on Windows 11

### ISSUE THREAD

**Issue by graham8** [shinchiro/mpv-winbuild-cmake#612]
I've been running an older version for months but I can't get the latest Windows download to work.  Copied everything into a folder, double-click mpv.exe, dismiss Windows warning then nothing.  And nothing showing in Task Manager.

How to debug?

**Comment by temis01** [comment]
do you have an error ID 1000 in windows event viewer ?
do you have vulkan enabled in mpv.conf ?
if so you may disable vulkan and use default mpv hwdec
before disabling vulkan :
you could debug if you like with m$ windbg from github but you need to use zhongfly mpv + mpv.pdb in same directory

**Comment by graham8** [comment]
Thanks for the reply.  I did solve this by deleting a line in the conf file but didn't keep a note of what I deleted. I now just have `vo=gpu-next` and it's working again.  If I can find the old version in a backup, I'll post that here.
