### ISSUE TITLE
ffmpeg has been installed in my win 10 system. After installing mpv-winbuild-cmake, will it replace the installed ffmpeg?

### ISSUE THREAD

**Issue by haiyulin** [shinchiro/mpv-winbuild-cmake#616]
ffmpeg has been installed in my win 10 system. 
1) After installing mpv-winbuild-cmake, will it replace the installed ffmpeg?
2）And will there be any conflicts or errors with the installed ffmpeg?
How to install？

I appreciate you taking the time to answer this.

**Comment by hooke007** [comment]
There is no installation in this project.

**Comment by hooke007** [comment]
The script mainly sets up file associations for mpv on Windows.
