### ISSUE TITLE
Updater giving SSL/TLS error

### ISSUE THREAD

**Issue by NorioTomokawa** [shinchiro/mpv-winbuild-cmake#62]
Hi there,

Since Tuesday the 13th of February 2018, running updater.bat gives me a `The request was aborted: Could not create SSL/TLS secure channel.` right after `Fetching RSS feed for mpv`.

I went into [https://sourceforge.net/projects/mpv-player-windows/rss?path=/64bit](url) which is what the `updater.ps1` links to (on my 64-bit machine, anyway). Now here's something interesting. Despite the fact that the protocol is indeed HTTPS - as shown in the address bar - there is no "little green lock" and I'm getting a `Connection is Not Secure`. 

Just wondering whether this is something on my side or on Sourceforge's side. Thanks.

I have attached a screenshot here:
![mpv ssl](https://user-images.githubusercontent.com/36551473/36329915-af4d4194-1335-11e8-8d8a-9bfd26177597.png)

**Comment by shinchiro** [comment]
Already fixed in shinchiro/mpv-packaging@fe1e0c7. Next build will have the fixed `updater.ps1`

If you prefer to download future build with the script, you need to add those 2 line in the current `updater.ps1`

**Comment by fcll** [comment]
I got this error concerning the security protocols:
```
Running script without administrator privileges
Checking Windows PowerShell version -- 3
Cannot convert value "Tls, Tls11, Tls12" to type "System.Net.SecurityProtocolType". Error: "Invalid cast from 'System.Security.Authentication.SslProtocols' to 'System.Net.SecurityProtocolType'."
```

I did some digging and changed line 253 manually to  ```[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12``` and voila, it works (for me). Change copped from [some blog](https://blog.pauby.com/post/force-powershell-to-use-tls-1-2/).

System: Windows 7 Pro SP1 x64, PowerShell 3.0, latest script/mpv (20180310)

**Comment by shinchiro** [comment]
That might be incompatibility with older version of powershell. I'll just change it for good
