### ISSUE TITLE
Stable releases don't include install scripts

### ISSUE THREAD

**Issue by dsbert** [shinchiro/mpv-winbuild-cmake#63]
Hopefully this is the place to ask.

The stable release archives on sourceforge do not include the installer scripts. `scoop` references these scripts in the installation notes. I'm wondering if this is deliberate (don't know much about the release workflow) and scoop should be updated or if the scripts can be added to stable?

Thanks

https://github.com/lukesampson/scoop-extras/issues/3587

**Comment by shinchiro** [comment]
Dont know much about scoop but I'll add installer scripts too in stable build in future
