### ISSUE TITLE
Command Line Options Don't Work

### ISSUE THREAD

**Issue by asheimo** [shinchiro/mpv-winbuild-cmake#64]
I would like to be able to verify mpv availability on a system by invoking mpv --version but it doesn't seem like that's available in the windows version. Am I wrong or is that something that can be easily implemented?

**Comment by garoto** [comment]
`mpv.com --version`.

**Comment by asheimo** [comment]
so the mpv.exe can be used as standalone but to get some of the functionality you need to have the mpv.com as well. Is that correct?

**Comment by garoto** [comment]
It's a Windows limitation regarding CUI and GUI executables.

https://github.com/mpv-player/mpv/wiki/FAQ#On_Windows_why_does_mpvexe_not_attach_to_the_console_and_what_does_mpvcom_do

Edit: `.com` binaries should have priority over `.exe` ones by default. Check your `%PATHEXT%` environment variable. It should have an order similar to this: `
.COM;.EXE;.BAT;.CMD;.MSC;.VBS;.VBE`

**Comment by shinchiro** [comment]
^Exactly
