### ISSUE TITLE
Hello friend! Can you please help me to compile Windows executables?

### ISSUE THREAD

**Issue by zhouxinghong** [shinchiro/mpv-winbuild-cmake#646]
Hello friend! Can you please help me to compile Windows executables?
Just compiling Windows x64 is fine, thank you very much.🎉😜👍👏
Here is the source code address:
https://github.com/librempeg/librempeg

**Comment by zhouxinghong** [comment]
Because I need a latest version of librempeg Windows executable, but I can't compile it myself, so I'd like to ask you to help me build it 😜 Thank you very, very much indeed! 💗💗

**Comment by shinchiro** [comment]
Change the git url with librempeg in `ffmpeg.cmake`.
https://github.com/shinchiro/mpv-winbuild-cmake/blob/3281b9143064965daaeef195cc144a129bbd1331/packages/ffmpeg.cmake#L49
