### ISSUE TITLE
updater.bat not removing the downloaded .7z files

### ISSUE THREAD

**Issue by NorioTomokawa** [shinchiro/mpv-winbuild-cmake#66]
Hi there,

I update your mpv builds through the updater.bat script. However recently (for the past 3-4 updates I think) the downloaded .7z files remain in the directory.

I run the updater script without admin privileges but I've always did that and I've never had any problems with files not being automatically deleted after the update.

I went through the updater.ps1 and it doesn't seem to have a command to remove the downloaded .7z, but I'm not a programmer.

Thanks!

**Comment by shinchiro** [comment]
Yeah, I removed the command to delete the 7z archive. The reason is, sometimes mpv or other packages like spirv-cross can be unstable at time . By not deleted them will give users to downgrade. This can be annoying but you need to manually delete them if no regression occured

**Comment by shinchiro** [comment]
Or I can make it only keep only 4-5 older build in the directory if people want..
