### ISSUE TITLE
[BUG] apt-get install list has some errors.

### ISSUE THREAD

**Issue by tasty0tomato** [shinchiro/mpv-winbuild-cmake#661]
As title.
'libgcrypt20-dev' instead of 'libgcrypt-dev'
E: Unable to locate package mimalloc

**Comment by Andarwinux** [comment]
You don't need to install this, mimalloc is just to speed up the build, you can also use jemalloc instead or not install any alternative malloc. I'll add statically linked mimalloc support for llvm later.

**Comment by shinchiro** [comment]
Install `libmimalloc-dev`
