### ISSUE TITLE
Microsoft Defender virus alert："Program:Win32/Wacapew.C!ml"

### ISSUE THREAD

**Issue by chacha125** [shinchiro/mpv-winbuild-cmake#665]
https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20240420/mpv-x86_64-20240420-git-e7b0d6b.7z，"mpv.com"
https://sourceforge.net/projects/mpv-player-windows/files/release/mpv-0.38.0-x86_64.7z, "mpv.exe"

**Comment by chacha125** [comment]
git and release,v3 builds no problem

**Comment by zhongfly** [comment]
submit mpv.exe(from [mpv-0.38.0-x86_64](https://sourceforge.net/projects/mpv-player-windows/files/release/mpv-0.38.0-x86_64.7z) ) to microsoft, hope Microsoft will correct this mistake.

https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-false-positives-negatives?view=o365-worldwide#part-4-submit-a-file-for-analysis

![image](https://github.com/shinchiro/mpv-winbuild-cmake/assets/11155705/4971bbc4-8786-4e81-af04-b1b951ee5928)

**Comment by udit** [comment]
> try v3 builds.

[/release/mpv-0.38.0-x86_64-v3.7z](https://sourceforge.net/projects/mpv-player-windows/files/release/mpv-0.38.0-x86_64-v3.7z/download) - Flagged as Trojan:Script/Wacatac.B!ml

[/64bit-v3/mpv-x86_64-v3-20240414-git-6a8b130.7z](https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/mpv-x86_64-v3-20240414-git-6a8b130.7z/download) - No issue

[/64bit/mpv-x86_64-20240414-git-6a8b130.7z](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20240414-git-6a8b130.7z/download) - No issue

**Comment by shinchiro** [comment]
The ultimate solution to solve the false flags is via code signing the executable
