### ISSUE TITLE
Libmpv from Feb. 25th is the last one that works in Plex

### ISSUE THREAD

**Issue by Enivex** [shinchiro/mpv-winbuild-cmake#669]
Because Plex ships with an _ancient_ version of mpv, I've made a habit of swapping out the dll with newer ones from https://sourceforge.net/projects/mpv-player-windows/files/libmpv/

Unfortunately no dll built after February 25th (i.e. March 4th and up) works. The player just endlessly loads.

I have no idea whether this is an issue with Plex itself, or the dlls. It would be nice to be able to keep up-to-date if possible

**Comment by mitzsch** [comment]
https://forums.plex.tv/t/dolby-truehd-passthrough-modified-mpv-build/802742/229

**Comment by mitzsch** [comment]
> Not related to this issue

Actually, it is. I linked a specific post in that forum thread. Please read. 

Quote from the plex forum post. 

_Side note on using the latest mpv upstream. Those versions will not work with Plex HTPC. The devs changed how the loadfile command works, breaking Plex HTPC (and probably Plex for Desktop as well)._

_Commit: [input/player: add loadfile/loadlist insert-at command · mpv-player/mpv@c678033 · GitHub 8](https://github.com/mpv-player/mpv/commit/c678033c1d60b48ae02fbbe4815869b9504a17f6)_

**Comment by Enivex** [comment]
> https://forums.plex.tv/t/dolby-truehd-passthrough-modified-mpv-build/802742/229

Thanks for the link, I've tried to search for this for a while, but never managed to find anything.

I guess the situation will just get worse and worse as long as Plex doesn't update their own mpv build?

**Comment by mitzsch** [comment]
> I guess the situation will just get worse and worse as long as Plex doesn't update their own mpv build?

I guess, but that's why there are users like myself who keep an eye on upstream mpv additions and revert them if necessary in a fork of mpv ;)



(I guess this can be closed)
