### ISSUE TITLE
update.bat not working!

### ISSUE THREAD

**Issue by njscorpion** [shinchiro/mpv-winbuild-cmake#67]
Mpv version output:

> mpv 0.32.0-288-gee70e8ce50 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
>  built on Sun Mar 22 12:56:50 +08 2020
> FFmpeg library versions:
>    libavutil       56.42.101
>    libavcodec      58.76.100
>    libavformat     58.42.100
>    libswscale      5.6.101
>    libavfilter     7.77.100
>    libswresample   3.6.100
> FFmpeg version: git-2020-03-21-ea46b45e9

Output of update.bat

> Running script without administrator privileges
> Checking Windows PowerShell version -- 5
> Fetching RSS feed for mpv
> Unable to connect to the remote server
> Press any key to continue . . .
>

**Comment by njscorpion** [comment]
![image](https://user-images.githubusercontent.com/44571306/77359861-4cc68780-6d72-11ea-8599-b975e1023fc9.png)

![image](https://user-images.githubusercontent.com/44571306/77359971-85666100-6d72-11ea-858c-cbab33bae84d.png)

**Comment by njscorpion** [comment]
Sorry for creating this issue! it seems to be some strange system error!

**Comment by Samillion** [comment]
I've been getting the same error, are you sure this was a system error?
