### ISSUE TITLE
Why not update after 20240426?

### ISSUE THREAD

**Issue by yosh-wang** [shinchiro/mpv-winbuild-cmake#672]
Why not update after 20240426?

**Comment by zhongfly** [comment]
see https://github.com/shinchiro/mpv-winbuild-cmake/actions
![image](https://github.com/shinchiro/mpv-winbuild-cmake/assets/11155705/90b18614-3263-4977-96bb-cca2b81d84c8)

Workflow was interrupted due to i686 mpv build failure. It will be released only if all builds succeed.

**Comment by Jules-A** [comment]
> Workflow was interrupted due to i686 mpv build failure. It will be released only if all builds succeed.

I don't know anything about Github build system but why can't the successful machine target builds be posted still?

EDIT: Oh, the packages are still there, I thought by "Upload releases" being skipped the artifacts weren't uploaded.

**Comment by zhongfly** [comment]
> I don't know anything about Github build system but why can't the successful machine target builds be posted still?

https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures

**Comment by TI34H** [comment]
I saw your mpv-winbuild repository is similar to this one, can you tell me what the differences are with this repository?

**Comment by izumi46** [comment]
> see https://github.com/shinchiro/mpv-winbuild-cmake/actions ![image](https://private-user-images.githubusercontent.com/11155705/327919060-90b18614-3263-4977-96bb-cca2b81d84c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MDM1NTcsIm5iZiI6MTcxNDgwMzI1NywicGF0aCI6Ii8xMTE1NTcwNS8zMjc5MTkwNjAtOTBiMTg2MTQtMzI2My00OTc3LTk2YmItY2NhMmI4MWQ4NGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDA2MTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1NWM1ZTY1NTFkZjhmMWU0MDk3Zjg0YjNkMWJkMjZkMmU3ZTllZGZiNjlmMGRkOWEzYzJhNWIxMGQ3MjdiYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lUhH5alnqzp231_Q445IrjQaJhgpusMX-ck8Bdvqr04)
> 
> Workflow was interrupted due to i686 mpv build failure. It will be released only if all builds succeed.

I saw your mpv-winbuild repository is similar to this one, can you tell me what the differences are with this repository ?

**Comment by zhongfly** [comment]
> I saw your mpv-winbuild repository is similar to this one, can you tell me what the differences are with this repository ?

Firstly, I need to make it clear that [shinchiro/mpv-winbuild-cmake](https://github.com/shinchiro/mpv-winbuild-cmake) (this repo) provides a toolchain for building mpv that anyone can use it to build mpv themselves. You can build the mpv on your own computer by using this toolchain.

Second, GitHub offers Linux, Windows, and macOS virtual machines to run workflows (builds, tests), just like on your own computer.This feature is called 'GitHub Action', and the workflows are defined by the `.github/workflows/xxxxx.yml`. For example,these files:
![image](https://github.com/shinchiro/mpv-winbuild-cmake/assets/11155705/6f961eed-8c6c-49a8-be7a-907abef79fa7)

Third, my repository is mostly `.yml` files that let virtual machine (provided by GitHub Action) to build mpv using shinchiro/mpv-winbuild-cmake toolchain. These `.yml` files are not the same as in this repository.

**Comment by shinchiro** [comment]
Should be fix later.

**Comment by izumi46** [comment]
> > I saw your mpv-winbuild repository is similar to this one, can you tell me what the differences are with this repository ?
> 
> Firstly, I need to make it clear that [shinchiro/mpv-winbuild-cmake](https://github.com/shinchiro/mpv-winbuild-cmake) (this repo) provides a toolchain for building mpv that anyone can use it to build mpv themselves. You can build the mpv on your own computer by using this toolchain.
> 
> Second, GitHub offers Linux, Windows, and macOS virtual machines to run workflows (builds, tests), just like on your own computer.This feature is called 'GitHub Action', and the workflows are defined by the `.github/workflows/xxxxx.yml`. For example,these files: ![image](https://private-user-images.githubusercontent.com/11155705/327929951-6f961eed-8c6c-49a8-be7a-907abef79fa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MDc4MjAsIm5iZiI6MTcxNDgwNzUyMCwicGF0aCI6Ii8xMTE1NTcwNS8zMjc5Mjk5NTEtNmY5NjFlZWQtOGM2Yy00OWE4LWJlN2EtOTA3YWJlZjc5ZmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDA3MjUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNGY1Nzg4ZWMyNzI1MDYyMzJhMWU4NTVmNTMwMmM5NTA2MmQzMDJmMjQwNDFmOTM1YjRjMjUzYzllZThkZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p1D-cHBDmcJNrefKE9m7zeSFsHlcKpF5mYvAzDvTT7s)
> 
> Third, my repository is mostly `.yml` files that let virtual machine (provided by GitHub Action) to build mpv using shinchiro/mpv-winbuild-cmake toolchain. These `.yml` files are not the same as in this repository.

I see, thanks for your reply.
