### ISSUE TITLE
No video output with Hwdec=auto since the June 11 Commits

### ISSUE THREAD

**Issue by Raza-0007** [shinchiro/mpv-winbuild-cmake#685]
Hello guys,

Since the June 11 commits, I have no video output if `hwdec` is enabled. I have tested both @shinchiro and @zhongfly builds, and June 11 or older builds from both work fine, any build after that gives no video output while audio plays fine if `hwdec=auto-safe`. Disabling `hwdec` fixes the issue. There has been no commits in mpv since then, so I am assuming it is something to do with the recent June 11 commits here.

My system is Windows 11, Nvidia 1070 (latest driver).

Nothing abnormal in the log but it is attached.

[mpv log.txt](https://github.com/user-attachments/files/15812689/mpv.log.txt)

~Raza

**Comment by zhongfly** [comment]
maybe ffmpeg issue
look like https://github.com/mpv-player/mpv/issues/14343

Jun 11 don't contain https://github.com/FFmpeg/FFmpeg/commit/d725c737fe2a19091b481d4d115fd939e0a674b2, but Jun 12 build contain it.

**Comment by zhongfly** [comment]
Try this build https://github.com/zhongfly/mpv-winbuild/actions/runs/9493732132 ,it has applyed fix from https://ffmpeg.org//pipermail/ffmpeg-devel/2024-June/329504.html

**Comment by Raza-0007** [comment]
Thanks @zhongfly, yes it was FFmpeg issue, and your new build works fine! :smiley:

~Raza

**Comment by zhongfly** [comment]
ffmpeg have fixed this by https://github.com/FFmpeg/FFmpeg/commit/0060a368b175b1cbc01800af2d3d17ca9f88970c
You can close this issue now.
