### ISSUE TITLE
LUAJIT_USE_SYSMALLOC

### ISSUE THREAD

**Issue by wbtcpip2** [shinchiro/mpv-winbuild-cmake#695]
hello, it seems the cause of a 4 years old memory leak has been discovered.
https://github.com/mpv-player/mpv/issues/14451

would it be possible to use the flag -DLUAJIT_USE_SYSMALLOC in the shinchiro builds?

**Comment by wbtcpip2** [comment]
thank you.
it seems they have fixed
https://github.com/mpv-player/mpv/pull/14457

so i don't know if it's still necessary to use LUAJIT_USE_SYSMALLOC or not

**Comment by shinchiro** [comment]
`LUAJIT_USE_SYSMALLOC` might have some drawback in performance based on dev's comment:
https://github.com/openresty/luajit2/blob/dc397b66e6c8065185343cbe5dbeb4532f8e0b92/src/Makefile#L124-L130
Imo, it's helpful for debugging but not for release
