### ISSUE TITLE
info.conf volume and playback speed controls unresponsive after 20240812 update

### ISSUE THREAD

**Issue by plissken1138** [shinchiro/mpv-winbuild-cmake#698]
Volume +/- controls unresponsive after 20240812 update.

When reverted back to 20240812 the controls work.

Win10Edu

**Comment by plissken1138** [comment]
OK so **add speed** and **add volume** don't work anymore or what? 

I had keybinded + and - to volume control 
and / and * to playback speed control.

After 20240812 those commands are unresponsive. / and * are reset to default volume control, regardless of info.conf entries.

So what are new **add speed** and **add volume** commands?

**Comment by zhongfly** [comment]
1. report bug or ask question about mpv in https://github.com/mpv-player/mpv ,not here
2. `input.conf`, not `info.conf`
3. After https://github.com/mpv-player/mpv/commit/f3a00ea131d5c308e4b0bab49d8913870aaa65d4, the `+ - * /` keys in numpad remap to `KP_ADD/KP_SUBTRACT/KP_MULTIPLY/KP_DIVIDE`.
4. If you don't understand , see example: https://github.com/mpv-player/mpv/commit/d06f3d39cb840f8839e8d0ef9ff1fa065651031f

**Comment by plissken1138** [comment]
>     3. After [mpv-player/mpv@f3a00ea](https://github.com/mpv-player/mpv/commit/f3a00ea131d5c308e4b0bab49d8913870aaa65d4), the `+ - * /` keys in numpad remap to `KP_ADD/KP_SUBTRACT/KP_MULTIPLY/KP_DIVIDE`.
> 

thanks. 

it's a bit frustrating finding out these things only when something stops working.
