### ISSUE TITLE
mpv clang build Error

### ISSUE THREAD

**Issue by nicaicaii** [shinchiro/mpv-winbuild-cmake#699]
https://github.com/nicaicaii/mpv-winbuild-cmake/actions/runs/10607594256/job/29400274569
gcc also error
https://github.com/nicaicaii/mpv-winbuild-cmake/actions/runs/10607995286/job/29401371537
ffmpeg-configure-err.log
`/__w/mpv-winbuild-cmake/mpv-winbuild-cmake/build_x86_64/exec: line 13: /__w/mpv-winbuild-cmake/mpv-winbuild-cmake/src_packages/ffmpeg/configure: Permission denied`

**Comment by shinchiro** [comment]
Permission problem
