### ISSUE TITLE
Feature Request: AArch64 builds

### ISSUE THREAD

**Issue by TreeBranches** [shinchiro/mpv-winbuild-cmake#700]
Throwing this out there to say that there's at least one vote for an ARM build of MPV for these new battery efficient PC's.

I'm an MPC-HC refugee as the current maintainer seems resistant to any and every request made on Git, so I'm hoping MPV are a little friendlier :)

Much appreciated.

**Comment by hooke007** [comment]
https://github.com/minnyres/mpv-windows-arm64

**Comment by shinchiro** [comment]
Kindly reopen that PR. I didnt even get to review it enough before it get closed

**Comment by shinchiro** [comment]
Can you test this aarch build?
[mpv-aarch64-20240915-git-429e379.zip](https://github.com/user-attachments/files/17004897/mpv-aarch64-20240915-git-429e379.zip)

**Comment by shinchiro** [comment]
Does any feature is missing? The exe size is more smaller than x86 version

**Comment by TreeBranches** [comment]
I've been using it the last few days and personally haven't noticed any issues or anything missing from the main release. Thanks for the quick response!

**Comment by shinchiro** [comment]
There's now aarch64 build in releases. I assumed the the build is working fine
