### ISSUE TITLE
Issues when using Vulkan vs d3d11

### ISSUE THREAD

**Issue by xian-sean-li** [shinchiro/mpv-winbuild-cmake#709]
Setting gpu-api = vulkan is having rendering problems on the latest builds. No issues on the 20241007 build but any build after that will either not render correctly or have lots of stuttering.

MPV: mpv-x86_64-v3

System Specs
CPU: 7800x3d
GPU Radeon 6900xt

**Comment by CharlesMengCA** [comment]
You should report the problem here: https://github.com/mpv-player/mpv
