### ISSUE TITLE
is there a feature to automatically add `mpv` as a `path` in `environment variable` to use `mpv` from `terminal`/`Command Prompt` easily

### ISSUE THREAD

**Issue by candrapersada** [shinchiro/mpv-winbuild-cmake#714]
is there a feature to automatically add `mpv` as a `path` in windows `environment variable`?

**Comment by rorgoroth** [comment]
C:\Users\YourUserName\Documents\WindowsPowerShell\profile.ps1

```
$env:Path += ";C:\Users\YourUserName\PathToMPV\"
```

**Comment by candrapersada** [comment]
> C:\Users\YourUserName\Documents\WindowsPowerShell\profile.ps1
> 
> ```
> $env:Path += ";C:\Users\YourUserName\PathToMPV\"
> ```

it's only temporary after closing it you have to try doing it again

**Comment by rorgoroth** [comment]
> > C:\Users\YourUserName\Documents\WindowsPowerShell\profile.ps1
> > ```
> > $env:Path += ";C:\Users\YourUserName\PathToMPV\"
> > ```
> 
> it's only temporary after closing it you have to try doing it again

Then you have done something wrong.
You add that line to your powershell profile.ps1, as I wrote, it will be in your environment for all spawned sessions. I've been using it like this for years without issue. The only quirk is autocomplete the binary (using tab) selects mpv.com first before mpv.exe but this isn't an issue as mpv.com works just fine to launch the player.
