### ISSUE TITLE
What is the advantage of this over the official build helper scripts of mpv?

### ISSUE THREAD

**Issue by ghost** [shinchiro/mpv-winbuild-cmake#715]
Here is the official build helper scripts of mpv: https://github.com/mpv-player/mpv-build

**Comment by mh466lfa** [comment]
It's CMake-based. I think this could be considered as an advantage. But it still requires GCC/Clang and MSYS2 on Windows. IMO, the advantage of CMake is it could work with MSVC and it doesn't need a POSIX environment to run shell scripts. It's not true here.

Maybe it's designed to cross compile from Linux to Windows?

**Comment by mh466lfa** [comment]
Nope. This project is not even about cross compiling. The developer dictated to use the Cygwin/MSYS2 MSYS GCC on Windows. So this is definitely not about cross compiling. To cross compile from Linux to Windows, you must use MinGW-w64 cross compilers.

**Comment by ghost** [comment]
This script will compile its own GCC/Clang. If you only want to compile mpv from source, just use the official build helper script.

**Comment by chadchoi** [comment]
I will use the prebuilt binaries. I only want the latest mpv. I don't want to compile from source. I didn't know that this project offers prebuilt binaries. I thought that I need to compile from source so I asked this question.

**Comment by ghost** [comment]
I only want the latest mpv on Windows so I will use the prebuilt binaries. I don't know that this project also offers prebuilt binaries. I thought that I will need to compile from source (using MSYS2) so I asked this question.

Btw, I also have Linux and I'm curious to see how cross compiling works. But compiling my own GCC/Clang is a showstopper for me. Why can't I use the cross compilers provided by the Linux distro? I'm using Debian and it has packages for mingw-w64 cross compiler (GCC). There is also prebuilt version of llvm-mingw (Clang) for Linux. So both GCC and Clang cross compilers are available as prebuilt binaries. Why do I need to compile my own cross compiler?
