### ISSUE TITLE
Bug - mpv crashes when resizing window with vo=gpu-next option enabled

### ISSUE THREAD

**Issue by pcotaku** [shinchiro/mpv-winbuild-cmake#729]
The `--vo=gpu-next` backend driver causes mpv to crash when resizing its window lower than approximately 38%×38% of its `--autofit` capacity on my laptop featuring a Qualcomm(R) Adreno(TM) X1-85 GPU. This behaviour occurs during media playback and idle mode. However, this behaviour doesn't occur while rendering content on other backends, like `--vo=gpu` and `--vo=direct3d`; it only occurs when the console parses the `--vo=gpu-next` parameter. Furthermore, the console doesn't print any error indicating why it crashes with the `--vo=gpu-next` backend driver enabled. 

Incidentally, the console prints the following error messages when using `--vo=gpu`; however, these errors don't interfere with media playback. 
`[vo/gpu] Unrecognized/unavailable FORMAT name: 'rgba16f'!`
`[vo/gpu] Unrecognized command 'PARAM distance_coeff'!`

Strangely enough, the console doesn't print these errors with the `--vo=gpu-next` video renderer enabled.

**Comment by zhongfly** [comment]
report mpv related issue to mpv repo.
https://github.com/mpv-player/mpv

**Comment by pcotaku** [comment]
Merry Christmas!

I've reported the issue to the repo. Thanks for the heads-up, zhongfly.

https://github.com/mpv-player/mpv/issues/15573
