### ISSUE TITLE
Could not initialize VapourSynth scripting

### ISSUE THREAD

**Issue by deama** [shinchiro/mpv-winbuild-cmake#73]
Alright so I've set it all up (at least I think I done it right) but it just keeps coming up with that damn error:
`[   7.672][f][vapoursynth] Could not initialize VapourSynth scripting`
This error is from the mpv log file.

I'm not sure what the problem is, the internet isn't helping much, and I've tried this on another computer (very low end) and it works, I also tried it on a friends computer (about same as mine) and it works there too, it just doesn't work on my one specifically...

I'm using Windows 7, my lower end comp uses windows 7 too, and my friend uses windows 10.

The setup I did was I followed the quick steps outlined in another issue around here, here is a quote:
```

1.    Download latest Vapoursynth with same type (32/64-bit) as mpv. If you've download portable version, extract it in same folder as mpv.exe
 2.   Download Python 3.6.x. If you want portable one, download the embed one and extract in same folder as mpv.exe
 3.   Download additional vapoursynth plugin like mvtools. Extract the library and copy into vapoursynth64\plugins folder
 4.  You may need additional plugins, depends on what the vapoursynth script do
```

**Comment by shinchiro** [comment]
If it works on a computer then it is not a problem with the builds itself
