### ISSUE TITLE
Upstream spirv-tools bug failing some shaders on d3d11 

### ISSUE THREAD

**Issue by voltmtr** [shinchiro/mpv-winbuild-cmake#73]
https://github.com/bloc97/Anime4K/issues/66
https://github.com/mpv-player/mpv/issues/7500
https://github.com/KhronosGroup/SPIRV-Tools/issues/3244

eg: Bug caused by upstream change https://github.com/KhronosGroup/SPIRV-Tools/commit/e7afeb060e1637ca964c62517c3e6c225704b7eb causing issues with d3d11 backend with glsl shaders using if( ). I suggest using last known good commit  at 6729c4a7ce98bc5d1b6e1d3a36c6c9ccf87d8966 or reverting the problematic commit with a patch until issue is fixed in a proper manner

**Comment by shinchiro** [comment]
Since it is only affecting d3d11 backend, someone should report it on spirv-cross repo.

Unfortunately, the way all these spirv things related, clamping commit is not good idea.
