### ISSUE TITLE
Can you provide static libraries?

### ISSUE THREAD

**Issue by wangwenx190** [shinchiro/mpv-winbuild-cmake#74]
Static libraries are very useful as well.

**Comment by wangwenx190** [comment]
Your repo is great and it's really helpful. Thanks. But in my country, some of the repos to build libmpv are VERY hard to access, so I just can't build libmpv myself. That's why I'm requesting you to provide the static libraries, otherwise I'll build them on my own.

**Comment by shinchiro** [comment]
I put libmpv in SF:
https://sourceforge.net/projects/mpv-player-windows/files/libmpv/

**Comment by wangwenx190** [comment]
>
> I put libmpv in SF:
> https://sourceforge.net/projects/mpv-player-windows/files/libmpv/
>

I know. I'm using it and it really helps me a lot. Thanks. But I'm requesting static libraries, not shared libraries.
