### ISSUE TITLE
Weird issue with lua scripts and user-opts in recent builds

### ISSUE THREAD

**Issue by xnoreq** [shinchiro/mpv-winbuild-cmake#78]
Hello,

in the stable version (0.32) I have compiled a month ago, this  `mpv\scripts\test.lua` script:
```
local opt = require 'mp.options'

local user_opts = {
    enabled = false,
}
opt.read_options(user_opts)

print(user_opts.enabled)

```

with this `mpv\script-opts\test.conf` file:
```
enabled=no
```

and starting `mpv.com` resulted in this output:
```
[test] disabled
```

Recent builds (of the same stable 0.32), however, result in this output:
```
 to boolean!  Can't convert no
' for key 'enabled' est.conf:1 error converting value 'no
[test] false
```

Any ideas what is going on here?
I tried reverting to luajit v2.0 and also gcc 9 but that didn't seem to have any effect.

**Comment by shinchiro** [comment]
This caused by luajit's patch mean to enable `io.open` to accept unicode name in path. Temporary workaround is to convert the `.conf` files to LF ending or disable the patch.

**Comment by xnoreq** [comment]
Thanks! LF line endings fixed it.
