### ISSUE TITLE
Failed to initialize SPIR-V compiler on latest nvidia driver 411.63

### ISSUE THREAD

**Issue by Robblle** [shinchiro/mpv-winbuild-cmake#8]
After installing the latest nvidia driver 411.63 I get the error message that SPIR-V compiler isn't being initialized. Previous driver version was 399.24.

mpv.conf snippet
```
profile=gpu-hq
gpu-api=vulkan
spirv-compiler=nvidia
```
On mpv 0.29.0-30-g6eb59fea2f
GTX 1070

**Comment by shinchiro** [comment]
Probably driver issue. I can initialize the `nvidia` spirv-v compiler just fine on my GeForce GT 1030
