### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by andrew-boyarshin** [shinchiro/mpv-winbuild-cmake#80]
Successfully compiled mpv for Windows x64 target using this project using Ubuntu 20.04 on WSL2. Thank you for your work on these build scripts!

Additional packages required:
1. `selinux-utils` for `selinuxenabled` command, executed by some python script during build.
2. `python` for Python 2 alias, used by mpv build itself.

WSL notes:
Apparently, _some_ GNU Autoconf scripts check for something like "are we cross-compiling?" by trying to execute freshly-compiled _.exe_ file, and don't expect the _exe_ to actually work. So at least 4 configure scripts hang on `/tools/init ./conftest.exe` (fontconfig, nettle, and I don't remember the others). To solve this, I had to add this to my `/etc/wsl.conf`:
```ini
[interop]
enabled=false
appendWindowsPath=false
```

A little nice-to-have:
Ability to override _mpv_ source repository (point it to my fork, for instance) by setting a CMake variable. Or any other means to enable _mpv_ development.

**Comment by shinchiro** [comment]
> Ability to override mpv source repository (point it to my fork, for instance) by setting a CMake variable. Or any other means to enable mpv development.

You  can edit `mpv.cmake` file and change `GIT_REPOSITORY` to ur repo

**Comment by andrew-boyarshin** [comment]
@shinchiro yeah, I'm using this already, but it's always best to preserve build scripts unmodified (less trouble when updating) and use env vars instead. Thanks again!
