### ISSUE TITLE
You manually enabled the feature 'vulkan', but the autodetection check failed.

### ISSUE THREAD

**Issue by CharlesMengCA** [shinchiro/mpv-winbuild-cmake#83]
Hi Shinchiro,

I really like you build and used it a lot. Thanks a lot for your work.

I recently got following error during build on Arch Linux. even with a fresh install of everything.

Could you check and help?  Thanks again.

You manually enabled the feature 'vulkan', but the autodetection check failed.

Checking for Vulkan context support
['pkg-config', 'vulkan', '--libs', '--cflags', '--static', 'vulkan']
err: Package vulkan was not found in the pkg-config search path.
Perhaps you should add the directory containing `vulkan.pc'
to the PKG_CONFIG_PATH environment variable
Package 'vulkan', required by 'virtual:world', not found
Package 'vulkan', required by 'virtual:world', not found

from /root/mpv-winbuild-cmake/build64/packages/mpv-prefix/src/mpv: The configuration failed
no ('vulkan' not found)

**Comment by shinchiro** [comment]
Worked fine here.
https://github.com/shinchiro/mpv-winbuild-cmake/blob/45ffbfd4ccd4a7a1b48d757fe145175a359b2d14/exec.in#L4
^ The file always called before running `configure` & `install` so there's no need to explicitly define it in each cmake file

**Comment by CharlesMengCA** [comment]
Following line in  Vulkan-Loader/loader/CMakeLists.txt caused the problem. vulkan.pc was not generated.
if(PKG_CONFIG_FOUND)
Temporarily changed to 
if(TRUE)
and the problem is gone.
