### ISSUE TITLE
how to build static libmpv library?

### ISSUE THREAD

**Issue by lyg1949** [shinchiro/mpv-winbuild-cmake#89]
this build script only build dll and exe, if i want to build static libmpv library ,how to modify build scripts?

thank you!

**Comment by shinchiro** [comment]
Delete this line
https://github.com/shinchiro/mpv-winbuild-cmake/blob/77c3b5ee40d71a82768742d5c16e837e50356772/packages/mpv.cmake#L34
Replace it with `--enable-libmpv-static`

**Comment by lyg1949** [comment]
thank you!
