### ISSUE TITLE
Segfault building 32bit shaderc with gcc-10-20200822

### ISSUE THREAD

**Issue by belonesox** [shinchiro/mpv-winbuild-cmake#92]
I am trying to reproduce msys 32bit build.
 on commit ``433a8d070d66c49c864f2ca994f8125761360a06``

``URL ftp://ftp.mirrorservice.org/sites/sourceware.org/pub/gcc/snapshots/10-20200822/gcc-10-20200822.tar.xz``
+
``mpv-winbuild-cmake\build32\packages\shaderc-prefix\src\shaderc`` — trying ``main`` + all tags 
``v2018.0, v2019.0, v2019.1, v2020.0, …, v2020.3``

On (i tried even on -j1)
```
'make' '-j1' '-C' '/c/projects/mpv-winbuild-cmake/build32/packages/shaderc-prefix/src/shaderc-build'
```
got *Segmentation fault*
```
In file included from /c/projects/mpv-winbuild-cmake/build32/packages/shaderc-prefix/src/shaderc/third_party/glslang/glslang/MachineIndependent/pch.h:47,
                 from /c/projects/mpv-winbuild-cmake/build32/packages/shaderc-prefix/src/shaderc-build/third_party/glslang/glslang/CMakeFiles/MachineIndependent.dir/cmake_pch.hxx:5,
                 from <command-line>:
/c/projects/mpv-winbuild-cmake/build32/packages/shaderc-prefix/src/shaderc/third_party/glslang/glslang/MachineIndependent/ScanContext.h:93:1: internal compiler error: Segmentation fault
   93 | } // end namespace glslang
      | ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
```

I have no good idea except enumerating gcc versions, may be someone have better idea or can check building on this commit?

**Comment by shinchiro** [comment]
Well, it's msys problem (or limitation?) sadly. I advise you to use WSL instead
