### ISSUE TITLE
Thank you very much!

### ISSUE THREAD

**Issue by mrkaban** [shinchiro/mpv-winbuild-cmake#93]
Thank you very much for the program distributed under a free open license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%BC%D1%83%D0%BB%D1%8C%D1%82%D0%B8%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0/%D0%B2%D0%BE%D1%81%D0%BF%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5/mpv-%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0-%D0%BF%D0%BB%D0%B5%D0%B5%D1%80.html).

Please do not drop the project, this is a very interesting program!

**Comment by shinchiro** [comment]
You're welcome
