### ISSUE TITLE
D3DCompiler DLL not found

### ISSUE THREAD

**Issue by ek4** [shinchiro/mpv-winbuild-cmake#95]
I am on Windows 7 SP1 with the platform update.

I have mpv.exe and d3dcompiler_43.dll from your release.

The two files are in the same directory. The directory is included in my PATH environment variable.

When I run mpv from the command prompt it gives me a message from vo/gpu/d3d11 about not finding the D3DCompiler DLL.

I havent tried your builds before, but this wasnt a problem with lachs0r's old builds.

**Comment by ek4** [comment]
Do you need Universal CRT for this?

**Comment by ek4** [comment]
I guess you do.

By the way, the compiler you package isnt the most recent.

https://developer.microsoft.com/en-us/windows/downloads/sdk-archive

Also, there is no need to rename it. 47 is fine.

**Comment by garoto** [comment]
I just delete the shipped `d3dcompiler_43.dll` or don't extract it all on my Windows 8.1 and everything just works. Perhaps because I took the time to install the latest DX redistributables a long time ago.

**Comment by shinchiro** [comment]
Fyi, the mpv always search `d3dcompiler_43.dll` inside ur windows dir. If the version of d3dcompiler there is old, it still will be used even there's new d3dcompiler inside mpv folder.

Reference: https://github.com/mpv-player/mpv/blob/8e50d7a746f88c44cc40d0ff87d8540253d2d996/video/out/d3d11/ra_d3d11.c#L2276

**Comment by ek4** [comment]
So the packaged compiler is only for peeps on old Windows..
